Synthetic data generation

In [ ]:
import os
import csv
import glob
import numpy as np
import openlpt as lpt

# --- Settings ---
cam_dir = r"H:\20260210\T0\Round1\camFile"
out_csv = r"H:\20260210\T0\synthetic_wand_points.csv"

N_pairs = 2500
wand_len = 10.0
R_small = 1.5  # mm
R_large = 2.0  # mm

# --- Load all cameras ---
cam_files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
if not cam_files:
    raise FileNotFoundError(f"No cam*.txt found in {cam_dir}")

cams = {}
for path in cam_files:
    name = os.path.basename(path)
    # Extract integer id from camX.txt
    cid_str = name.replace("cam", "").replace(".txt", "")
    cid = int(cid_str)
    cam = lpt.Camera()
    cam.loadParameters(path)
    cams[cid] = cam

cam_ids = sorted(cams.keys())
print("Loaded cameras:", cam_ids)

# --- Helper: project point and compute pixel radius ---
def estimate_radius_px(cam, X, R_mm):
    """
    Estimate pixel radius for a 3D sphere of radius R_mm at X
    using finite differences and cam.project only.
    Returns NaN if projection fails.
    """
    X = np.asarray(X, dtype=float)

    # Project center
    ptC = lpt.Pt3D(float(X[0]), float(X[1]), float(X[2]))
    uvC = cam.project(ptC)
    u0, v0 = float(uvC[0]), float(uvC[1])
    if not np.isfinite(u0) or not np.isfinite(v0):
        return np.nan

    # Use camera line-of-sight direction to build tangent basis
    # Approx: dir = (X - C), where C from pinplate param
    pp = cam._pinplate_param
    C = np.array([pp.t_vec_inv[0], pp.t_vec_inv[1], pp.t_vec_inv[2]], dtype=float)
    dir_vec = X - C
    norm = np.linalg.norm(dir_vec)
    if not np.isfinite(norm) or norm < 1e-9:
        return np.nan
    dir_vec /= norm

    # Build two orthonormal tangents
    tmp = np.array([1.0, 0.0, 0.0]) if abs(dir_vec[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
    t1 = np.cross(dir_vec, tmp); t1 /= np.linalg.norm(t1)
    t2 = np.cross(dir_vec, t1)

    # Project ±R along tangents
    def proj_offset(t):
        Xp = X + R_mm * t
        Xm = X - R_mm * t
        up = cam.project(lpt.Pt3D(float(Xp[0]), float(Xp[1]), float(Xp[2])))
        um = cam.project(lpt.Pt3D(float(Xm[0]), float(Xm[1]), float(Xm[2])))
        up = np.array([float(up[0]), float(up[1])], dtype=float)
        um = np.array([float(um[0]), float(um[1])], dtype=float)
        if np.any(~np.isfinite(up)) or np.any(~np.isfinite(um)):
            return np.nan
        return 0.5 * np.linalg.norm(up - um)

    r1 = proj_offset(t1)
    r2 = proj_offset(t2)

    if not np.isfinite(r1) and not np.isfinite(r2):
        return np.nan
    if not np.isfinite(r1):
        return r2
    if not np.isfinite(r2):
        return r1
    return 0.5 * (r1 + r2)

def project_with_radius(cam, X, R_mm):
    pt = lpt.Pt3D(float(X[0]), float(X[1]), float(X[2]))
    uv = cam.project(pt)
    u = float(uv[0])
    v = float(uv[1])
    if not np.isfinite(u) or not np.isfinite(v):
        return None
    r_px = estimate_radius_px(cam, X, R_mm)
    if not np.isfinite(r_px):
        return None
    return (u, v, float(r_px))

# --- Generate valid wand pairs ---
rows = []
frame_id = 0

rng = np.random.default_rng(42)

def random_unit_vector():
    v = rng.normal(size=3)
    v /= np.linalg.norm(v)
    return v

while frame_id < N_pairs:
    # random center within cube, but ensure endpoints stay inside [-10,10]
    # use center in [-5,5] so ±5 stays inside
    C = rng.uniform(-5.0, 5.0, size=3)
    d = random_unit_vector()
    A = C - 0.5 * wand_len * d
    B = C + 0.5 * wand_len * d

    # ensure inside 20x20x20 cube centered at origin
    if np.any(A < -10) or np.any(A > 10) or np.any(B < -10) or np.any(B > 10):
        continue

    # Project for all cams; if any cam fails, reject this pair
    projections = {}
    valid = True
    for cid in cam_ids:
        cam = cams[cid]
        proj_s = project_with_radius(cam, A, R_small)
        proj_l = project_with_radius(cam, B, R_large)
        if (proj_s is None) or (proj_l is None):
            valid = False
            break
        projections[cid] = (proj_s, proj_l)

    if not valid:
        continue    

    # Store rows: Filtered_Small (PointIdx=0), Filtered_Large (PointIdx=1)
    for cid in cam_ids:
        (u_s, v_s, r_s), (u_l, v_l, r_l) = projections[cid]
        rows.append([frame_id, cid, "Filtered_Small", 0, f"{u_s:.3f}", f"{v_s:.3f}", f"{r_s:.3f}", "0"])
        rows.append([frame_id, cid, "Filtered_Large", 1, f"{u_l:.3f}", f"{v_l:.3f}", f"{r_l:.3f}", "0"])

    frame_id += 1
    if frame_id % 100 == 0:
        print(f"Generated frame {frame_id}/{N_pairs}", end="\r")

print("Generated frames:", frame_id)
print("Total rows:", len(rows))

# --- Write CSV ---
with open(out_csv, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Frame", "Camera", "Status", "PointIdx", "X", "Y", "Radius", "Metric"])
    writer.writerows(rows)

print("Saved:", out_csv)

Given true refraction plane, check camera calibration

In [1]:
import os
import re
import csv
import glob
import numpy as np
import cv2

from modules.camera_calibration.wand_calibration.refraction_calibration_BA import (
    RefractiveBAOptimizer,
    RefractiveBAConfig,
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import (
    CppCameraFactory,
)

# -----------------------------
# Paths
# -----------------------------
truth_cam_dir = r"H:\20260210\T0\Round1\camFile"          # 真值平面/介质来源
init_cam_dir  = r"H:\20260210\T0\Synthetic_test\camFile"  # 相机初值来源
out_csv       = r"H:\20260210\T0\synthetic_wand_points.csv"

# 可选：为了先快速验证，限制帧数；想全量就设为 0
MAX_FRAMES = 300

# -----------------------------
# Helpers
# -----------------------------
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and not s.startswith("#"):
            return s, j
        j += 1
    return "", j

def parse_cam_file(path):
    with open(path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()

    d = {}
    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix") or s.startswith("# Camera Matrix K"):
            row, _ = _next_data(lines, i)
            d["f"] = float(row.split()[0])

        elif s.startswith("# Distortion"):
            row, _ = _next_data(lines, i)
            vals = [float(x) for x in row.split(",")]
            d["k1"] = vals[0] if len(vals) > 0 else 0.0
            d["k2"] = vals[1] if len(vals) > 1 else 0.0

        elif s.startswith("# Rotation Matrix R") or s.startswith("# Rotation Matrix:"):
            r1, _ = _next_data(lines, i)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            R = np.array(
                [
                    [float(x) for x in r1.split()],
                    [float(x) for x in r2.split()],
                    [float(x) for x in r3.split()],
                ],
                dtype=float,
            )
            d["R"] = R

        elif s.startswith("# Translation Vector T") or s.startswith("# Translation Vector:"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "WINDOW_ID=" in s:
            d["wid"] = int(s.split("WINDOW_ID=")[1])

        elif "plane.pt" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "plane.norm_vector" in s:
            row, _ = _next_data(lines, i)
            n = np.array([float(x) for x in row.split()], dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = float(row.split(",")[0])

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = [float(x) for x in row.split(",")]
            # file: obj,win,air -> n3,n2,n1
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()
    d["cx"] = 640.0
    d["cy"] = 400.0
    return d

def load_cam_set(cam_dir, with_plane=True):
    cam_params = {}
    cam_to_window = {}
    window_planes = {}
    window_media = {}

    files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
    if not files:
        raise FileNotFoundError(f"No cam*.txt in {cam_dir}")

    for path in files:
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array(
            [
                d["rvec"][0], d["rvec"][1], d["rvec"][2],
                d["tvec"][0], d["tvec"][1], d["tvec"][2],
                d["f"], d["cx"], d["cy"],
                d.get("k1", 0.0), d.get("k2", 0.0),
            ],
            dtype=np.float64,
        )

        cam_to_window[cid] = d["wid"]

        if with_plane and d["wid"] not in window_planes:
            # 文件里是 farthest interface，优化内部使用 closest interface
            p_closest = d["plane_far"] - d["plane_n"] * d["thickness"]
            wid = d["wid"]
            window_planes[wid] = {
                "plane_pt": p_closest,
                "plane_n": d["plane_n"],
                "initialized": True,
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"],
            }

    return cam_params, cam_to_window, window_planes, window_media

def load_obs_csv(csv_path):
    obsA, obsB = {}, {}
    frames = set()

    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    return obsA, obsB, frames

def rot_err_deg(rvec_est, rvec_gt):
    R1, _ = cv2.Rodrigues(rvec_est)
    R2, _ = cv2.Rodrigues(rvec_gt)
    R = R2 @ R1.T
    c = (np.trace(R) - 1.0) / 2.0
    c = max(-1.0, min(1.0, c))
    return float(np.degrees(np.arccos(c)))

# -----------------------------
# Build test setup
# -----------------------------
cam_gt, map_gt, plane_gt, media_gt = load_cam_set(truth_cam_dir, with_plane=True)
cam_init, map_init, _, _ = load_cam_set(init_cam_dir, with_plane=False)

if map_gt != map_init:
    raise RuntimeError("cam_to_window mismatch between truth and init cam folders")

obsA, obsB, frames_all = load_obs_csv(out_csv)
if MAX_FRAMES > 0:
    frames = frames_all[:MAX_FRAMES]
else:
    frames = frames_all

dataset = {
    "obsA": obsA,
    "obsB": obsB,
    "frames": frames,
    "cam_ids": sorted(cam_init.keys()),
    "est_radius_small_mm": 1.5,
    "est_radius_large_mm": 2.0,
}

class _Base:
    pass

base = _Base()
base.image_size = (800, 1280)

# 用“初始相机 + 真值平面/介质”初始化 C++ 相机
cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_init,
    window_media=media_gt,
    cam_to_window=map_gt,
    window_planes=plane_gt,
)

# -----------------------------
# Progress callback (every nfev=10)
# -----------------------------
cb_count = {"k": 0}
def progress_cb(phase, ray_rmse, len_rmse, cost):
    cb_count["k"] += 1
    # BA内部已改成每10次residual callback一次，这里按nfev=10递增显示
    nfev_est = cb_count["k"] * 10
    print(
        f"[nfev~{nfev_est:4d}] {phase} | "
        f"ray_rmse={ray_rmse:.6f} mm | len_rmse={len_rmse:.6f} mm | cost={cost:.6e}"
    )

cfg = RefractiveBAConfig(
    stage=0,          # 我们手动调用 _optimize_generic
    verbosity=1,      # 可看到更多日志
    max_frames=MAX_FRAMES if MAX_FRAMES > 0 else 0,
)

opt = RefractiveBAOptimizer(
    dataset=dataset,
    cam_params=cam_init,        # 初值（Synthetic_test）
    cams_cpp=cams_cpp,
    cam_to_window=map_gt,
    window_media=media_gt,      # 真值介质
    window_planes=plane_gt,     # 真值平面
    wand_length=10.0,
    config=cfg,
    progress_callback=progress_cb,
)

opt._compute_physical_sigmas()

print("\n=== Before (vs GT) ===")
for cid in sorted(cam_init.keys()):
    e_t = np.linalg.norm(cam_init[cid][3:6] - cam_gt[cid][3:6])
    e_r = rot_err_deg(cam_init[cid][0:3], cam_gt[cid][0:3])
    print(f"Cam {cid}: t_err={e_t:.6f} mm, r_err={e_r:.6f} deg")

# -----------------------------
# Camera-only optimization (planes fixed to truth)
# -----------------------------
opt._optimize_generic(
    mode="cam_only_truth_plane",
    description="CamOnly TruthPlane",
    enable_planes=False,         # 只优化相机
    enable_cam_t=True,
    enable_cam_r=True,
    limit_rot_rad=np.radians(20.0),
    limit_trans_mm=50.0,
    limit_plane_d_mm=0.0,
    limit_plane_angle_rad=0.0,
    ftol=1e-8,
    loss="linear",
)

print("\n=== After (vs GT) ===")
for cid in sorted(cam_init.keys()):
    p = opt.cam_params[cid]
    e_t = np.linalg.norm(p[3:6] - cam_gt[cid][3:6])
    e_r = rot_err_deg(p[0:3], cam_gt[cid][0:3])
    print(f"Cam {cid}: t_err={e_t:.6f} mm, r_err={e_r:.6f} deg")

lam = 2.0 * max(1, len(cam_init))
_, S_ray, S_len, N_ray, N_len = opt.evaluate_residuals(
    opt.window_planes, opt.cam_params, lam, window_media=opt.window_media
)
ray_rmse = np.sqrt(S_ray / max(1, N_ray))
len_rmse = np.sqrt(S_len / max(1, N_len)) if N_len > 0 else 0.0

print("\n=== Final residuals ===")
print(f"frames={len(frames)}, N_ray={N_ray}, N_len={N_len}")
print(f"ray_rmse_mm={ray_rmse:.9f}")
print(f"len_rmse_mm={len_rmse:.9f}")

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
Unit Normalization: sigma_ray=0.0114mm (0.5px at Z=206.0mm), sigma_wand=0.2000mm (2.0%)

=== Before (vs GT) ===
Cam 0: t_err=0.697742 mm, r_err=2.344519 deg
Cam 1: t_err=1.100389 mm, r_err=1.558594 deg
Cam 2: t_err=0.667578 mm, r_err=1.632894 deg
Cam 3: t_err=0.525099 mm, r_err=1.833747 deg
  diff_step: rvec=0.0001, tvec=0.01, plane_d=0.01, plane_ang=0.0001, f=0.1, thick=0.001, k=1e-06
  [CamOnly TruthPlane] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=40.21, S_len=0.20 (J0=0.0222)
[nfev~  10] CamOnly TruthPlane | ray_rmse=0.071562 mm | len_rmse=0.025226 mm | cost=4.695107e+04
[nfev~  20] CamOnly TruthPlane | ray_rmse=0.059677 mm | len_rmse=0.022063 mm | cost=3.265260e+04
[nfev~  30] CamOnly TruthPlane | ray_rmse=0.043556 mm | len_rmse=0.019343 mm | cost=1.739737e+04
[nfev~  40] CamOnly TruthPlane | ray_rmse=0.027230 mm | len_rmse=0.016464 mm | cost=6.803287e+03
[nfev~  50] CamOnly TruthPlane | ray_rmse=0.011491 mm | len_rmse=0.011127 mm | cost=1.213733e+03
[nfev~  60] CamOnly TruthPlane | ray_rmse=0.002477 mm | len_rmse=0.003104 mm | cost=5.651284e+01
[nfev~  70] CamOnly TruthPlane | ray_rmse=0.002101 mm | len_rmse=0.003570 mm | cost=4.082533e+01
[nfev~  80] CamOnly TruthPlane | ray_rmse=0.001991 mm | len_rmse=0.003846 mm | cost=3.678697e+01
[nfev~  90] CamOnly TruthPlane | ray_rmse=0.001876 mm | len_rmse=0.001603 mm | cost=3.234748e+01
[nfev~ 100] CamOnly TruthPlane | ray_rmse=0.001355 mm | len_rmse=0.001105 mm | cost=1.685441e+01
[nfev~ 110] CamOnly TruthPlane | ray_rmse=0.001384 mm | len_rmse=0.001110 mm | cost=1.759880e+01
[nfev~ 120] CamOnly TruthPlane | ray_rmse=0.001245 mm | len_rmse=0.001108 mm | cost=1.423474e+01
[nfev~ 130] CamOnly TruthPlane | ray_rmse=0.001241 mm | len_rmse=0.001110 mm | cost=1.415851e+01
[nfev~ 140] CamOnly TruthPlane | ray_rmse=0.001241 mm | len_rmse=0.001111 mm | cost=1.414707e+01
[nfev~ 150] CamOnly TruthPlane | ray_rmse=0.001241 mm | len_rmse=0.001109 mm | cost=1.415839e+01
[nfev~ 160] CamOnly TruthPlane | ray_rmse=0.001368 mm | len_rmse=0.001111 mm | cost=1.717906e+01
[nfev~ 170] CamOnly TruthPlane | ray_rmse=0.001241 mm | len_rmse=0.001109 mm | cost=1.414660e+01
  Termination: xtol (nfev=23)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.990deg, Δt=0.738mm
    Cam 1: Δr=1.402deg, Δt=1.058mm
    Cam 2: Δr=1.512deg, Δt=0.570mm
    Cam 3: Δr=2.029deg, Δt=0.770mm
    [RefractiveCalib][SIDE-BARRIER] min(sX)=4.7023mm, near(<20um)=0.0%, vio=0, cost/J=0.0e+00
    Final:   S_ray=0.00, S_len=0.00 (JF=0.0000)
      RMSE Ray: 0.1294 -> 0.0012
      RMSE Len: 0.0260 -> 0.0011

=== After (vs GT) ===
Cam 0: t_err=0.124131 mm, r_err=0.408297 deg
Cam 1: t_err=0.221538 mm, r_err=0.329465 deg
Cam 2: t_err=0.228903 mm, r_err=0.320824 deg
Cam 3: t_err=0.247021 mm, r_err=0.396236 deg

=== Final residuals ===
frames=300, N_ray=2400, N_len=300
ray_rmse_mm=0.001240833
len_rmse_mm=0.001109661

Add bias to plane location to check camera calibration

In [2]:
import os
import re
import csv
import glob
import copy
import numpy as np
import cv2
import pandas as pd
import matplotlib.pyplot as plt

from modules.camera_calibration.wand_calibration.refraction_calibration_BA import (
    RefractiveBAOptimizer,
    RefractiveBAConfig,
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import (
    CppCameraFactory,
)

# =========================
# Paths / Settings
# =========================
truth_cam_dir = r"H:\20260210\T0\Round1\camFile"          # 真值平面
init_cam_dir  = r"H:\20260210\T0\Synthetic_test\camFile"  # 相机初值
obs_csv       = r"H:\20260210\T0\synthetic_wand_points.csv"

WAND_LEN_MM = 10.0
R_SMALL_MM = 1.5
R_LARGE_MM = 2.0
MAX_FRAMES = 300          # 0 表示全量
BIAS_LIST_MM = np.arange(-15.0, 15.01, 2.5)  # 你问的偏差设置
SHOW_PROGRESS = True      # True: 每10个nfev打印一次

# =========================
# Helpers
# =========================
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and not s.startswith("#"):
            return s, j
        j += 1
    return "", j

def parse_cam_file(path):
    with open(path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()

    d = {}
    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix") or s.startswith("# Camera Matrix K"):
            row, _ = _next_data(lines, i)
            d["f"] = float(row.split()[0])

        elif s.startswith("# Distortion"):
            row, _ = _next_data(lines, i)
            vals = [float(x) for x in row.split(",")]
            d["k1"] = vals[0] if len(vals) > 0 else 0.0
            d["k2"] = vals[1] if len(vals) > 1 else 0.0

        elif s.startswith("# Rotation Matrix R") or s.startswith("# Rotation Matrix:"):
            r1, _ = _next_data(lines, i)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array(
                [[float(x) for x in r1.split()],
                 [float(x) for x in r2.split()],
                 [float(x) for x in r3.split()]],
                dtype=float
            )

        elif s.startswith("# Translation Vector T") or s.startswith("# Translation Vector:"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "WINDOW_ID=" in s:
            d["wid"] = int(s.split("WINDOW_ID=")[1])

        elif "plane.pt" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "plane.norm_vector" in s:
            row, _ = _next_data(lines, i)
            n = np.array([float(x) for x in row.split()], dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = float(row.split(",")[0])

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = [float(x) for x in row.split(",")]  # obj,win,air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()
    d["cx"] = 640.0
    d["cy"] = 400.0
    return d

def load_cam_set(cam_dir, with_plane=True):
    cam_params = {}
    cam_to_window = {}
    window_planes = {}
    window_media = {}

    files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
    if not files:
        raise FileNotFoundError(f"No cam*.txt found in {cam_dir}")

    for path in files:
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array(
            [
                d["rvec"][0], d["rvec"][1], d["rvec"][2],
                d["tvec"][0], d["tvec"][1], d["tvec"][2],
                d["f"], d["cx"], d["cy"], d.get("k1", 0.0), d.get("k2", 0.0),
            ],
            dtype=np.float64,
        )
        cam_to_window[cid] = d["wid"]

        if with_plane and d["wid"] not in window_planes:
            # 文件中是 farthest interface；优化内部用 closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            wid = d["wid"]
            window_planes[wid] = {
                "plane_pt": p_close,
                "plane_n": d["plane_n"],
                "initialized": True,
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"],
            }

    return cam_params, cam_to_window, window_planes, window_media

def load_obs_dataset(csv_path, max_frames=0):
    obsA, obsB = {}, {}
    frames = set()

    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {
        "obsA": obsA,
        "obsB": obsB,
        "frames": frames,
        "cam_ids": None,  # later填
        "est_radius_small_mm": R_SMALL_MM,
        "est_radius_large_mm": R_LARGE_MM,
    }

def rot_err_deg(rvec_est, rvec_gt):
    R1, _ = cv2.Rodrigues(rvec_est)
    R2, _ = cv2.Rodrigues(rvec_gt)
    R = R2 @ R1.T
    c = (np.trace(R) - 1.0) / 2.0
    c = np.clip(c, -1.0, 1.0)
    return float(np.degrees(np.arccos(c)))

def mean_cam_err(cam_est, cam_gt):
    t_err = []
    r_err = []
    for cid in sorted(cam_gt.keys()):
        t_err.append(np.linalg.norm(cam_est[cid][3:6] - cam_gt[cid][3:6]))
        r_err.append(rot_err_deg(cam_est[cid][0:3], cam_gt[cid][0:3]))
    return float(np.mean(t_err)), float(np.mean(r_err))

def apply_plane_bias(truth_planes, bias_mm):
    """沿每个window法向将plane_pt(closest)平移 bias_mm。"""
    planes = copy.deepcopy(truth_planes)
    for wid, pl in planes.items():
        n = np.asarray(pl["plane_n"], dtype=float)
        planes[wid]["plane_pt"] = np.asarray(pl["plane_pt"], dtype=float) + bias_mm * n
        planes[wid]["initialized"] = True
    return planes

# =========================
# Load baseline data
# =========================
cam_truth, cam2win_truth, plane_truth, media_truth = load_cam_set(truth_cam_dir, with_plane=True)
cam_init_base, cam2win_init, _, _ = load_cam_set(init_cam_dir, with_plane=False)
if cam2win_truth != cam2win_init:
    raise RuntimeError("cam_to_window mismatch between truth and init")

dataset = load_obs_dataset(obs_csv, max_frames=MAX_FRAMES)
dataset["cam_ids"] = sorted(cam_init_base.keys())

print("Cams:", sorted(cam_init_base.keys()))
print("Frames used:", len(dataset["frames"]))
print("Bias list (mm):", BIAS_LIST_MM)

# =========================
# Experiment A
# =========================
records = []

for bias in BIAS_LIST_MM:
    print(f"\n=== Bias {bias:+.2f} mm ===")

    # 相机初值每次重置
    cam_init = {cid: p.copy() for cid, p in cam_init_base.items()}

    # 真值平面加偏差
    plane_biased = apply_plane_bias(plane_truth, bias)

    # C++ cams: 初始相机 + 偏置平面 + 真值介质
    class _Base:
        pass
    base = _Base()
    base.image_size = (800, 1280)

    cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
        base=base,
        cam_params=cam_init,
        window_media=media_truth,
        cam_to_window=cam2win_truth,
        window_planes=plane_biased,
    )

    # progress callback: 每10个nfev
    cb_counter = {"k": 0}
    def progress_cb(phase, ray_rmse, len_rmse, cost):
        if not SHOW_PROGRESS:
            return
        cb_counter["k"] += 1
        nfev_est = cb_counter["k"] * 10
        print(
            f"[nfev~{nfev_est:4d}] {phase} | "
            f"ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | cost={cost:.6e}"
        )

    cfg = RefractiveBAConfig(
        stage=0,
        verbosity=0,
        max_frames=(MAX_FRAMES if MAX_FRAMES > 0 else 0),
    )

    opt = RefractiveBAOptimizer(
        dataset=dataset,
        cam_params=cam_init,
        cams_cpp=cams_cpp,
        cam_to_window=cam2win_truth,
        window_media=media_truth,
        window_planes=plane_biased,
        wand_length=WAND_LEN_MM,
        config=cfg,
        progress_callback=progress_cb,
    )
    opt._compute_physical_sigmas()

    # A: 只优化相机参数，平面固定
    opt._optimize_generic(
        mode="expA_cam_only",
        description="ExpA CamOnly",
        enable_planes=False,
        enable_cam_t=True,
        enable_cam_r=True,
        limit_rot_rad=np.radians(20.0),
        limit_trans_mm=50.0,
        limit_plane_d_mm=0.0,
        limit_plane_angle_rad=0.0,
        ftol=1e-7,
        loss="linear",
    )

    lam = 2.0 * max(1, len(cam_init))
    _, S_ray, S_len, N_ray, N_len = opt.evaluate_residuals(
        opt.window_planes, opt.cam_params, lam, window_media=opt.window_media
    )
    ray_rmse = np.sqrt(S_ray / max(1, N_ray))
    len_rmse = np.sqrt(S_len / max(1, N_len)) if N_len > 0 else np.nan

    cam_t_err_mean, cam_r_err_mean = mean_cam_err(opt.cam_params, cam_truth)

    records.append({
        "bias_mm": float(bias),
        "ray_rmse_mm": float(ray_rmse),
        "len_rmse_mm": float(len_rmse),
        "cam_t_err_mean_mm": cam_t_err_mean,
        "cam_r_err_mean_deg": cam_r_err_mean,
        "N_ray": int(N_ray),
        "N_len": int(N_len),
    })

dfA = pd.DataFrame(records).sort_values("bias_mm").reset_index(drop=True)
display(dfA)

plt.figure(figsize=(7,4))
plt.plot(dfA["bias_mm"], dfA["ray_rmse_mm"], marker="o")
plt.xlabel("Plane bias along normal (mm)")
plt.ylabel("Ray RMSE (mm)")
plt.title("Experiment A: Plane Bias vs Ray RMSE (Camera-only optimize)")
plt.grid(True, alpha=0.3)
plt.show()

Cams: [0, 1, 2, 3]
Frames used: 300
Bias list (mm): [-15.  -12.5 -10.   -7.5  -5.   -2.5   0.    2.5   5.    7.5  10.   12.5
  15. ]

=== Bias -15.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=1522.64, S_len=10.87 (J0=0.9243)
[nfev~  10] ExpA CamOnly | ray=0.706828 mm | len=0.187868 mm | cost=4.572865e+06
[nfev~  20] ExpA CamOnly | ray=0.528830 mm | len=0.183165 mm | cost=2.560134e+06
[nfev~  30] ExpA CamOnly | ray=0.182582 mm | len=0.174634 mm | cost=3.059692e+05
[nfev~  40] ExpA CamOnly | ray=0.038963 mm | len=0.152343 mm | cost=1.458809e+04
[nfev~  50] ExpA CamOnly | ray=0.009081 mm | len=0.049766 mm | cost=8.289917e+02
[nfev~  60] ExpA CamOnly | ray=0.004865 mm | len=0.010948 mm | cost=2.202025e+02
[nfev~  70] ExpA CamOnly | ray=0.003778 mm | len=0.010940 mm | cost=1.341836e+02
[nfev~  80] ExpA CamOnly | ray=0.003774 mm | len=0.010436 mm | cost=1.336051e+02
[nfev~  90] ExpA CamOnly | ray=0.005024 mm | len=0.010934 mm | cost=2.345732e+02
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=2.290deg, Δt=2.568mm
    Cam 1: Δr=0.488deg, Δt=4.421mm
    Cam 2: Δr=0.497deg, Δt=3.987mm
    Cam 3: Δr=1.284deg, Δt=2.746mm
    Final:   S_ray=0.03, S_len=0.04 (JF=0.0010)
      RMSE Ray: 0.7965 -> 0.0038
      RMSE Len: 0.1903 -> 0.0109

=== Bias -12.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=1080.45, S_len=7.59 (J0=0.6526)
[nfev~  10] ExpA CamOnly | ray=0.581836 mm | len=0.156708 mm | cost=3.099363e+06
[nfev~  20] ExpA CamOnly | ray=0.405277 mm | len=0.152267 mm | cost=1.504090e+06
[nfev~  30] ExpA CamOnly | ray=0.085719 mm | len=0.144032 mm | cost=6.787775e+04
[nfev~  40] ExpA CamOnly | ray=0.033255 mm | len=0.124425 mm | cost=1.058667e+04
[nfev~  50] ExpA CamOnly | ray=0.007376 mm | len=0.041885 mm | cost=5.505800e+02
[nfev~  60] ExpA CamOnly | ray=0.005348 mm | len=0.007474 mm | cost=2.634944e+02
[nfev~  70] ExpA CamOnly | ray=0.005356 mm | len=0.007398 mm | cost=2.642535e+02
[nfev~  80] ExpA CamOnly | ray=0.002999 mm | len=0.007389 mm | cost=8.395390e+01
[nfev~  90] ExpA CamOnly | ray=0.003099 mm | len=0.007442 mm | cost=8.959419e+01
  Termination: xtol (nfev=18)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.685deg, Δt=2.097mm
    Cam 1: Δr=0.724deg, Δt=3.978mm
    Cam 2: Δr=0.854deg, Δt=3.539mm
    Cam 3: Δr=1.910deg, Δt=2.253mm
    Final:   S_ray=0.02, S_len=0.02 (JF=0.0005)
      RMSE Ray: 0.6710 -> 0.0031
      RMSE Len: 0.1591 -> 0.0074

=== Bias -10.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=716.31, S_len=4.91 (J0=0.4294)
[nfev~  10] ExpA CamOnly | ray=0.457905 mm | len=0.125767 mm | cost=1.920151e+06
[nfev~  20] ExpA CamOnly | ray=0.283560 mm | len=0.121618 mm | cost=7.365968e+05
[nfev~  30] ExpA CamOnly | ray=0.071829 mm | len=0.113695 mm | cost=4.762436e+04
[nfev~  40] ExpA CamOnly | ray=0.013342 mm | len=0.053723 mm | cost=1.716276e+03
[nfev~  50] ExpA CamOnly | ray=0.005007 mm | len=0.009671 mm | cost=2.323619e+02
[nfev~  60] ExpA CamOnly | ray=0.002904 mm | len=0.005534 mm | cost=7.812636e+01
[nfev~  70] ExpA CamOnly | ray=0.002764 mm | len=0.005450 mm | cost=7.083142e+01
[nfev~  80] ExpA CamOnly | ray=0.003011 mm | len=0.005718 mm | cost=8.398641e+01
[nfev~  90] ExpA CamOnly | ray=0.002073 mm | len=0.005681 mm | cost=4.033083e+01
[nfev~ 100] ExpA CamOnly | ray=0.001975 mm | len=0.005695 mm | cost=3.666793e+01
  Termination: xtol (nfev=19)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.615deg, Δt=1.546mm
    Cam 1: Δr=1.173deg, Δt=3.426mm
    Cam 2: Δr=1.308deg, Δt=2.943mm
    Cam 3: Δr=2.184deg, Δt=1.638mm
    Final:   S_ray=0.01, S_len=0.01 (JF=0.0003)
      RMSE Ray: 0.5463 -> 0.0020
      RMSE Len: 0.1280 -> 0.0057

=== Bias -7.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=430.21, S_len=2.83 (J0=0.2548)
[nfev~  10] ExpA CamOnly | ray=0.336087 mm | len=0.095184 mm | cost=1.034672e+06
[nfev~  20] ExpA CamOnly | ray=0.167413 mm | len=0.091355 mm | cost=2.569128e+05
[nfev~  30] ExpA CamOnly | ray=0.064121 mm | len=0.086722 mm | cost=3.787729e+04
[nfev~  40] ExpA CamOnly | ray=0.013177 mm | len=0.035106 mm | cost=1.627095e+03
[nfev~  50] ExpA CamOnly | ray=0.005075 mm | len=0.007614 mm | cost=2.375842e+02
[nfev~  60] ExpA CamOnly | ray=0.002791 mm | len=0.006114 mm | cost=7.243901e+01
[nfev~  70] ExpA CamOnly | ray=0.002547 mm | len=0.003829 mm | cost=5.983164e+01
[nfev~  80] ExpA CamOnly | ray=0.003288 mm | len=0.004162 mm | cost=9.952970e+01
[nfev~  90] ExpA CamOnly | ray=0.001690 mm | len=0.004156 mm | cost=2.666162e+01
  Termination: xtol (nfev=18)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.859deg, Δt=1.085mm
    Cam 1: Δr=1.232deg, Δt=2.847mm
    Cam 2: Δr=1.345deg, Δt=2.348mm
    Cam 3: Δr=2.031deg, Δt=1.097mm
    Final:   S_ray=0.01, S_len=0.01 (JF=0.0001)
      RMSE Ray: 0.4234 -> 0.0017
      RMSE Len: 0.0972 -> 0.0042

=== Bias -5.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=222.16, S_len=1.36 (J0=0.1287)
[nfev~  10] ExpA CamOnly | ray=0.219352 mm | len=0.065501 mm | cost=4.408608e+05
[nfev~  20] ExpA CamOnly | ray=0.083086 mm | len=0.061969 mm | cost=6.334848e+04
[nfev~  30] ExpA CamOnly | ray=0.047296 mm | len=0.060111 mm | cost=2.059840e+04
[nfev~  40] ExpA CamOnly | ray=0.006962 mm | len=0.024742 mm | cost=4.622968e+02
[nfev~  50] ExpA CamOnly | ray=0.003660 mm | len=0.005639 mm | cost=1.236686e+02
[nfev~  60] ExpA CamOnly | ray=0.002361 mm | len=0.003560 mm | cost=5.142858e+01
[nfev~  70] ExpA CamOnly | ray=0.002559 mm | len=0.003621 mm | cost=6.035542e+01
[nfev~  80] ExpA CamOnly | ray=0.002012 mm | len=0.003606 mm | cost=3.748188e+01
  Termination: xtol (nfev=18)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.691deg, Δt=0.560mm
    Cam 1: Δr=1.162deg, Δt=2.206mm
    Cam 2: Δr=1.288deg, Δt=1.772mm
    Cam 3: Δr=2.109deg, Δt=0.597mm
    Final:   S_ray=0.01, S_len=0.00 (JF=0.0001)
      RMSE Ray: 0.3042 -> 0.0020
      RMSE Len: 0.0672 -> 0.0036

=== Bias -2.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=92.16, S_len=0.48 (J0=0.0512)
[nfev~  10] ExpA CamOnly | ray=0.118766 mm | len=0.038929 mm | cost=1.292814e+05
[nfev~  20] ExpA CamOnly | ray=0.065580 mm | len=0.037219 mm | cost=3.944580e+04
[nfev~  30] ExpA CamOnly | ray=0.031588 mm | len=0.036374 mm | cost=9.181985e+03
[nfev~  40] ExpA CamOnly | ray=0.005505 mm | len=0.009251 mm | cost=2.801840e+02
[nfev~  50] ExpA CamOnly | ray=0.003388 mm | len=0.002038 mm | cost=1.052689e+02
[nfev~  60] ExpA CamOnly | ray=0.002529 mm | len=0.004446 mm | cost=5.918582e+01
[nfev~  70] ExpA CamOnly | ray=0.002397 mm | len=0.004430 mm | cost=5.321509e+01
[nfev~  80] ExpA CamOnly | ray=0.002296 mm | len=0.004430 mm | cost=4.888350e+01
[nfev~  90] ExpA CamOnly | ray=0.002296 mm | len=0.004363 mm | cost=4.887091e+01
  Termination: xtol (nfev=19)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.627deg, Δt=0.220mm
    Cam 1: Δr=1.286deg, Δt=1.639mm
    Cam 2: Δr=1.426deg, Δt=1.202mm
    Cam 3: Δr=2.200deg, Δt=0.369mm
    Final:   S_ray=0.01, S_len=0.01 (JF=0.0002)
      RMSE Ray: 0.1960 -> 0.0023
      RMSE Len: 0.0400 -> 0.0044

=== Bias +0.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=40.21, S_len=0.20 (J0=0.0222)
[nfev~  10] ExpA CamOnly | ray=0.071562 mm | len=0.025226 mm | cost=4.695107e+04
[nfev~  20] ExpA CamOnly | ray=0.059677 mm | len=0.022063 mm | cost=3.265260e+04
[nfev~  30] ExpA CamOnly | ray=0.043556 mm | len=0.019343 mm | cost=1.739737e+04
[nfev~  40] ExpA CamOnly | ray=0.027230 mm | len=0.016464 mm | cost=6.803287e+03
[nfev~  50] ExpA CamOnly | ray=0.011491 mm | len=0.011127 mm | cost=1.213733e+03
[nfev~  60] ExpA CamOnly | ray=0.002477 mm | len=0.003104 mm | cost=5.651284e+01
[nfev~  70] ExpA CamOnly | ray=0.002101 mm | len=0.003570 mm | cost=4.082533e+01
[nfev~  80] ExpA CamOnly | ray=0.001991 mm | len=0.003846 mm | cost=3.678697e+01
[nfev~  90] ExpA CamOnly | ray=0.001876 mm | len=0.001603 mm | cost=3.234748e+01
[nfev~ 100] ExpA CamOnly | ray=0.001355 mm | len=0.001105 mm | cost=1.685441e+01
[nfev~ 110] ExpA CamOnly | ray=0.001384 mm | len=0.001110 mm | cost=1.759880e+01
[nfev~ 120] ExpA CamOnly | ray=0.001245 mm | len=0.001108 mm | cost=1.423474e+01
[nfev~ 130] ExpA CamOnly | ray=0.001241 mm | len=0.001110 mm | cost=1.415851e+01
[nfev~ 140] ExpA CamOnly | ray=0.001241 mm | len=0.001111 mm | cost=1.414707e+01
[nfev~ 150] ExpA CamOnly | ray=0.001241 mm | len=0.001109 mm | cost=1.415839e+01
[nfev~ 160] ExpA CamOnly | ray=0.001368 mm | len=0.001111 mm | cost=1.717906e+01
[nfev~ 170] ExpA CamOnly | ray=0.001241 mm | len=0.001109 mm | cost=1.414660e+01
  Termination: xtol (nfev=23)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.990deg, Δt=0.738mm
    Cam 1: Δr=1.402deg, Δt=1.058mm
    Cam 2: Δr=1.512deg, Δt=0.570mm
    Cam 3: Δr=2.029deg, Δt=0.770mm
    Final:   S_ray=0.00, S_len=0.00 (JF=0.0000)
      RMSE Ray: 0.1294 -> 0.0012
      RMSE Len: 0.0260 -> 0.0011

=== Bias +2.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=95.18, S_len=0.53 (J0=0.0537)
[nfev~  10] ExpA CamOnly | ray=0.139449 mm | len=0.040354 mm | cost=1.783075e+05
[nfev~  20] ExpA CamOnly | ray=0.087553 mm | len=0.036317 mm | cost=7.030718e+04
[nfev~  30] ExpA CamOnly | ray=0.055517 mm | len=0.025413 mm | cost=2.827294e+04
[nfev~  40] ExpA CamOnly | ray=0.022368 mm | len=0.027285 mm | cost=4.608544e+03
[nfev~  50] ExpA CamOnly | ray=0.017922 mm | len=0.046447 mm | cost=3.009225e+03
[nfev~  60] ExpA CamOnly | ray=0.017501 mm | len=0.051527 mm | cost=2.887375e+03
[nfev~  70] ExpA CamOnly | ray=0.017191 mm | len=0.051568 mm | cost=2.788743e+03
[nfev~  80] ExpA CamOnly | ray=0.017012 mm | len=0.051506 mm | cost=2.732439e+03
[nfev~  90] ExpA CamOnly | ray=0.016836 mm | len=0.051518 mm | cost=2.677955e+03
[nfev~ 100] ExpA CamOnly | ray=0.016832 mm | len=0.051525 mm | cost=2.676726e+03
  Termination: xtol (nfev=18)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=4.190deg, Δt=2.359mm
    Cam 1: Δr=4.269deg, Δt=1.025mm
    Cam 2: Δr=4.392deg, Δt=2.274mm
    Cam 3: Δr=4.602deg, Δt=2.514mm
    Final:   S_ray=0.68, S_len=0.80 (JF=0.0215)
      RMSE Ray: 0.1991 -> 0.0168
      RMSE Len: 0.0419 -> 0.0515

=== Bias +5.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=889.45, S_len=1.45 (J0=0.4093)
[nfev~  10] ExpA CamOnly | ray=0.557821 mm | len=0.068319 mm | cost=3.054389e+06
[nfev~  20] ExpA CamOnly | ray=0.465656 mm | len=0.066292 mm | cost=2.090038e+06
[nfev~  30] ExpA CamOnly | ray=0.313922 mm | len=0.064537 mm | cost=9.165615e+05
[nfev~  40] ExpA CamOnly | ray=0.149714 mm | len=0.034970 mm | cost=2.055560e+05
[nfev~  50] ExpA CamOnly | ray=0.065766 mm | len=0.100493 mm | cost=3.996119e+04
[nfev~  60] ExpA CamOnly | ray=0.038410 mm | len=0.195125 mm | cost=1.466959e+04
[nfev~  70] ExpA CamOnly | ray=0.037073 mm | len=0.185232 mm | cost=1.363143e+04
[nfev~  80] ExpA CamOnly | ray=0.031621 mm | len=0.185104 mm | cost=1.019589e+04
[nfev~  90] ExpA CamOnly | ray=0.030995 mm | len=0.183488 mm | cost=9.818803e+03
[nfev~ 100] ExpA CamOnly | ray=0.029693 mm | len=0.183605 mm | cost=9.095319e+03
  Termination: xtol (nfev=20)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=6.329deg, Δt=5.895mm
    Cam 1: Δr=5.310deg, Δt=6.064mm
    Cam 2: Δr=5.367deg, Δt=7.194mm
    Cam 3: Δr=6.216deg, Δt=5.991mm
    Final:   S_ray=2.12, S_len=10.11 (JF=0.2706)
      RMSE Ray: 0.6088 -> 0.0297
      RMSE Len: 0.0696 -> 0.1836

=== Bias +7.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=3836.96, S_len=2.98 (J0=1.6782)
[nfev~  10] ExpA CamOnly | ray=1.211764 mm | len=0.098639 mm | cost=1.751442e+07
[nfev~  20] ExpA CamOnly | ray=1.110847 mm | len=0.096706 mm | cost=1.452779e+07
[nfev~  30] ExpA CamOnly | ray=0.924098 mm | len=0.093668 mm | cost=9.709329e+06
[nfev~  40] ExpA CamOnly | ray=0.606788 mm | len=0.089339 mm | cost=3.785845e+06
[nfev~  50] ExpA CamOnly | ray=0.298336 mm | len=0.140398 mm | cost=8.241137e+05
[nfev~  60] ExpA CamOnly | ray=0.118679 mm | len=0.200019 mm | cost=1.303757e+05
[nfev~  70] ExpA CamOnly | ray=0.047441 mm | len=0.162539 mm | cost=2.143396e+04
[nfev~  80] ExpA CamOnly | ray=0.035980 mm | len=0.127729 mm | cost=1.236214e+04
[nfev~  90] ExpA CamOnly | ray=0.030243 mm | len=0.102329 mm | cost=8.702830e+03
[nfev~ 100] ExpA CamOnly | ray=0.025397 mm | len=0.103067 mm | cost=6.234273e+03
[nfev~ 110] ExpA CamOnly | ray=0.025169 mm | len=0.103142 mm | cost=6.129226e+03
  Termination: xtol (nfev=21)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=5.133deg, Δt=7.063mm
    Cam 1: Δr=4.268deg, Δt=6.916mm
    Cam 2: Δr=4.409deg, Δt=8.041mm
    Cam 3: Δr=5.281deg, Δt=7.349mm
    Final:   S_ray=1.52, S_len=3.19 (JF=0.0857)
      RMSE Ray: 1.2644 -> 0.0252
      RMSE Len: 0.0996 -> 0.1031

=== Bias +10.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=11123.49, S_len=5.11 (J0=4.7709)
[nfev~  10] ExpA CamOnly | ray=2.094534 mm | len=0.129799 mm | cost=5.886295e+07
[nfev~  20] ExpA CamOnly | ray=1.980796 mm | len=0.128470 mm | cost=5.231246e+07
[nfev~  30] ExpA CamOnly | ray=1.764889 mm | len=0.125782 mm | cost=4.092388e+07
[nfev~  40] ExpA CamOnly | ray=1.374062 mm | len=0.120667 mm | cost=2.384055e+07
[nfev~  50] ExpA CamOnly | ray=0.765188 mm | len=0.097086 mm | cost=6.384943e+06
[nfev~  60] ExpA CamOnly | ray=0.247116 mm | len=0.689380 mm | cost=5.744585e+05
[nfev~  70] ExpA CamOnly | ray=0.174127 mm | len=0.681170 mm | cost=2.920684e+05
[nfev~  80] ExpA CamOnly | ray=0.076707 mm | len=0.470391 mm | cost=6.061518e+04
[nfev~  90] ExpA CamOnly | ray=0.054927 mm | len=0.449022 mm | cost=3.372557e+04
[nfev~ 100] ExpA CamOnly | ray=0.037416 mm | len=0.447098 mm | cost=1.883984e+04
[nfev~ 110] ExpA CamOnly | ray=0.036485 mm | len=0.443522 mm | cost=1.811274e+04
  Termination: xtol (nfev=22)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=6.682deg, Δt=13.216mm
    Cam 1: Δr=2.783deg, Δt=16.510mm
    Cam 2: Δr=2.814deg, Δt=16.945mm
    Cam 3: Δr=5.799deg, Δt=13.257mm
    Final:   S_ray=3.05, S_len=59.02 (JF=1.5751)
      RMSE Ray: 2.1529 -> 0.0357
      RMSE Len: 0.1305 -> 0.4435

=== Bias +12.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=26314.30, S_len=7.83 (J0=11.1732)
[nfev~  10] ExpA CamOnly | ray=3.245985 mm | len=0.161596 mm | cost=1.516853e+08
[nfev~  20] ExpA CamOnly | ray=3.121365 mm | len=0.161208 mm | cost=1.398179e+08
[nfev~  30] ExpA CamOnly | ray=2.880275 mm | len=0.160200 mm | cost=1.182639e+08
[nfev~  40] ExpA CamOnly | ray=2.430669 mm | len=0.156499 mm | cost=8.291768e+07
[nfev~  50] ExpA CamOnly | ray=1.687114 mm | len=0.140027 mm | cost=3.780198e+07
[nfev~  60] ExpA CamOnly | ray=0.430378 mm | len=0.608823 mm | cost=1.746953e+06
[nfev~  70] ExpA CamOnly | ray=0.227066 mm | len=0.610793 mm | cost=4.844121e+05
[nfev~  80] ExpA CamOnly | ray=0.117635 mm | len=0.686261 mm | cost=1.411057e+05
[nfev~  90] ExpA CamOnly | ray=0.081709 mm | len=0.684107 mm | cost=7.530153e+04
[nfev~ 100] ExpA CamOnly | ray=0.068101 mm | len=0.682874 mm | cost=5.654546e+04
[nfev~ 110] ExpA CamOnly | ray=0.066781 mm | len=0.682099 mm | cost=5.488026e+04
[nfev~ 120] ExpA CamOnly | ray=0.063876 mm | len=0.681351 mm | cost=5.136590e+04
[nfev~ 130] ExpA CamOnly | ray=0.062947 mm | len=0.681066 mm | cost=5.027322e+04
[nfev~ 140] ExpA CamOnly | ray=0.062292 mm | len=0.680301 mm | cost=4.948973e+04
[nfev~ 150] ExpA CamOnly | ray=0.061376 mm | len=0.680364 mm | cost=4.845247e+04
[nfev~ 160] ExpA CamOnly | ray=0.061271 mm | len=0.680354 mm | cost=4.833451e+04
  Termination: xtol (nfev=26)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=4.654deg, Δt=18.665mm
    Cam 1: Δr=0.787deg, Δt=22.896mm
    Cam 2: Δr=1.171deg, Δt=23.249mm
    Cam 3: Δr=3.591deg, Δt=19.516mm
    Final:   S_ray=9.01, S_len=138.86 (JF=3.7068)
      RMSE Ray: 3.3112 -> 0.0613
      RMSE Len: 0.1616 -> 0.6804

=== Bias +15.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpA CamOnly] optimizing 24 parameters (8 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=53115.80, S_len=11.16 (J0=22.4292)
[nfev~  10] ExpA CamOnly | ray=4.633857 mm | len=0.193668 mm | cost=3.274977e+08
[nfev~  20] ExpA CamOnly | ray=4.494151 mm | len=0.195149 mm | cost=3.070956e+08
[nfev~  30] ExpA CamOnly | ray=4.220322 mm | len=0.197750 mm | cost=2.690937e+08
[nfev~  40] ExpA CamOnly | ray=3.694819 mm | len=0.201175 mm | cost=2.034185e+08
[nfev~  50] ExpA CamOnly | ray=2.782032 mm | len=0.188654 mm | cost=1.116371e+08
[nfev~  60] ExpA CamOnly | ray=0.730862 mm | len=0.613677 mm | cost=5.620385e+06
[nfev~  70] ExpA CamOnly | ray=0.374310 mm | len=0.773269 mm | cost=1.320562e+06
[nfev~  80] ExpA CamOnly | ray=0.212225 mm | len=0.831758 mm | cost=4.341370e+05
[nfev~  90] ExpA CamOnly | ray=0.123623 mm | len=0.764469 mm | cost=1.577991e+05
[nfev~ 100] ExpA CamOnly | ray=0.105990 mm | len=0.526646 mm | cost=1.114271e+05
[nfev~ 110] ExpA CamOnly | ray=0.043137 mm | len=0.307466 mm | cost=1.991471e+04
[nfev~ 120] ExpA CamOnly | ray=0.024863 mm | len=0.305224 mm | cost=8.468554e+03
[nfev~ 130] ExpA CamOnly | ray=0.022032 mm | len=0.296265 mm | cost=7.088301e+03
[nfev~ 140] ExpA CamOnly | ray=0.021310 mm | len=0.298532 mm | cost=6.841452e+03
[nfev~ 150] ExpA CamOnly | ray=0.021401 mm | len=0.296344 mm | cost=6.838156e+03
  Termination: xtol (nfev=27)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.647deg, Δt=17.300mm
    Cam 1: Δr=2.601deg, Δt=18.501mm
    Cam 2: Δr=2.645deg, Δt=19.321mm
    Cam 3: Δr=4.020deg, Δt=18.060mm
    Final:   S_ray=1.06, S_len=26.35 (JF=0.7031)
      RMSE Ray: 4.7044 -> 0.0210
      RMSE Len: 0.1929 -> 0.2964

,bias_mm,ray_rmse_mm,len_rmse_mm,cam_t_err_mean_mm,cam_r_err_mean_deg,N_ray,N_len
0,-15.0,0.003779,0.010941,3.288802,1.020728,2400,300
1,-12.5,0.003100,0.007442,2.823483,1.026195,2400,300
2,-10.0,0.001975,0.005695,2.240727,0.752024,2400,300
3,-7.5,0.001690,0.004156,1.687466,0.547158,2400,300
4,-5.0,0.002006,0.003612,1.106522,0.671138,2400,300
5,-2.5,0.002294,0.004428,0.544683,0.679791,2400,300
6,0.0,0.001241,0.001110,0.205398,0.363705,2400,300
7,2.5,0.016832,0.051525,2.195331,3.747433,2400,300
8,5.0,0.029692,0.183603,6.442344,5.731180,2400,300
9,7.5,0.025168,0.103136,7.576402,4.513467,2400,300
10,10.0,0.035651,0.443546,15.155918,4.983924,2400,300
11,12.5,0.061266,0.680355,21.245977,3.056344,2400,300
12,15.0,0.021047,0.296357,18.521908,2.299429,2400,300

add bias to plane location, calibrate camera and palen

In [3]:
import copy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 复用你实验A里已经定义好的这些对象/函数：
# - cam_truth, cam_init_base
# - cam2win_truth, plane_truth, media_truth
# - dataset
# - apply_plane_bias(...)
# - mean_cam_err(...)
# - RefractiveBAConfig, RefractiveBAOptimizer, CppCameraFactory

BIAS_LIST_MM = np.arange(-15.0, 15.01, 2.5)
SHOW_PROGRESS = True  # True时每10个nfev打印一次

records_B = []

for bias in BIAS_LIST_MM:
    print(f"\n=== [ExpB] Bias {bias:+.2f} mm ===")

    cam_init = {cid: p.copy() for cid, p in cam_init_base.items()}
    plane_biased = apply_plane_bias(plane_truth, bias)

    class _Base:
        pass
    base = _Base()
    base.image_size = (800, 1280)

    cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
        base=base,
        cam_params=cam_init,
        window_media=media_truth,
        cam_to_window=cam2win_truth,
        window_planes=plane_biased,
    )

    cb_counter = {"k": 0}
    def progress_cb(phase, ray_rmse, len_rmse, cost):
        if not SHOW_PROGRESS:
            return
        cb_counter["k"] += 1
        nfev_est = cb_counter["k"] * 10
        print(
            f"[ExpB][bias={bias:+.2f}][nfev~{nfev_est:4d}] {phase} | "
            f"ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | cost={cost:.6e}"
        )

    cfg = RefractiveBAConfig(
        stage=0,
        verbosity=0,
        max_frames=(MAX_FRAMES if MAX_FRAMES > 0 else 0),
    )

    opt = RefractiveBAOptimizer(
        dataset=dataset,
        cam_params=cam_init,
        cams_cpp=cams_cpp,
        cam_to_window=cam2win_truth,
        window_media=media_truth,
        window_planes=plane_biased,
        wand_length=WAND_LEN_MM,
        config=cfg,
        progress_callback=progress_cb,
    )
    opt._compute_physical_sigmas()

    # 实验B：相机+平面一起优化
    opt._optimize_generic(
        mode="expB_joint",
        description="ExpB Joint",
        enable_planes=True,
        enable_cam_t=True,
        enable_cam_r=True,
        limit_rot_rad=np.radians(20.0),
        limit_trans_mm=50.0,
        limit_plane_d_mm=50.0,
        limit_plane_angle_rad=np.radians(10.0),
        ftol=1e-7,
        loss="linear",
    )

    lam = 2.0 * max(1, len(cam_init))
    _, S_ray, S_len, N_ray, N_len = opt.evaluate_residuals(
        opt.window_planes, opt.cam_params, lam, window_media=opt.window_media
    )
    ray_rmse = np.sqrt(S_ray / max(1, N_ray))
    len_rmse = np.sqrt(S_len / max(1, N_len)) if N_len > 0 else np.nan

    cam_t_err_mean, cam_r_err_mean = mean_cam_err(opt.cam_params, cam_truth)

    # 平面“回正”量：沿真值法向的平均位置误差
    plane_d_errs = []
    for wid in sorted(plane_truth.keys()):
        n_gt = np.asarray(plane_truth[wid]["plane_n"], dtype=float)
        pt_gt = np.asarray(plane_truth[wid]["plane_pt"], dtype=float)
        pt_est = np.asarray(opt.window_planes[wid]["plane_pt"], dtype=float)
        plane_d_errs.append(abs(float(np.dot(n_gt, pt_est - pt_gt))))
    plane_d_err_mean = float(np.mean(plane_d_errs)) if plane_d_errs else np.nan

    records_B.append({
        "bias_mm": float(bias),
        "ray_rmse_mm": float(ray_rmse),
        "len_rmse_mm": float(len_rmse),
        "cam_t_err_mean_mm": cam_t_err_mean,
        "cam_r_err_mean_deg": cam_r_err_mean,
        "plane_d_err_mean_mm": plane_d_err_mean,
        "N_ray": int(N_ray),
        "N_len": int(N_len),
    })

dfB = pd.DataFrame(records_B).sort_values("bias_mm").reset_index(drop=True)
display(dfB)

plt.figure(figsize=(7,4))
plt.plot(dfB["bias_mm"], dfB["ray_rmse_mm"], marker="o", label="ExpB joint")
plt.xlabel("Plane bias along normal (mm)")
plt.ylabel("Ray RMSE (mm)")
plt.title("Experiment B: Plane Bias vs Ray RMSE (Camera + Plane optimize)")
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

=== [ExpB] Bias -15.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=1522.64, S_len=10.87 (J0=0.9243)
[ExpB][bias=-15.00][nfev~  10] ExpB Joint | ray=0.796514 mm | len=0.190348 mm | cost=5.806694e+06
[ExpB][bias=-15.00][nfev~  20] ExpB Joint | ray=0.703952 mm | len=0.186725 mm | cost=4.535728e+06
[ExpB][bias=-15.00][nfev~  30] ExpB Joint | ray=0.520304 mm | len=0.179713 mm | cost=2.478249e+06
[ExpB][bias=-15.00][nfev~  40] ExpB Joint | ray=0.164755 mm | len=0.166543 mm | cost=2.492245e+05
[ExpB][bias=-15.00][nfev~  50] ExpB Joint | ray=0.038196 mm | len=0.143617 mm | cost=1.396943e+04
[ExpB][bias=-15.00][nfev~  60] ExpB Joint | ray=0.006807 mm | len=0.045448 mm | cost=4.859674e+02
[ExpB][bias=-15.00][nfev~  70] ExpB Joint | ray=0.003118 mm | len=0.010304 mm | cost=9.217069e+01
[ExpB][bias=-15.00][nfev~  80] ExpB Joint | ray=0.003221 mm | len=0.010252 mm | cost=9.808971e+01
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=2.305deg, Δt=2.155mm
    Cam 1: Δr=0.542deg, Δt=4.121mm
    Cam 2: Δr=0.522deg, Δt=3.690mm
    Cam 3: Δr=1.290deg, Δt=2.310mm
  Window Δ:
    Win 0: Δd=1.2297mm, Δa=-0.2429deg, Δb=0.0865deg
    Win 1: Δd=1.5840mm, Δa=0.8308deg, Δb=0.3689deg
    Final:   S_ray=0.01, S_len=0.03 (JF=0.0009)
      RMSE Ray: 0.7965 -> 0.0022
      RMSE Len: 0.1903 -> 0.0103

=== [ExpB] Bias -12.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=1080.45, S_len=7.59 (J0=0.6526)
[ExpB][bias=-12.50][nfev~  10] ExpB Joint | ray=0.670961 mm | len=0.159063 mm | cost=4.121382e+06
[ExpB][bias=-12.50][nfev~  20] ExpB Joint | ray=0.578972 mm | len=0.155580 mm | cost=3.068929e+06
[ExpB][bias=-12.50][nfev~  30] ExpB Joint | ray=0.396826 mm | len=0.148866 mm | cost=1.442013e+06
[ExpB][bias=-12.50][nfev~  40] ExpB Joint | ray=0.077506 mm | len=0.135999 mm | cost=5.553907e+04
[ExpB][bias=-12.50][nfev~  50] ExpB Joint | ray=0.031160 mm | len=0.114756 mm | cost=9.282501e+03
[ExpB][bias=-12.50][nfev~  60] ExpB Joint | ray=0.003840 mm | len=0.032322 mm | cost=1.663133e+02
[ExpB][bias=-12.50][nfev~  70] ExpB Joint | ray=0.002994 mm | len=0.013333 mm | cost=8.740611e+01
[ExpB][bias=-12.50][nfev~  80] ExpB Joint | ray=0.002569 mm | len=0.010582 mm | cost=6.375260e+01
[ExpB][bias=-12.50][nfev~  90] ExpB Joint | ray=0.004271 mm | len=0.010508 mm | cost=1.702661e+02
[ExpB][bias=-12.50][nfev~ 100] ExpB Joint | ray=0.002420 mm | len=0.010497 mm | cost=5.690101e+01
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.645deg, Δt=1.500mm
    Cam 1: Δr=0.582deg, Δt=3.637mm
    Cam 2: Δr=0.738deg, Δt=3.143mm
    Cam 3: Δr=1.907deg, Δt=1.573mm
  Window Δ:
    Win 0: Δd=2.0221mm, Δa=-0.4854deg, Δb=0.0220deg
    Win 1: Δd=1.3607mm, Δa=0.9391deg, Δb=0.5568deg
    Final:   S_ray=0.01, S_len=0.03 (JF=0.0009)
      RMSE Ray: 0.6710 -> 0.0021
      RMSE Len: 0.1591 -> 0.0105

=== [ExpB] Bias -10.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=716.31, S_len=4.91 (J0=0.4294)
[ExpB][bias=-10.00][nfev~  10] ExpB Joint | ray=0.546316 mm | len=0.127953 mm | cost=2.733022e+06
[ExpB][bias=-10.00][nfev~  20] ExpB Joint | ray=0.455055 mm | len=0.124663 mm | cost=1.896316e+06
[ExpB][bias=-10.00][nfev~  30] ExpB Joint | ray=0.275254 mm | len=0.118301 mm | cost=6.940782e+05
[ExpB][bias=-10.00][nfev~  40] ExpB Joint | ray=0.072386 mm | len=0.107333 mm | cost=4.831719e+04
[ExpB][bias=-10.00][nfev~  50] ExpB Joint | ray=0.012689 mm | len=0.049799 mm | cost=1.548517e+03
[ExpB][bias=-10.00][nfev~  60] ExpB Joint | ray=0.002597 mm | len=0.010542 mm | cost=6.508808e+01
[ExpB][bias=-10.00][nfev~  70] ExpB Joint | ray=0.002212 mm | len=0.005584 mm | cost=4.573949e+01
[ExpB][bias=-10.00][nfev~  80] ExpB Joint | ray=0.002649 mm | len=0.005584 mm | cost=6.520112e+01
[ExpB][bias=-10.00][nfev~  90] ExpB Joint | ray=0.001792 mm | len=0.005523 mm | cost=3.030334e+01
[ExpB][bias=-10.00][nfev~ 100] ExpB Joint | ray=0.001335 mm | len=0.005543 mm | cost=1.723886e+01
[ExpB][bias=-10.00][nfev~ 110] ExpB Joint | ray=0.001369 mm | len=0.005348 mm | cost=1.801565e+01
[ExpB][bias=-10.00][nfev~ 120] ExpB Joint | ray=0.002803 mm | len=0.005547 mm | cost=7.286408e+01
[ExpB][bias=-10.00][nfev~ 130] ExpB Joint | ray=0.001981 mm | len=0.005522 mm | cost=3.682629e+01
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.837deg, Δt=1.267mm
    Cam 1: Δr=0.536deg, Δt=3.208mm
    Cam 2: Δr=0.659deg, Δt=2.732mm
    Cam 3: Δr=1.730deg, Δt=1.321mm
  Window Δ:
    Win 0: Δd=1.0468mm, Δa=-0.2809deg, Δb=0.1469deg
    Win 1: Δd=0.9323mm, Δa=0.6500deg, Δb=0.6666deg
    Final:   S_ray=0.00, S_len=0.01 (JF=0.0002)
      RMSE Ray: 0.5463 -> 0.0013
      RMSE Len: 0.1280 -> 0.0055

=== [ExpB] Bias -7.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=430.21, S_len=2.83 (J0=0.2548)
[ExpB][bias=-7.50][nfev~  10] ExpB Joint | ray=0.423385 mm | len=0.097185 mm | cost=1.641837e+06
[ExpB][bias=-7.50][nfev~  20] ExpB Joint | ray=0.333267 mm | len=0.094135 mm | cost=1.017380e+06
[ExpB][bias=-7.50][nfev~  30] ExpB Joint | ray=0.159703 mm | len=0.088220 mm | cost=2.337999e+05
[ExpB][bias=-7.50][nfev~  40] ExpB Joint | ray=0.060517 mm | len=0.081965 mm | cost=3.373946e+04
[ExpB][bias=-7.50][nfev~  50] ExpB Joint | ray=0.012304 mm | len=0.032119 mm | cost=1.417223e+03
[ExpB][bias=-7.50][nfev~  60] ExpB Joint | ray=0.003746 mm | len=0.005338 mm | cost=1.293259e+02
[ExpB][bias=-7.50][nfev~  70] ExpB Joint | ray=0.001536 mm | len=0.005112 mm | cost=2.238878e+01
[ExpB][bias=-7.50][nfev~  80] ExpB Joint | ray=0.002038 mm | len=0.005094 mm | cost=3.881193e+01
[ExpB][bias=-7.50][nfev~  90] ExpB Joint | ray=0.001810 mm | len=0.005080 mm | cost=3.076282e+01
[ExpB][bias=-7.50][nfev~ 100] ExpB Joint | ray=0.001276 mm | len=0.005090 mm | cost=1.569602e+01
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=2.042deg, Δt=0.853mm
    Cam 1: Δr=0.591deg, Δt=2.542mm
    Cam 2: Δr=0.639deg, Δt=2.045mm
    Cam 3: Δr=1.538deg, Δt=0.827mm
  Window Δ:
    Win 0: Δd=0.7672mm, Δa=-0.5135deg, Δb=0.1456deg
    Win 1: Δd=1.3737mm, Δa=0.6064deg, Δb=0.7626deg
    Final:   S_ray=0.00, S_len=0.01 (JF=0.0002)
      RMSE Ray: 0.4234 -> 0.0013
      RMSE Len: 0.0972 -> 0.0051

=== [ExpB] Bias -5.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=222.16, S_len=1.36 (J0=0.1287)
[ExpB][bias=-5.00][nfev~  10] ExpB Joint | ray=0.304249 mm | len=0.067231 mm | cost=8.480490e+05
[ExpB][bias=-5.00][nfev~  20] ExpB Joint | ray=0.216619 mm | len=0.064575 mm | cost=4.299461e+05
[ExpB][bias=-5.00][nfev~  30] ExpB Joint | ray=0.080946 mm | len=0.059209 mm | cost=6.012341e+04
[ExpB][bias=-5.00][nfev~  40] ExpB Joint | ray=0.046578 mm | len=0.056859 mm | cost=1.996960e+04
[ExpB][bias=-5.00][nfev~  50] ExpB Joint | ray=0.005203 mm | len=0.022353 mm | cost=2.629172e+02
[ExpB][bias=-5.00][nfev~  60] ExpB Joint | ray=0.002284 mm | len=0.003228 mm | cost=4.811525e+01
[ExpB][bias=-5.00][nfev~  70] ExpB Joint | ray=0.001732 mm | len=0.003797 mm | cost=2.791124e+01
[ExpB][bias=-5.00][nfev~  80] ExpB Joint | ray=0.001630 mm | len=0.001690 mm | cost=2.443028e+01
[ExpB][bias=-5.00][nfev~  90] ExpB Joint | ray=0.001119 mm | len=0.001782 mm | cost=1.156405e+01
[ExpB][bias=-5.00][nfev~ 100] ExpB Joint | ray=0.001585 mm | len=0.002595 mm | cost=2.320433e+01
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.832deg, Δt=0.396mm
    Cam 1: Δr=0.599deg, Δt=2.071mm
    Cam 2: Δr=0.751deg, Δt=1.617mm
    Cam 3: Δr=1.750deg, Δt=0.368mm
  Window Δ:
    Win 0: Δd=0.7252mm, Δa=-0.0916deg, Δb=0.4005deg
    Win 1: Δd=0.9037mm, Δa=0.5914deg, Δb=0.7159deg
    Final:   S_ray=0.00, S_len=0.00 (JF=0.0001)
      RMSE Ray: 0.3042 -> 0.0011
      RMSE Len: 0.0672 -> 0.0026

=== [ExpB] Bias -2.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=92.16, S_len=0.48 (J0=0.0512)
[ExpB][bias=-2.50][nfev~  10] ExpB Joint | ray=0.195960 mm | len=0.039967 mm | cost=3.518806e+05
[ExpB][bias=-2.50][nfev~  20] ExpB Joint | ray=0.116407 mm | len=0.038332 mm | cost=1.241973e+05
[ExpB][bias=-2.50][nfev~  30] ExpB Joint | ray=0.064516 mm | len=0.036154 mm | cost=3.817510e+04
[ExpB][bias=-2.50][nfev~  40] ExpB Joint | ray=0.032102 mm | len=0.034991 mm | cost=9.478780e+03
[ExpB][bias=-2.50][nfev~  50] ExpB Joint | ray=0.003832 mm | len=0.008170 mm | cost=1.365242e+02
[ExpB][bias=-2.50][nfev~  60] ExpB Joint | ray=0.001797 mm | len=0.001875 mm | cost=2.970479e+01
[ExpB][bias=-2.50][nfev~  70] ExpB Joint | ray=0.001711 mm | len=0.002823 mm | cost=2.705904e+01
[ExpB][bias=-2.50][nfev~  80] ExpB Joint | ray=0.001213 mm | len=0.002765 mm | cost=1.371237e+01
[ExpB][bias=-2.50][nfev~  90] ExpB Joint | ray=0.001182 mm | len=0.002806 mm | cost=1.303170e+01
  Termination: xtol (nfev=18)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.886deg, Δt=0.420mm
    Cam 1: Δr=0.617deg, Δt=1.553mm
    Cam 2: Δr=0.735deg, Δt=1.084mm
    Cam 3: Δr=1.685deg, Δt=0.483mm
  Window Δ:
    Win 0: Δd=0.9371mm, Δa=-0.1856deg, Δb=0.2515deg
    Win 1: Δd=0.5321mm, Δa=0.5017deg, Δb=0.7929deg
    Final:   S_ray=0.00, S_len=0.00 (JF=0.0001)
      RMSE Ray: 0.1960 -> 0.0012
      RMSE Len: 0.0400 -> 0.0028

=== [ExpB] Bias +0.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=40.21, S_len=0.20 (J0=0.0222)
[ExpB][bias=+0.00][nfev~  10] ExpB Joint | ray=0.129434 mm | len=0.026017 mm | cost=1.535546e+05
[ExpB][bias=+0.00][nfev~  20] ExpB Joint | ray=0.070767 mm | len=0.025090 mm | cost=4.591393e+04
[ExpB][bias=+0.00][nfev~  30] ExpB Joint | ray=0.060427 mm | len=0.022353 mm | cost=3.347904e+04
[ExpB][bias=+0.00][nfev~  40] ExpB Joint | ray=0.043302 mm | len=0.019966 mm | cost=1.719575e+04
[ExpB][bias=+0.00][nfev~  50] ExpB Joint | ray=0.027118 mm | len=0.017462 mm | cost=6.748745e+03
[ExpB][bias=+0.00][nfev~  60] ExpB Joint | ray=0.011283 mm | len=0.012757 mm | cost=1.171613e+03
[ExpB][bias=+0.00][nfev~  70] ExpB Joint | ray=0.003083 mm | len=0.001794 mm | cost=8.718967e+01
[ExpB][bias=+0.00][nfev~  80] ExpB Joint | ray=0.002274 mm | len=0.005413 mm | cost=4.828427e+01
[ExpB][bias=+0.00][nfev~  90] ExpB Joint | ray=0.001983 mm | len=0.005034 mm | cost=3.679046e+01
[ExpB][bias=+0.00][nfev~ 100] ExpB Joint | ray=0.001520 mm | len=0.004038 mm | cost=2.167345e+01
[ExpB][bias=+0.00][nfev~ 110] ExpB Joint | ray=0.001347 mm | len=0.005783 mm | cost=1.764343e+01
[ExpB][bias=+0.00][nfev~ 120] ExpB Joint | ray=0.001280 mm | len=0.005426 mm | cost=1.589231e+01
[ExpB][bias=+0.00][nfev~ 130] ExpB Joint | ray=0.001275 mm | len=0.004935 mm | cost=1.563481e+01
[ExpB][bias=+0.00][nfev~ 140] ExpB Joint | ray=0.001270 mm | len=0.004915 mm | cost=1.550171e+01
[ExpB][bias=+0.00][nfev~ 150] ExpB Joint | ray=0.001266 mm | len=0.004915 mm | cost=1.540181e+01
  Termination: xtol (nfev=24)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.818deg, Δt=0.737mm
    Cam 1: Δr=0.689deg, Δt=0.932mm
    Cam 2: Δr=0.838deg, Δt=0.456mm
    Cam 3: Δr=1.785deg, Δt=0.822mm
  Window Δ:
    Win 0: Δd=0.1947mm, Δa=-0.0892deg, Δb=0.2248deg
    Win 1: Δd=0.6718mm, Δa=0.5692deg, Δb=0.6667deg
    Final:   S_ray=0.00, S_len=0.01 (JF=0.0002)
      RMSE Ray: 0.1294 -> 0.0013
      RMSE Len: 0.0260 -> 0.0049

=== [ExpB] Bias +2.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=95.18, S_len=0.53 (J0=0.0537)
[ExpB][bias=+2.50][nfev~  10] ExpB Joint | ray=0.199143 mm | len=0.041936 mm | cost=3.635887e+05
[ExpB][bias=+2.50][nfev~  20] ExpB Joint | ray=0.133698 mm | len=0.039372 mm | cost=1.639048e+05
[ExpB][bias=+2.50][nfev~  30] ExpB Joint | ray=0.072136 mm | len=0.032810 mm | cost=4.773283e+04
[ExpB][bias=+2.50][nfev~  40] ExpB Joint | ray=0.041387 mm | len=0.021844 mm | cost=1.571605e+04
[ExpB][bias=+2.50][nfev~  50] ExpB Joint | ray=0.004199 mm | len=0.004997 mm | cost=1.624001e+02
[ExpB][bias=+2.50][nfev~  60] ExpB Joint | ray=0.001802 mm | len=0.004298 mm | cost=3.031580e+01
[ExpB][bias=+2.50][nfev~  70] ExpB Joint | ray=0.001102 mm | len=0.004309 mm | cost=1.168292e+01
[ExpB][bias=+2.50][nfev~  80] ExpB Joint | ray=0.000964 mm | len=0.004311 mm | cost=9.082592e+00
[ExpB][bias=+2.50][nfev~  90] ExpB Joint | ray=0.000934 mm | len=0.004313 mm | cost=8.556093e+00
  Termination: xtol (nfev=17)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.965deg, Δt=1.112mm
    Cam 1: Δr=0.565deg, Δt=0.602mm
    Cam 2: Δr=0.693deg, Δt=0.093mm
    Cam 3: Δr=1.613deg, Δt=1.156mm
  Window Δ:
    Win 0: Δd=-1.1627mm, Δa=0.1288deg, Δb=0.0544deg
    Win 1: Δd=-1.4773mm, Δa=0.6242deg, Δb=1.0616deg
    Final:   S_ray=0.00, S_len=0.01 (JF=0.0001)
      RMSE Ray: 0.1991 -> 0.0009
      RMSE Len: 0.0419 -> 0.0043

=== [ExpB] Bias +5.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=889.45, S_len=1.45 (J0=0.4093)
[ExpB][bias=+5.00][nfev~  10] ExpB Joint | ray=0.608773 mm | len=0.069590 mm | cost=3.663842e+06
[ExpB][bias=+5.00][nfev~  20] ExpB Joint | ray=0.543224 mm | len=0.067538 mm | cost=2.875630e+06
[ExpB][bias=+5.00][nfev~  30] ExpB Joint | ray=0.420964 mm | len=0.063477 mm | cost=1.681168e+06
[ExpB][bias=+5.00][nfev~  40] ExpB Joint | ray=0.221834 mm | len=0.055155 mm | cost=4.526065e+05
[ExpB][bias=+5.00][nfev~  50] ExpB Joint | ray=0.098424 mm | len=0.033785 mm | cost=8.885788e+04
[ExpB][bias=+5.00][nfev~  60] ExpB Joint | ray=0.038473 mm | len=0.070037 mm | cost=1.371898e+04
[ExpB][bias=+5.00][nfev~  70] ExpB Joint | ray=0.022106 mm | len=0.050768 mm | cost=4.558190e+03
[ExpB][bias=+5.00][nfev~  80] ExpB Joint | ray=0.012448 mm | len=0.008597 mm | cost=1.422986e+03
[ExpB][bias=+5.00][nfev~  90] ExpB Joint | ray=0.004064 mm | len=0.013181 mm | cost=1.566648e+02
[ExpB][bias=+5.00][nfev~ 100] ExpB Joint | ray=0.002456 mm | len=0.004678 mm | cost=5.598556e+01
[ExpB][bias=+5.00][nfev~ 110] ExpB Joint | ray=0.002183 mm | len=0.002286 mm | cost=4.384401e+01
[ExpB][bias=+5.00][nfev~ 120] ExpB Joint | ray=0.001339 mm | len=0.002287 mm | cost=1.660326e+01
[ExpB][bias=+5.00][nfev~ 130] ExpB Joint | ray=0.001394 mm | len=0.002290 mm | cost=1.798562e+01
[ExpB][bias=+5.00][nfev~ 140] ExpB Joint | ray=0.001053 mm | len=0.002290 mm | cost=1.031752e+01
[ExpB][bias=+5.00][nfev~ 150] ExpB Joint | ray=0.000991 mm | len=0.002292 mm | cost=9.153698e+00
[ExpB][bias=+5.00][nfev~ 160] ExpB Joint | ray=0.000987 mm | len=0.002292 mm | cost=9.082954e+00
[ExpB][bias=+5.00][nfev~ 170] ExpB Joint | ray=0.000987 mm | len=0.002292 mm | cost=9.086351e+00
[ExpB][bias=+5.00][nfev~ 180] ExpB Joint | ray=0.000977 mm | len=0.002311 mm | cost=8.916629e+00
[ExpB][bias=+5.00][nfev~ 190] ExpB Joint | ray=0.001025 mm | len=0.002292 mm | cost=9.799370e+00
[ExpB][bias=+5.00][nfev~ 200] ExpB Joint | ray=0.004260 mm | len=0.002285 mm | cost=1.665761e+02
  Termination: xtol (nfev=23)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=2.151deg, Δt=1.625mm
    Cam 1: Δr=0.623deg, Δt=0.220mm
    Cam 2: Δr=0.686deg, Δt=0.646mm
    Cam 3: Δr=1.439deg, Δt=1.677mm
  Window Δ:
    Win 0: Δd=-2.9680mm, Δa=0.0301deg, Δb=-0.0158deg
    Win 1: Δd=-3.2699mm, Δa=0.2881deg, Δb=1.1459deg
    Final:   S_ray=0.00, S_len=0.00 (JF=0.0000)
      RMSE Ray: 0.6088 -> 0.0010
      RMSE Len: 0.0696 -> 0.0023

=== [ExpB] Bias +7.50 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=3836.96, S_len=2.98 (J0=1.6782)
[ExpB][bias=+7.50][nfev~  10] ExpB Joint | ray=1.264411 mm | len=0.099646 mm | cost=1.918118e+07
[ExpB][bias=+7.50][nfev~  20] ExpB Joint | ray=1.193648 mm | len=0.098045 mm | cost=1.690620e+07
[ExpB][bias=+7.50][nfev~  30] ExpB Joint | ray=1.057350 mm | len=0.094724 mm | cost=1.294465e+07
[ExpB][bias=+7.50][nfev~  40] ExpB Joint | ray=0.806511 mm | len=0.087623 mm | cost=7.098603e+06
[ExpB][bias=+7.50][nfev~  50] ExpB Joint | ray=0.401626 mm | len=0.057100 mm | cost=1.535171e+06
[ExpB][bias=+7.50][nfev~  60] ExpB Joint | ray=0.180006 mm | len=0.127632 mm | cost=2.978358e+05
[ExpB][bias=+7.50][nfev~  70] ExpB Joint | ray=0.078640 mm | len=0.190623 mm | cost=5.780830e+04
[ExpB][bias=+7.50][nfev~  80] ExpB Joint | ray=0.031169 mm | len=0.105230 mm | cost=9.242459e+03
[ExpB][bias=+7.50][nfev~  90] ExpB Joint | ray=0.029742 mm | len=0.065837 mm | cost=8.243173e+03
[ExpB][bias=+7.50][nfev~ 100] ExpB Joint | ray=0.018327 mm | len=0.046391 mm | cost=3.145052e+03
[ExpB][bias=+7.50][nfev~ 110] ExpB Joint | ray=0.016546 mm | len=0.042772 mm | cost=2.565839e+03
[ExpB][bias=+7.50][nfev~ 120] ExpB Joint | ray=0.013068 mm | len=0.041606 mm | cost=1.618226e+03
[ExpB][bias=+7.50][nfev~ 130] ExpB Joint | ray=0.012028 mm | len=0.039677 mm | cost=1.374129e+03
[ExpB][bias=+7.50][nfev~ 140] ExpB Joint | ray=0.011322 mm | len=0.038559 mm | cost=1.220175e+03
[ExpB][bias=+7.50][nfev~ 150] ExpB Joint | ray=0.010831 mm | len=0.038560 mm | cost=1.120586e+03
[ExpB][bias=+7.50][nfev~ 160] ExpB Joint | ray=0.010807 mm | len=0.038555 mm | cost=1.115709e+03
  Termination: xtol (nfev=23)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=1.596deg, Δt=2.655mm
    Cam 1: Δr=1.967deg, Δt=1.199mm
    Cam 2: Δr=2.102deg, Δt=2.294mm
    Cam 3: Δr=2.705deg, Δt=2.922mm
  Window Δ:
    Win 0: Δd=-4.4670mm, Δa=-0.9173deg, Δb=0.6075deg
    Win 1: Δd=-4.2029mm, Δa=-1.8317deg, Δb=1.8344deg
    Final:   S_ray=0.28, S_len=0.45 (JF=0.0120)
      RMSE Ray: 1.2644 -> 0.0108
      RMSE Len: 0.0996 -> 0.0386

=== [ExpB] Bias +10.00 mm ===

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
  [ExpB Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams=4)
    Initial: S_ray=11123.49, S_len=5.11 (J0=4.7709)
[ExpB][bias=+10.00][nfev~  10] ExpB Joint | ray=2.152856 mm | len=0.130453 mm | cost=6.236973e+07
[ExpB][bias=+10.00][nfev~  20] ExpB Joint | ray=2.073708 mm | len=0.129244 mm | cost=5.755393e+07
[ExpB][bias=+10.00][nfev~  30] ExpB Joint | ray=1.920430 mm | len=0.126630 mm | cost=4.879181e+07
[ExpB][bias=+10.00][nfev~  40] ExpB Joint | ray=1.633145 mm | len=0.120755 mm | cost=3.437611e+07
[ExpB][bias=+10.00][nfev~  50] ExpB Joint | ray=1.123753 mm | len=0.106157 mm | cost=1.519722e+07
[ExpB][bias=+10.00][nfev~  60] ExpB Joint | ray=0.525299 mm | len=0.142003 mm | cost=2.738020e+06
[ExpB][bias=+10.00][nfev~  70] ExpB Joint | ray=0.259607 mm | len=0.364997 mm | cost=6.239669e+05

,bias_mm,ray_rmse_mm,len_rmse_mm,cam_t_err_mean_mm,cam_r_err_mean_deg,plane_d_err_mean_mm,N_ray,N_len
0,-15.0,0.002181,0.010300,2.929833,1.086692,13.593156,2400,300
1,-12.5,0.002087,0.010521,2.316487,1.174601,10.808562,2400,300
2,-10.0,0.001335,0.005543,1.983529,1.153499,9.010493,2400,300
3,-7.5,0.001276,0.005090,1.412827,1.042935,6.429556,2400,300
4,-5.0,0.001079,0.002598,0.921168,1.061351,4.185523,2400,300
5,-2.5,0.001182,0.002806,0.371782,1.048978,1.765437,2400,300
6,0.0,0.001266,0.004915,0.251335,0.955202,0.433223,2400,300
7,2.5,0.000934,0.004314,0.579483,1.154927,1.180010,2400,300
8,5.0,0.000986,0.002292,1.231446,1.095595,1.881075,2400,300
9,7.5,0.010807,0.038555,2.528358,1.165975,3.165011,2400,300
10,10.0,0.009994,0.037759,3.142358,2.323957,3.342022,2400,300
11,12.5,0.012054,0.027901,4.383734,2.576439,2.788191,2400,300
12,15.0,0.012066,0.028067,6.256753,1.891977,7.993535,2400,300

In [3]:
import os, re, csv, glob, copy
import numpy as np
import cv2
import pandas as pd

from modules.camera_calibration.wand_calibration.refraction_calibration_BA import (
    RefractiveBAOptimizer, RefractiveBAConfig
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import (
    CppCameraFactory
)

# -----------------------------
# Paths
# -----------------------------
init_cam_dir = r"H:\20260210\T0\Synthetic_test\camFile"   # 相机+平面初值都用这个
obs_csv      = r"H:\20260210\T0\synthetic_wand_points.csv"

# 可选：用于对比真值参数误差（不影响优化）
truth_cam_dir = r"H:\20260210\T0\Round1\camFile"

MAX_FRAMES = 0   # 先快跑；要全量改成 0
WAND_LEN_MM = 10.0

def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and not s.startswith("#"):
            return s, j
        j += 1
    return "", j

def parse_cam_file(path):
    with open(path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()

    d = {}
    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix") or s.startswith("# Camera Matrix K"):
            row, _ = _next_data(lines, i)
            d["f"] = float(row.split()[0])

        elif s.startswith("# Distortion"):
            row, _ = _next_data(lines, i)
            vals = [float(x) for x in row.split(",")]
            d["k1"] = vals[0] if len(vals) > 0 else 0.0
            d["k2"] = vals[1] if len(vals) > 1 else 0.0

        elif s.startswith("# Rotation Matrix R") or s.startswith("# Rotation Matrix:"):
            r1, _ = _next_data(lines, i)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array([
                [float(x) for x in r1.split()],
                [float(x) for x in r2.split()],
                [float(x) for x in r3.split()],
            ], dtype=float)

        elif s.startswith("# Translation Vector T") or s.startswith("# Translation Vector:"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "WINDOW_ID=" in s:
            d["wid"] = int(s.split("WINDOW_ID=")[1])

        elif "plane.pt" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "plane.norm_vector" in s:
            row, _ = _next_data(lines, i)
            n = np.array([float(x) for x in row.split()], dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = float(row.split(",")[0])

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = [float(x) for x in row.split(",")]  # obj,win,air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()
    d["cx"], d["cy"] = 640.0, 400.0
    return d

def load_cam_set(cam_dir, with_plane=True):
    cam_params, cam_to_window, window_planes, window_media = {}, {}, {}, {}

    for path in sorted(glob.glob(os.path.join(cam_dir, "cam*.txt"))):
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array([
            d["rvec"][0], d["rvec"][1], d["rvec"][2],
            d["tvec"][0], d["tvec"][1], d["tvec"][2],
            d["f"], d["cx"], d["cy"], d.get("k1", 0.0), d.get("k2", 0.0)
        ], dtype=np.float64)
        cam_to_window[cid] = d["wid"]

        if with_plane and d["wid"] not in window_planes:
            # file是farthest；优化内部用closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            wid = d["wid"]
            window_planes[wid] = {
                "plane_pt": p_close,
                "plane_n": d["plane_n"],
                "initialized": True
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"]
            }

    return cam_params, cam_to_window, window_planes, window_media

def load_obs(csv_path, max_frames=0):
    obsA, obsB, frames = {}, {}, set()
    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or pidx == 0:
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or pidx == 1:
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {
        "obsA": obsA,
        "obsB": obsB,
        "frames": frames,
        "cam_ids": None,
        "est_radius_small_mm": 1.5,
        "est_radius_large_mm": 2.0,
    }

def rot_err_deg(r_est, r_gt):
    R1, _ = cv2.Rodrigues(r_est)
    R2, _ = cv2.Rodrigues(r_gt)
    R = R2 @ R1.T
    c = np.clip((np.trace(R) - 1.0) / 2.0, -1.0, 1.0)
    return float(np.degrees(np.arccos(c)))

# -----------------------------
# Build init from Synthetic_test
# -----------------------------
cam_init, cam2win_init, plane_init, media_init = load_cam_set(init_cam_dir, with_plane=True)
dataset = load_obs(obs_csv, max_frames=MAX_FRAMES)
dataset["cam_ids"] = sorted(cam_init.keys())

class _Base: pass
base = _Base()
base.image_size = (800, 1280)

cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_init,
    window_media=media_init,
    cam_to_window=cam2win_init,
    window_planes=plane_init
)

# progress: 每10 nfev 打一次（BA内部每10次residual callback）
_cb = {"k": 0}
def progress_cb(phase, ray_rmse, len_rmse, cost):
    _cb["k"] += 1
    nfev_est = _cb["k"] * 10
    print(f"[nfev~{nfev_est:4d}] {phase} | ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | cost={cost:.6e}")

cfg = RefractiveBAConfig(stage=0, verbosity=0, max_frames=(MAX_FRAMES if MAX_FRAMES > 0 else 0))
opt = RefractiveBAOptimizer(
    dataset=dataset,
    cam_params={k: v.copy() for k, v in cam_init.items()},
    cams_cpp=cams_cpp,
    cam_to_window=cam2win_init,
    window_media=copy.deepcopy(media_init),
    window_planes=copy.deepcopy(plane_init),
    wand_length=WAND_LEN_MM,
    config=cfg,
    progress_callback=progress_cb
)
opt._compute_physical_sigmas()

# --- 先评估初值 ---
lam = 2.0 * max(1, len(cam_init))
_, S_ray0, S_len0, N_ray0, N_len0 = opt.evaluate_residuals(opt.window_planes, opt.cam_params, lam, window_media=opt.window_media)
print("\nBefore optimize:")
print("ray_rmse_mm =", np.sqrt(S_ray0 / max(1, N_ray0)))
print("len_rmse_mm =", np.sqrt(S_len0 / max(1, N_len0)) if N_len0 > 0 else np.nan)

# --- ExpB: camera + plane optimize ---
opt._optimize_generic(
    mode="final",
    description="ExpB Joint From SyntheticInit",
    enable_planes=True,
    enable_cam_t=True,
    enable_cam_r=True,
    limit_rot_rad=np.radians(20.0),
    limit_trans_mm=50.0,
    limit_plane_d_mm=50.0,
    limit_plane_angle_rad=np.radians(10.0),
    ftol=1e-7,
    loss="linear",
)

# --- 优化后评估 ---
_, S_ray1, S_len1, N_ray1, N_len1 = opt.evaluate_residuals(opt.window_planes, opt.cam_params, lam, window_media=opt.window_media)
print("\nAfter optimize:")
print("ray_rmse_mm =", np.sqrt(S_ray1 / max(1, N_ray1)))
print("len_rmse_mm =", np.sqrt(S_len1 / max(1, N_len1)) if N_len1 > 0 else np.nan)
print("N_ray =", N_ray1, "N_len =", N_len1)

# --- 可选：对比Round1真值参数误差 ---
cam_truth, _, plane_truth, _ = load_cam_set(truth_cam_dir, with_plane=True)

t_errs, r_errs = [], []
for cid in sorted(cam_truth.keys()):
    p = opt.cam_params[cid]
    gt = cam_truth[cid]
    t_errs.append(np.linalg.norm(p[3:6] - gt[3:6]))
    r_errs.append(rot_err_deg(p[0:3], gt[0:3]))
print("\nVs Round1 truth (optional reference):")
print("cam_t_err_mean_mm =", float(np.mean(t_errs)))
print("cam_r_err_mean_deg =", float(np.mean(r_errs)))

plane_d_errs = []
for wid in sorted(plane_truth.keys()):
    n = np.asarray(plane_truth[wid]["plane_n"], float)
    pt_gt = np.asarray(plane_truth[wid]["plane_pt"], float)
    pt_est = np.asarray(opt.window_planes[wid]["plane_pt"], float)
    plane_d_errs.append(abs(float(np.dot(n, pt_est - pt_gt))))
print("plane_d_err_mean_mm =", float(np.mean(plane_d_errs)))

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.

Before optimize:
ray_rmse_mm = 0.08848784389708853
len_rmse_mm = 0.256456298021347
  [ExpB Joint From SyntheticInit] optimizing 30 parameters (10 blocks)...
    [Constraint] S_ray/S_len (0.95) < 10. Forcing lambda=1.0 (was 8.0)
    Global Fixed Weighting: lambda=1.0 (N_cams=4)
    Initial: S_ray=156.60, S_len=164.42 (J0=0.0736)
[nfev~  10] ExpB Joint From SyntheticInit | ray=0.088488 mm | len=0.256456 mm | cost=6.995278e+05
[nfev~  20] ExpB Joint From SyntheticInit | ray=0.088488 mm | len=0.256456 mm | cost=6.995278e+05
[nfev~  30] ExpB Joint From SyntheticInit | ray=0.088488 mm | len=0.256456 mm | cost=6.995278e+05
[nfev~  40] ExpB Joint From SyntheticInit | ray=0.085074 mm | len=0.256956 mm | cost=6.244925e+05
[nfev~  50] ExpB Joint From SyntheticInit | ray=0.085074 mm | len=0.256956 mm | cost=6.244945e+05

KeyboardInterrupt:

Debug on the final two rounds in BA, using the same input as Exp B.

In [8]:
import os, re, csv, glob, copy
import numpy as np
import cv2

from modules.camera_calibration.wand_calibration.refraction_calibration_BA import (
    RefractiveBAOptimizer, RefractiveBAConfig
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import (
    CppCameraFactory
)

# =========================
# Paths (same as ExpB)
# =========================
init_cam_dir = r"H:\20260210\T0\Synthetic_test\camFile"
obs_csv      = r"H:\20260210\T0\synthetic_wand_points.csv"

MAX_FRAMES = 0  # 0 = all frames, set to 300 if you want quick run
WAND_LEN_MM = 10.0

# -------------------------
# Helpers (same loading logic as ExpB)
# -------------------------
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and not s.startswith("#"):
            return s, j
        j += 1
    return "", j

def parse_cam_file(path):
    with open(path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()

    d = {}
    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix") or s.startswith("# Camera Matrix K"):
            row, _ = _next_data(lines, i)
            d["f"] = float(row.split()[0])

        elif s.startswith("# Distortion"):
            row, _ = _next_data(lines, i)
            vals = [float(x) for x in row.split(",")]
            d["k1"] = vals[0] if len(vals) > 0 else 0.0
            d["k2"] = vals[1] if len(vals) > 1 else 0.0

        elif s.startswith("# Rotation Matrix R") or s.startswith("# Rotation Matrix:"):
            r1, _ = _next_data(lines, i)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array([
                [float(x) for x in r1.split()],
                [float(x) for x in r2.split()],
                [float(x) for x in r3.split()],
            ], dtype=float)

        elif s.startswith("# Translation Vector T") or s.startswith("# Translation Vector:"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "WINDOW_ID=" in s:
            d["wid"] = int(s.split("WINDOW_ID=")[1])

        elif "plane.pt" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array([float(x) for x in row.split()], dtype=float)

        elif "plane.norm_vector" in s:
            row, _ = _next_data(lines, i)
            n = np.array([float(x) for x in row.split()], dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = float(row.split(",")[0])

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = [float(x) for x in row.split(",")]  # obj,win,air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()
    d["cx"], d["cy"] = 640.0, 400.0
    return d

def load_cam_set(cam_dir, with_plane=True):
    cam_params, cam_to_window = {}, {}
    window_planes, window_media = {}, {}

    for path in sorted(glob.glob(os.path.join(cam_dir, "cam*.txt"))):
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array([
            d["rvec"][0], d["rvec"][1], d["rvec"][2],
            d["tvec"][0], d["tvec"][1], d["tvec"][2],
            d["f"], d["cx"], d["cy"], d.get("k1", 0.0), d.get("k2", 0.0)
        ], dtype=np.float64)
        cam_to_window[cid] = d["wid"]

        if with_plane and d["wid"] not in window_planes:
            # file stores farthest interface; optimizer uses closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            wid = d["wid"]
            window_planes[wid] = {
                "plane_pt": p_close,
                "plane_n": d["plane_n"],
                "initialized": True
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"]
            }

    return cam_params, cam_to_window, window_planes, window_media

def load_obs_dataset(csv_path, max_frames=0):
    obsA, obsB, frames = {}, {}, set()
    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {
        "obsA": obsA,
        "obsB": obsB,
        "frames": frames,
        "cam_ids": None,
        "est_radius_small_mm": 1.5,
        "est_radius_large_mm": 2.0,
    }

def eval_rmse(opt, tag):
    lam = 2.0 * max(1, len(opt.cam_params))
    _, S_ray, S_len, N_ray, N_len = opt.evaluate_residuals(
        opt.window_planes, opt.cam_params, lam, window_media=opt.window_media
    )
    ray_rmse = np.sqrt(S_ray / max(1, N_ray))
    len_rmse = np.sqrt(S_len / max(1, N_len)) if N_len > 0 else np.nan
    print(f"[{tag}] ray_rmse_mm={ray_rmse:.9f}, len_rmse_mm={len_rmse:.9f}, N_ray={N_ray}, N_len={N_len}")
    return ray_rmse, len_rmse, N_ray, N_len

# =========================
# Build EXACT ExpB state
# =========================
cam_init, cam_to_window, window_planes_init, window_media_init = load_cam_set(init_cam_dir, with_plane=True)
dataset = load_obs_dataset(obs_csv, max_frames=MAX_FRAMES)
dataset["cam_ids"] = sorted(cam_init.keys())

class _Base: pass
base = _Base()
base.image_size = (800, 1280)

cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_init,
    window_media=window_media_init,
    cam_to_window=cam_to_window,
    window_planes=window_planes_init
)

# optional progress print (nfev~10,20,...)
_cb = {"k": 0}
def progress_cb(phase, ray_rmse, len_rmse, cost):
    _cb["k"] += 1
    nfev_est = _cb["k"] * 10
    print(f"[nfev~{nfev_est:4d}] {phase} | ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | cost={cost:.6e}")

cfg = RefractiveBAConfig(
    stage=0,      # IMPORTANT: we manually run rounds; no optimize() loops
    verbosity=0,
    max_frames=(MAX_FRAMES if MAX_FRAMES > 0 else 0),
)

opt = RefractiveBAOptimizer(
    dataset=dataset,
    cam_params={k: v.copy() for k, v in cam_init.items()},
    cams_cpp=cams_cpp,
    cam_to_window=cam_to_window,
    window_media=copy.deepcopy(window_media_init),
    window_planes=copy.deepcopy(window_planes_init),
    wand_length=WAND_LEN_MM,
    config=cfg,
    progress_callback=progress_cb
)
opt._compute_physical_sigmas()

# sanity snapshot hashes (confirm same state style as ExpB)
print("cam_ids:", sorted(opt.cam_params.keys()))
print("frames:", len(opt.fids_optim), "first10:", opt.fids_optim[:10])

import inspect
import modules.camera_calibration.wand_calibration.refraction_calibration_BA as ba_mod

print("module file:", ba_mod.__file__)
print("default losses:",
      ba_mod.RefractiveBAConfig().loss_plane,
      ba_mod.RefractiveBAConfig().loss_cam,
      ba_mod.RefractiveBAConfig().loss_joint,
      ba_mod.RefractiveBAConfig().loss_round4)

# 在你构造opt之后再看
print("opt losses:",
      opt.config.loss_plane, opt.config.loss_cam, opt.config.loss_joint, opt.config.loss_round4)

import numpy as np
import modules.camera_calibration.wand_calibration.refraction_calibration_BA as ba_mod

# def old_point_to_ray_dist(X, o, d):
#     d = d / (np.linalg.norm(d) + 1e-12)
#     v = X - o
#     t = float(np.dot(v, d))
#     if t >= 0.0:
#         v_perp = v - t * d
#         return float(np.linalg.norm(v_perp))
#     else:
#         return float(np.linalg.norm(v))

# # 关键：改 BA 模块内部实际调用的符号
# ba_mod.point_to_ray_dist = old_point_to_ray_dist


# 看调用点真实传参
print(inspect.getsource(ba_mod.RefractiveBAOptimizer.optimize).splitlines()[145:190])  # 可调整范围

# =========================
# 0) Before
# =========================
eval_rmse(opt, "before")

# =========================
# 1) Joint round only (BA joint settings)
# =========================
opt._optimize_generic(
    mode="joint",
    description="Notebook Joint",
    enable_planes=True,
    enable_cam_t=True,
    enable_cam_r=True,
    limit_rot_rad=np.radians(20.0),
    limit_trans_mm=50.0,
    limit_plane_d_mm=50.0,
    limit_plane_angle_rad=np.radians(10.0),
    ftol=1e-6,
    loss=opt.config.loss_joint,   # now config-controlled
)
eval_rmse(opt, "after_joint")

# =========================
# 2) Final refined round (BA final_refined settings)
# =========================
enable_k1 = opt.config.dist_coeff_num >= 1
enable_k2 = opt.config.dist_coeff_num >= 2

opt._optimize_generic(
    mode="final_refined",
    description="Notebook FinalRefined",
    enable_planes=True,
    enable_cam_t=True,
    enable_cam_r=True,
    enable_cam_f=True,
    enable_win_t=True,
    enable_cam_k1=enable_k1,
    enable_cam_k2=enable_k2,
    limit_rot_rad=np.radians(20.0),
    limit_trans_mm=50.0,
    limit_plane_d_mm=10.0,
    limit_plane_angle_rad=np.radians(5.0),
    ftol=1e-6,
    loss=opt.config.loss_round4,  # now config-controlled
)
eval_rmse(opt, "after_final_refined")

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
cam_ids: [0, 1, 2, 3]
frames: 2500 first10: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
module file: D:\0.Code\OpenLPTGUI\OpenLPT\modules\camera_calibration\wand_calibration\refraction_calibration_BA.py
default losses: linear linear linear linear
opt losses: linear linear linear linear
[]
[before] ray_rmse_mm=0.232330749, len_rmse_mm=0.256456298, N_ray=20000, N_len=2500
  [Notebook Joint] optimizing 30 parameters (10 blocks)...
    [Constraint] S_ray/S_len (6.57) < 10. Forcing lambda=1.0 (was 8.0)
    Global Fixed Weighting: lambda=1.0 (N_cams=4)
    Initial: S_ray=1079.55, S_len=164.42 (J0=0.1197)
[nfev~  10] Notebook Joint | ray=0.232331 mm | len=0.256456 mm | cost=4.385429e+06
[nfev~  20] Notebook Joint | ray=0.232331 mm | len=0.256456 mm | cost=4.385429e+06
[nfev~  30] Notebook Joint | ray=0.232331 mm | len=0.256456 mm | cost=4.385429e+06
[nfev~  40] Notebook Joint | ray=0.207979 mm | len=0.256742 mm | cost=3.504068e+06
[nfev~  50] Notebook Joint | ray=0.207979 mm | len=0.256742 mm | cost=3.504097e+06
[nfev~  60] Notebook Joint | ray=0.207979 mm | len=0.256742 mm | cost=3.504097e+06
[nfev~  70] Notebook Joint | ray=0.166466 mm | len=0.257390 mm | cost=2.238316e+06
[nfev~  80] Notebook Joint | ray=0.166551 mm | len=0.257410 mm | cost=2.240614e+06
[nfev~  90] Notebook Joint | ray=0.166549 mm | len=0.257427 mm | cost=2.240551e+06
[nfev~ 100] Notebook Joint | ray=0.117932 mm | len=0.260161 mm | cost=1.122855e+06
[nfev~ 110] Notebook Joint | ray=0.117932 mm | len=0.260161 mm | cost=1.122858e+06
[nfev~ 120] Notebook Joint | ray=0.117926 mm | len=0.260160 mm | cost=1.122740e+06
[nfev~ 130] Notebook Joint | ray=0.067161 mm | len=0.270528 mm | cost=3.657645e+05
[nfev~ 140] Notebook Joint | ray=0.067161 mm | len=0.270522 mm | cost=3.657657e+05
[nfev~ 150] Notebook Joint | ray=0.066210 mm | len=0.270479 mm | cost=3.555432e+05
[nfev~ 160] Notebook Joint | ray=0.016776 mm | len=0.244569 mm | cost=2.454885e+04
[nfev~ 170] Notebook Joint | ray=0.017259 mm | len=0.244473 mm | cost=2.587129e+04
[nfev~ 180] Notebook Joint | ray=0.017265 mm | len=0.244473 mm | cost=2.588813e+04
[nfev~ 190] Notebook Joint | ray=0.005928 mm | len=0.145546 mm | cost=3.493747e+03
[nfev~ 200] Notebook Joint | ray=0.005932 mm | len=0.145554 mm | cost=3.497202e+03
[nfev~ 210] Notebook Joint | ray=0.005928 mm | len=0.145546 mm | cost=3.493607e+03
[nfev~ 220] Notebook Joint | ray=0.002998 mm | len=0.130576 mm | cost=1.257298e+03
[nfev~ 230] Notebook Joint | ray=0.002999 mm | len=0.130576 mm | cost=1.257422e+03
[nfev~ 240] Notebook Joint | ray=0.002999 mm | len=0.130576 mm | cost=1.257409e+03
[nfev~ 250] Notebook Joint | ray=0.001961 mm | len=0.127079 mm | cost=8.144859e+02
[nfev~ 260] Notebook Joint | ray=0.001921 mm | len=0.127158 mm | cost=8.027093e+02
[nfev~ 270] Notebook Joint | ray=0.002031 mm | len=0.126811 mm | cost=8.349275e+02
[nfev~ 280] Notebook Joint | ray=0.001418 mm | len=0.124051 mm | cost=6.429274e+02
[nfev~ 290] Notebook Joint | ray=0.001417 mm | len=0.124051 mm | cost=6.427921e+02
[nfev~ 300] Notebook Joint | ray=0.001435 mm | len=0.124050 mm | cost=6.468650e+02
[nfev~ 310] Notebook Joint | ray=0.001418 mm | len=0.124051 mm | cost=6.429317e+02
[nfev~ 320] Notebook Joint | ray=0.001378 mm | len=0.124027 mm | cost=6.336319e+02
[nfev~ 330] Notebook Joint | ray=0.001377 mm | len=0.124027 mm | cost=6.335757e+02
[nfev~ 340] Notebook Joint | ray=0.001732 mm | len=0.124023 mm | cost=7.224339e+02
[nfev~ 350] Notebook Joint | ray=0.001236 mm | len=0.124034 mm | cost=6.038946e+02
[nfev~ 360] Notebook Joint | ray=0.001386 mm | len=0.123579 mm | cost=6.320288e+02
[nfev~ 370] Notebook Joint | ray=0.002120 mm | len=0.123983 mm | cost=8.425501e+02
[nfev~ 380] Notebook Joint | ray=0.001435 mm | len=0.124163 mm | cost=6.476640e+02
[nfev~ 390] Notebook Joint | ray=0.001187 mm | len=0.124043 mm | cost=5.942978e+02
[nfev~ 400] Notebook Joint | ray=0.001187 mm | len=0.124043 mm | cost=5.944414e+02
[nfev~ 410] Notebook Joint | ray=0.001176 mm | len=0.124050 mm | cost=5.923175e+02
[nfev~ 420] Notebook Joint | ray=0.001213 mm | len=0.124057 mm | cost=5.994575e+02
[nfev~ 430] Notebook Joint | ray=0.001176 mm | len=0.124050 mm | cost=5.922769e+02
[nfev~ 440] Notebook Joint | ray=0.001176 mm | len=0.124050 mm | cost=5.923541e+02
  Termination: xtol (nfev=21)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=2.100deg, Δt=1.914mm
    Cam 1: Δr=1.116deg, Δt=3.788mm
    Cam 2: Δr=1.453deg, Δt=2.964mm
    Cam 3: Δr=2.597deg, Δt=1.807mm
  Window Δ:
    Win 0: Δd=1.1927mm, Δa=-0.1940deg, Δb=-0.3255deg
    Win 1: Δd=-2.0202mm, Δa=2.3821deg, Δb=1.5910deg
    Final:   S_ray=0.03, S_len=38.47 (JF=0.0154)
      RMSE Ray: 0.2323 -> 0.0012
      RMSE Len: 0.2565 -> 0.1240
[after_joint] ray_rmse_mm=0.001175988, len_rmse_mm=0.124049624, N_ray=20000, N_len=2500
  [Notebook FinalRefined] optimizing 36 parameters (12 blocks)...
    [Constraint] S_ray/S_len (0.00) < 10. Forcing lambda=1.0 (was 8.0)
    Global Fixed Weighting: lambda=1.0 (N_cams=4)
    Initial: S_ray=0.03, S_len=38.47 (J0=0.0154)
[nfev~ 450] Notebook FinalRefined | ray=0.001176 mm | len=0.124050 mm | cost=5.891304e+02
[nfev~ 460] Notebook FinalRefined | ray=0.001176 mm | len=0.124050 mm | cost=5.891304e+02
[nfev~ 470] Notebook FinalRefined | ray=0.001176 mm | len=0.124050 mm | cost=5.891302e+02
[nfev~ 480] Notebook FinalRefined | ray=0.000909 mm | len=0.107023 mm | cost=4.226282e+02
[nfev~ 490] Notebook FinalRefined | ray=0.000912 mm | len=0.106988 mm | cost=4.228468e+02
[nfev~ 500] Notebook FinalRefined | ray=0.000909 mm | len=0.107023 mm | cost=4.226301e+02
[nfev~ 510] Notebook FinalRefined | ray=0.000907 mm | len=0.107023 mm | cost=4.223391e+02
[nfev~ 520] Notebook FinalRefined | ray=0.000608 mm | len=0.082576 mm | cost=2.420558e+02
[nfev~ 530] Notebook FinalRefined | ray=0.000605 mm | len=0.082572 mm | cost=2.417636e+02
[nfev~ 540] Notebook FinalRefined | ray=0.000604 mm | len=0.082572 mm | cost=2.416702e+02
[nfev~ 550] Notebook FinalRefined | ray=0.000605 mm | len=0.082573 mm | cost=2.417609e+02
[nfev~ 560] Notebook FinalRefined | ray=0.000836 mm | len=0.068525 mm | cost=2.015009e+02
[nfev~ 570] Notebook FinalRefined | ray=0.000838 mm | len=0.068524 mm | cost=2.017020e+02
[nfev~ 580] Notebook FinalRefined | ray=0.000836 mm | len=0.068525 mm | cost=2.014975e+02
[nfev~ 590] Notebook FinalRefined | ray=0.000492 mm | len=0.054779 mm | cost=1.127107e+02
[nfev~ 600] Notebook FinalRefined | ray=0.000491 mm | len=0.054783 mm | cost=1.126717e+02
[nfev~ 610] Notebook FinalRefined | ray=0.000496 mm | len=0.054783 mm | cost=1.130723e+02
[nfev~ 620] Notebook FinalRefined | ray=0.000496 mm | len=0.054782 mm | cost=1.130337e+02
[nfev~ 630] Notebook FinalRefined | ray=0.000654 mm | len=0.048531 mm | cost=1.070928e+02
[nfev~ 640] Notebook FinalRefined | ray=0.000654 mm | len=0.048532 mm | cost=1.071026e+02
[nfev~ 650] Notebook FinalRefined | ray=0.000707 mm | len=0.048537 mm | cost=1.127380e+02
[nfev~ 660] Notebook FinalRefined | ray=0.000654 mm | len=0.048532 mm | cost=1.071010e+02
[nfev~ 670] Notebook FinalRefined | ray=0.000416 mm | len=0.046312 mm | cost=8.058432e+01
[nfev~ 680] Notebook FinalRefined | ray=0.000492 mm | len=0.046317 mm | cost=8.597340e+01
[nfev~ 690] Notebook FinalRefined | ray=0.000416 mm | len=0.046312 mm | cost=8.058396e+01
[nfev~ 700] Notebook FinalRefined | ray=0.000399 mm | len=0.045149 mm | cost=7.617359e+01
[nfev~ 710] Notebook FinalRefined | ray=0.000399 mm | len=0.045148 mm | cost=7.616025e+01
[nfev~ 720] Notebook FinalRefined | ray=0.000399 mm | len=0.045149 mm | cost=7.617340e+01
[nfev~ 730] Notebook FinalRefined | ray=0.000477 mm | len=0.044993 mm | cost=8.104229e+01
[nfev~ 740] Notebook FinalRefined | ray=0.000398 mm | len=0.044172 mm | cost=7.335389e+01
[nfev~ 750] Notebook FinalRefined | ray=0.000398 mm | len=0.044172 mm | cost=7.336188e+01
[nfev~ 760] Notebook FinalRefined | ray=0.000881 mm | len=0.043520 mm | cost=1.199951e+02
[nfev~ 770] Notebook FinalRefined | ray=0.000399 mm | len=0.044002 mm | cost=7.295870e+01
[nfev~ 780] Notebook FinalRefined | ray=0.000445 mm | len=0.043012 mm | cost=7.333410e+01
[nfev~ 790] Notebook FinalRefined | ray=0.000583 mm | len=0.042734 mm | cost=8.371228e+01
[nfev~ 800] Notebook FinalRefined | ray=0.000477 mm | len=0.042877 mm | cost=7.522785e+01
[nfev~ 810] Notebook FinalRefined | ray=0.000445 mm | len=0.043012 mm | cost=7.333603e+01
[nfev~ 820] Notebook FinalRefined | ray=0.001064 mm | len=0.042095 mm | cost=1.440649e+02
[nfev~ 830] Notebook FinalRefined | ray=0.000405 mm | len=0.042756 mm | cost=6.998155e+01
[nfev~ 840] Notebook FinalRefined | ray=0.000394 mm | len=0.042920 mm | cost=6.973753e+01
[nfev~ 850] Notebook FinalRefined | ray=0.000390 mm | len=0.042820 mm | cost=6.922052e+01
[nfev~ 860] Notebook FinalRefined | ray=0.000362 mm | len=0.042707 mm | cost=6.727724e+01
[nfev~ 870] Notebook FinalRefined | ray=0.000390 mm | len=0.042820 mm | cost=6.922610e+01
[nfev~ 880] Notebook FinalRefined | ray=0.000423 mm | len=0.042821 mm | cost=7.131782e+01
[nfev~ 890] Notebook FinalRefined | ray=0.000369 mm | len=0.042842 mm | cost=6.804267e+01
[nfev~ 900] Notebook FinalRefined | ray=0.000369 mm | len=0.042845 mm | cost=6.801431e+01
[nfev~ 910] Notebook FinalRefined | ray=0.000371 mm | len=0.042845 mm | cost=6.812051e+01
[nfev~ 920] Notebook FinalRefined | ray=0.000369 mm | len=0.042845 mm | cost=6.801427e+01
[nfev~ 930] Notebook FinalRefined | ray=0.000338 mm | len=0.042849 mm | cost=6.630553e+01
[nfev~ 940] Notebook FinalRefined | ray=0.000344 mm | len=0.042849 mm | cost=6.662311e+01
[nfev~ 950] Notebook FinalRefined | ray=0.000338 mm | len=0.042849 mm | cost=6.630654e+01
[nfev~ 960] Notebook FinalRefined | ray=0.000338 mm | len=0.042859 mm | cost=6.634894e+01
[nfev~ 970] Notebook FinalRefined | ray=0.000339 mm | len=0.042862 mm | cost=6.637997e+01
[nfev~ 980] Notebook FinalRefined | ray=0.000337 mm | len=0.042862 mm | cost=6.630647e+01
[nfev~ 990] Notebook FinalRefined | ray=0.000336 mm | len=0.042861 mm | cost=6.625909e+01
[nfev~1000] Notebook FinalRefined | ray=0.000336 mm | len=0.042863 mm | cost=6.624333e+01
[nfev~1010] Notebook FinalRefined | ray=0.000336 mm | len=0.042864 mm | cost=6.624269e+01
[nfev~1020] Notebook FinalRefined | ray=0.000395 mm | len=0.042869 mm | cost=6.961515e+01
[nfev~1030] Notebook FinalRefined | ray=0.000336 mm | len=0.042863 mm | cost=6.624322e+01
  Termination: xtol (nfev=19)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=0.167deg, Δt=0.916mm, Δf=-31.2167
    Cam 1: Δr=0.118deg, Δt=1.430mm, Δf=-10.1666
    Cam 2: Δr=0.104deg, Δt=1.189mm, Δf=-22.9598
    Cam 3: Δr=0.184deg, Δt=1.398mm, Δf=-10.4894
  Window Δ:
    Win 0: Δd=0.0532mm, Δa=0.0869deg, Δb=0.1368deg, Δt=-0.0348mm
    Win 1: Δd=0.0533mm, Δa=0.1522deg, Δb=-0.0609deg, Δt=-0.1977mm
    Final:   S_ray=0.00, S_len=4.59 (JF=0.0018)
      RMSE Ray: 0.0012 -> 0.0003
      RMSE Len: 0.1240 -> 0.0429
[after_final_refined] ray_rmse_mm=0.000335831, len_rmse_mm=0.042863511, N_ray=20000, N_len=2500

(np.float64(0.00033583123883770783),
 np.float64(0.042863510927315066),
 20000,
 2500)

In [1]:
# =========================
# Single Cell: load -> align -> same joint optimize (robust parser)
# =========================
import os
import re
import csv
import glob
import copy
import numpy as np
import cv2

from modules.camera_calibration.wand_calibration.refraction_calibration_BA import (
    RefractiveBAConfig, RefractiveBAOptimizer
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import CppCameraFactory
from modules.camera_calibration.wand_calibration.refractive_geometry import (
    build_pinplate_rays_cpp_batch,
    triangulate_point,
    align_world_y_to_plane_intersection,
)

# ---------- user paths ----------
init_cam_dir = r"H:\20260210\T0\Synthetic_test\camFile_joint"
obs_csv      = r"H:\20260210\T0\synthetic_wand_points.csv"

# ---------- knobs ----------
MAX_FRAMES  = 0       # 0 = all frames
WAND_LEN_MM = 10.0
IMG_SIZE    = (800, 1280)


# ---------- helpers ----------
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and (not s.startswith("#")):
            return s, j
        j += 1
    return None, j

def _to_floats(s):
    # 支持 "1,2,3" / "1 2 3" / 混合分隔
    toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
    return [float(t) for t in toks]

def _to_ints(s):
    toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
    return [int(float(t)) for t in toks]  # 防 "800.0"

def parse_cam_file(path):
    import re
    import numpy as np
    import cv2

    def _next_data(lines, i):
        j = i + 1
        while j < len(lines):
            s = lines[j].strip()
            if s and (not s.startswith("#")):
                return s, j
            j += 1
        return None, j

    def _to_floats(s):
        toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
        return [float(t) for t in toks]

    def _to_ints(s):
        toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
        return [int(float(t)) for t in toks]

    d = {}
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Model"):
            row, _ = _next_data(lines, i)
            d["model_name"] = row.strip() if row is not None else "PINPLATE"

        elif s.startswith("# Image Size"):
            row, _ = _next_data(lines, i)
            rr = _to_ints(row)
            d["n_row"], d["n_col"] = rr[0], rr[1]

        elif s.startswith("# Camera Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            K = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)
            d["K"] = K
            d["f"] = float(K[0, 0])
            d["cx"] = float(K[0, 2])
            d["cy"] = float(K[1, 2])

        elif s.startswith("# Distortion Coefficients"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)
            d["k1"] = rr[0] if len(rr) > 0 else 0.0
            d["k2"] = rr[1] if len(rr) > 1 else 0.0

        elif s.startswith("# Rotation Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)

        elif s.startswith("# Translation Vector"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane reference point" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane normal" in s:
            row, _ = _next_data(lines, i)
            n = np.array(_to_floats(row), dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)  # obj,win,air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = _to_floats(row)[0]

        elif s.startswith("# WINDOW_ID="):
            d["wid_meta"] = int(s.split("=", 1)[1])

    # 关键：永远由 R 反算 rvec
    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()

    need = ["rvec", "tvec", "f", "cx", "cy", "plane_far", "plane_n", "n1", "n2", "n3", "thickness"]
    miss = [k for k in need if k not in d]
    if miss:
        raise ValueError(f"Missing keys in {path}: {miss}")

    return d

def load_cam_set(cam_dir, with_plane=True):
    cam_params, cam_to_window = {}, {}
    window_planes, window_media = {}, {}

    cam_files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
    assert len(cam_files) > 0, f"No cam*.txt in {cam_dir}"

    for path in cam_files:
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array([
            d["rvec"][0], d["rvec"][1], d["rvec"][2],
            d["tvec"][0], d["tvec"][1], d["tvec"][2],
            d["f"], d["cx"], d["cy"], d.get("k1", 0.0), d.get("k2", 0.0)
        ], dtype=np.float64)

        # 优先使用文件 meta 里的 WINDOW_ID
        if "wid_meta" in d:
            wid = int(d["wid_meta"])
        else:
            wid = 0 if cid <= 4 else 1  # fallback
        cam_to_window[cid] = wid

        if with_plane and (wid not in window_planes):
            # 文件存的是 farthest interface；优化器用 closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            window_planes[wid] = {
                "plane_pt": p_close,
                "plane_n": d["plane_n"],
                "initialized": True
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"]
            }

    return cam_params, cam_to_window, window_planes, window_media


def load_obs_dataset(csv_path, max_frames=0):
    obsA, obsB, frames = {}, {}, set()
    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {
        "obsA": obsA,
        "obsB": obsB,
        "frames": frames,
        "cam_ids": None,
        "est_radius_small_mm": 1.5,
        "est_radius_large_mm": 2.0,
    }


def eval_rmse(opt, tag):
    lam = 2.0 * max(1, len(opt.cam_params))
    _, S_ray, S_len, N_ray, N_len = opt.evaluate_residuals(
        opt.window_planes, opt.cam_params, lam, window_media=opt.window_media
    )
    ray_rmse = np.sqrt(S_ray / max(1, N_ray))
    len_rmse = np.sqrt(S_len / max(1, N_len)) if N_len > 0 else np.nan
    print(f"[{tag}] ray_rmse_mm={ray_rmse:.9f}, len_rmse_mm={len_rmse:.9f}, N_ray={N_ray}, N_len={N_len}")
    return ray_rmse, len_rmse, N_ray, N_len


def collect_points_for_alignment(opt):
    dataset = opt.dataset
    cams_cpp = opt.cams_cpp
    cam_params = opt.cam_params
    cam_to_window = opt.cam_to_window
    pts = []

    def _tri_all(obs_dict):
        out = []
        rays_by_fid = {fid: [] for fid in obs_dict.keys()}
        per_cam = {}

        for fid, cam_obs in obs_dict.items():
            for cid, uv in cam_obs.items():
                if cid not in cams_cpp or cid not in cam_params:
                    continue
                per_cam.setdefault(cid, []).append((fid, uv))

        for cid, items in per_cam.items():
            wid = cam_to_window.get(cid)
            uv_list = [uv for _, uv in items]
            meta_list = [
                {"cam_id": cid, "window_id": wid, "frame_id": fid, "endpoint": "?"}
                for fid, _ in items
            ]
            rays = build_pinplate_rays_cpp_batch(cams_cpp[cid], uv_list, meta_list=meta_list)
            for (fid, _), r in zip(items, rays):
                if r.valid:
                    rays_by_fid[fid].append(r)

        for fid in obs_dict.keys():
            rays = rays_by_fid[fid]
            if len(rays) >= 2:
                X, _, valid, _ = triangulate_point(rays)
                if valid:
                    out.append(X)
        return out

    pts.extend(_tri_all(dataset.get("obsA", {})))
    pts.extend(_tri_all(dataset.get("obsB", {})))
    return pts


# =========================
# 1) Load
# =========================
cam_init, cam_to_window, window_planes_init, window_media_init = load_cam_set(init_cam_dir, with_plane=True)
dataset = load_obs_dataset(obs_csv, max_frames=MAX_FRAMES)
dataset["cam_ids"] = sorted(cam_init.keys())

print("cam_to_window:", cam_to_window)
for cid, p in cam_init.items():
    print(f"cam{cid}: rvec_norm_deg={np.linalg.norm(p[:3])*180/np.pi:.3f}, tvec={p[3:6]}")


class _Base:
    pass
base = _Base()
base.image_size = IMG_SIZE

cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_init,
    window_media=window_media_init,
    cam_to_window=cam_to_window,
    window_planes=window_planes_init
)

cfg = RefractiveBAConfig(
    stage=0,
    verbosity=1,
    max_frames=(MAX_FRAMES if MAX_FRAMES > 0 else 0),
    diff_step_mode_joint="auto",
    diff_step_mode_final="auto",
)

_cb = {"k": 0}
def progress_cb(phase, ray_rmse, len_rmse, cost):
    _cb["k"] += 1
    nfev_est = _cb["k"] * 10
    print(f"[nfev~{nfev_est:4d}] {phase} | ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | cost={cost:.6e}")


opt = RefractiveBAOptimizer(
    dataset=dataset,
    cam_params={k: v.copy() for k, v in cam_init.items()},
    cams_cpp=cams_cpp,
    cam_to_window=cam_to_window,
    window_media=copy.deepcopy(window_media_init),
    window_planes=copy.deepcopy(window_planes_init),
    wand_length=WAND_LEN_MM,
    config=cfg,
    progress_callback=progress_cb
)
opt._compute_physical_sigmas()

print("cam_ids:", sorted(opt.cam_params.keys()))
print("window_ids:", sorted(opt.window_planes.keys()))
print("frames:", len(opt.fids_optim), "first10:", opt.fids_optim[:10])

# =========================
# 2) Before align
# =========================
eval_rmse(opt, "before_align")

# =========================
# 3) Align (rotate + shift)
# =========================
pts3d = collect_points_for_alignment(opt)
print(f"[align] points_for_centroid={len(pts3d)}")

ret = align_world_y_to_plane_intersection(
    opt.window_planes, opt.cam_params, points_3d=pts3d
)
if len(ret) == 5:
    cam_aligned, planes_aligned, _, R_align, t_shift = ret
else:
    cam_aligned, planes_aligned, _, R_align = ret
    t_shift = np.zeros(3, dtype=float)

opt.cam_params = {int(k): np.array(v, dtype=np.float64) for k, v in cam_aligned.items()}
opt.window_planes = copy.deepcopy(planes_aligned)
opt.sync_cpp_state(
    cam_params=opt.cam_params,
    window_planes=opt.window_planes,
    window_media=opt.window_media
)

# 用对齐后状态作为新初值
opt._sync_initial_state()
opt._compute_physical_sigmas()

print("[align] done")
print("[align] R_align=\n", R_align)
print("[align] t_shift=", t_shift)

eval_rmse(opt, "after_align_before_joint")

# =========================
# 4) Same JOINT optimize
# =========================
opt._optimize_generic(
    mode="joint",
    description="Notebook Joint",
    enable_planes=True,
    enable_cam_t=True,
    enable_cam_r=True,
    limit_rot_rad=np.radians(20.0),
    limit_trans_mm=50.0,
    limit_plane_d_mm=50.0,
    limit_plane_angle_rad=np.radians(10.0),
    ftol=1e-6,
    xtol=1e-6,
    gtol=1e-6,
    max_nfev=300,
    loss=opt.config.loss_joint,
)

eval_rmse(opt, "after_joint_from_aligned_init")
opt._print_plane_diagnostics("Joint End (Aligned Init)")

cam_to_window: {0: 0, 1: 1, 2: 1, 3: 0}
cam0: rvec_norm_deg=0.909, tvec=[-3.5592542 -1.4794667  6.6928316]
cam1: rvec_norm_deg=89.062, tvec=[184.65774    -7.7781103 201.6052   ]
cam2: rvec_norm_deg=91.307, tvec=[184.56527    -7.7120511 203.98762  ]
cam3: rvec_norm_deg=17.570, tvec=[-1.2466151 55.433966  16.507631 ]

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
Unit Normalization: sigma_ray=0.0224mm (1.0px at Z=201.4mm), sigma_wand=0.2000mm (2.0%)
cam_ids: [0, 1, 2, 3]
window_ids: [0, 1]
frames: 2500 first10: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[before_align] ray_rmse_mm=0.092704995, len_rmse_mm=0.243131943, N_ray=20000, N_len=2500
[align] points_for_centroid=5000
[Coordinate Alignment] Intersection line direction: [-0.2016, 0.9761, -0.0815]
[Coordinate Alignment] Intersection line direction: [-0.2016, 0.9761, -0.0815]
[ALIGN CHECK] Y-Axis (Intersection): [-4.27069348e-18  1.00000000e+00  1.89668606e-17]
[ALIGN CHECK] Z-Axis (Plane 0 Normal): [-2.01129160e-17  1.89668606e-17  1.00000000e+00]
[Coordinate Alignment] Centering World at Cloud Centroid: [  4.18181678  -0.68259398 184.97554375]
[Coordinate Alignment] Applied rotation and translation to align coordinates.
Unit Normalization: sigma_ray=0.0224mm (1.0px at Z=201.4mm), sigma_wand=0.2000mm (2.0%)
[align] done
[align] R_align=
 [[ 0.97721405  0.19478644 -0.08432645]
 [-0.20159031  0.97607522 -0.08147701]
 [ 0.06643834  0.09661988  0.99310148]]
[align] t_shift= [  -4.18181678    0.68259398 -184.97554375]
[after_align_before_joint] ray_rmse_mm=0.092704995, len_rmse_mm=0.243131943, N_ray=20000, N_len=2500
Unit Normalization: sigma_ray=0.0224mm (1.0px at Z=201.4mm), sigma_wand=0.2000mm (2.0%)
  [Barrier] profile=mid, gate_scale=0.500, beta_dir_scale=0.500, tau=0.020, soft_on=True
  [RoundConfig] mode=joint, loss=linear, ftol=1e-06, xtol=1e-06, gtol=1e-06, max_nfev=300, diff_step_mode=auto
  diff_step: auto (scipy default)
  [Notebook Joint] optimizing 30 parameters (10 blocks)...
    Global Fixed Weighting: lambda=8.0 (N_cams_total=4)
    Initial: S_ray=171.88, S_len=147.78 (J0=0.4815)
[nfev~  10] Notebook Joint | ray=0.092705 mm | len=0.243132 mm | cost=1.864523e+05
[nfev~  20] Notebook Joint | ray=0.092705 mm | len=0.243132 mm | cost=1.864523e+05
[nfev~  30] Notebook Joint | ray=0.092705 mm | len=0.243132 mm | cost=1.864523e+05
[nfev~  40] Notebook Joint | ray=0.086473 mm | len=0.240189 mm | cost=1.637919e+05
[nfev~  50] Notebook Joint | ray=0.086473 mm | len=0.240189 mm | cost=1.637919e+05
[nfev~  60] Notebook Joint | ray=0.086473 mm | len=0.240189 mm | cost=1.637918e+05
[nfev~  70] Notebook Joint | ray=0.074857 mm | len=0.233210 mm | cost=1.255302e+05
[nfev~  80] Notebook Joint | ray=0.074857 mm | len=0.233210 mm | cost=1.255302e+05
[nfev~  90] Notebook Joint | ray=0.074857 mm | len=0.233210 mm | cost=1.255302e+05
[nfev~ 100] Notebook Joint | ray=0.064148 mm | len=0.211908 mm | cost=9.342523e+04
[nfev~ 110] Notebook Joint | ray=0.064148 mm | len=0.211908 mm | cost=9.342523e+04
[nfev~ 120] Notebook Joint | ray=0.064148 mm | len=0.211908 mm | cost=9.342523e+04
[nfev~ 130] Notebook Joint | ray=0.036632 mm | len=0.169011 mm | cost=3.394672e+04
[nfev~ 140] Notebook Joint | ray=0.036632 mm | len=0.169011 mm | cost=3.394672e+04
[nfev~ 150] Notebook Joint | ray=0.036632 mm | len=0.169011 mm | cost=3.394673e+04
[nfev~ 160] Notebook Joint | ray=0.006647 mm | len=0.040718 mm | cost=1.297012e+03
[nfev~ 170] Notebook Joint | ray=0.006647 mm | len=0.040718 mm | cost=1.297012e+03
[nfev~ 180] Notebook Joint | ray=0.006647 mm | len=0.040718 mm | cost=1.297013e+03
[nfev~ 190] Notebook Joint | ray=0.002511 mm | len=0.009279 mm | cost=1.474862e+02
[nfev~ 200] Notebook Joint | ray=0.002511 mm | len=0.009279 mm | cost=1.474865e+02
[nfev~ 210] Notebook Joint | ray=0.002511 mm | len=0.009279 mm | cost=1.474868e+02
[nfev~ 220] Notebook Joint | ray=0.000627 mm | len=0.004166 mm | cost=1.220244e+01
[nfev~ 230] Notebook Joint | ray=0.000627 mm | len=0.004166 mm | cost=1.220252e+01
[nfev~ 240] Notebook Joint | ray=0.000627 mm | len=0.004166 mm | cost=1.220225e+01
[nfev~ 250] Notebook Joint | ray=0.000266 mm | len=0.000538 mm | cost=1.489887e+00
[nfev~ 260] Notebook Joint | ray=0.000266 mm | len=0.000538 mm | cost=1.489716e+00
[nfev~ 270] Notebook Joint | ray=0.000266 mm | len=0.000538 mm | cost=1.489887e+00
[nfev~ 280] Notebook Joint | ray=0.000071 mm | len=0.000323 mm | cost=1.255356e-01
[nfev~ 290] Notebook Joint | ray=0.000071 mm | len=0.000323 mm | cost=1.255404e-01
[nfev~ 300] Notebook Joint | ray=0.000071 mm | len=0.000323 mm | cost=1.255357e-01
[nfev~ 310] Notebook Joint | ray=0.000071 mm | len=0.000323 mm | cost=1.255259e-01
[nfev~ 320] Notebook Joint | ray=0.000060 mm | len=0.000273 mm | cost=9.160280e-02
[nfev~ 330] Notebook Joint | ray=0.000060 mm | len=0.000273 mm | cost=9.159765e-02
[nfev~ 340] Notebook Joint | ray=0.000060 mm | len=0.000273 mm | cost=9.160812e-02
[nfev~ 350] Notebook Joint | ray=0.000052 mm | len=0.000210 mm | cost=6.548387e-02
[nfev~ 360] Notebook Joint | ray=0.000052 mm | len=0.000210 mm | cost=6.548410e-02
[nfev~ 370] Notebook Joint | ray=0.000052 mm | len=0.000210 mm | cost=6.548514e-02
[nfev~ 380] Notebook Joint | ray=0.000042 mm | len=0.000148 mm | cost=4.006541e-02
[nfev~ 390] Notebook Joint | ray=0.000042 mm | len=0.000148 mm | cost=4.006575e-02
[nfev~ 400] Notebook Joint | ray=0.000042 mm | len=0.000148 mm | cost=4.006691e-02
[nfev~ 410] Notebook Joint | ray=0.000032 mm | len=0.000087 mm | cost=2.189421e-02
[nfev~ 420] Notebook Joint | ray=0.000032 mm | len=0.000087 mm | cost=2.189275e-02
[nfev~ 430] Notebook Joint | ray=0.000032 mm | len=0.000087 mm | cost=2.189299e-02
[nfev~ 440] Notebook Joint | ray=0.000027 mm | len=0.000053 mm | cost=1.563194e-02
[nfev~ 450] Notebook Joint | ray=0.000027 mm | len=0.000053 mm | cost=1.563206e-02
[nfev~ 460] Notebook Joint | ray=0.000027 mm | len=0.000053 mm | cost=1.563440e-02
[nfev~ 470] Notebook Joint | ray=0.000025 mm | len=0.000027 mm | cost=1.239415e-02
[nfev~ 480] Notebook Joint | ray=0.000025 mm | len=0.000027 mm | cost=1.239468e-02
[nfev~ 490] Notebook Joint | ray=0.000025 mm | len=0.000027 mm | cost=1.239529e-02
[nfev~ 500] Notebook Joint | ray=0.000025 mm | len=0.000018 mm | cost=1.213551e-02
[nfev~ 510] Notebook Joint | ray=0.000025 mm | len=0.000018 mm | cost=1.214979e-02
[nfev~ 520] Notebook Joint | ray=0.000025 mm | len=0.000018 mm | cost=1.213522e-02
[nfev~ 530] Notebook Joint | ray=0.000025 mm | len=0.000016 mm | cost=1.209440e-02
[nfev~ 540] Notebook Joint | ray=0.000025 mm | len=0.000016 mm | cost=1.209620e-02
[nfev~ 550] Notebook Joint | ray=0.000025 mm | len=0.000016 mm | cost=1.209444e-02
[nfev~ 560] Notebook Joint | ray=0.000025 mm | len=0.000016 mm | cost=1.218689e-02
[nfev~ 570] Notebook Joint | ray=0.000024 mm | len=0.000016 mm | cost=1.194756e-02
[nfev~ 580] Notebook Joint | ray=0.000024 mm | len=0.000016 mm | cost=1.194754e-02
[nfev~ 590] Notebook Joint | ray=0.000024 mm | len=0.000016 mm | cost=1.194652e-02
[nfev~ 600] Notebook Joint | ray=0.000022 mm | len=0.000016 mm | cost=9.355785e-03
[nfev~ 610] Notebook Joint | ray=0.000022 mm | len=0.000016 mm | cost=9.354890e-03
[nfev~ 620] Notebook Joint | ray=0.000022 mm | len=0.000016 mm | cost=9.356007e-03
[nfev~ 630] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.830781e-03
[nfev~ 640] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.830799e-03
[nfev~ 650] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.830701e-03
[nfev~ 660] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.806227e-03
[nfev~ 670] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.806110e-03
[nfev~ 680] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.806102e-03
[nfev~ 690] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.763120e-03
[nfev~ 700] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.763117e-03
[nfev~ 710] Notebook Joint | ray=0.000021 mm | len=0.000016 mm | cost=8.763068e-03
  Termination: xtol (nfev=26)
  Message: `xtol` termination condition is satisfied.
  Camera Δ:
    Cam 0: Δr=2.760deg, Δt=3.829mm
    Cam 1: Δr=1.317deg, Δt=5.684mm
    Cam 2: Δr=1.454deg, Δt=5.053mm
    Cam 3: Δr=2.276deg, Δt=3.812mm
  Window Δ:
    Win 0: Δd=2.4310mm, Δa=0.4060deg, Δb=2.3129deg
    Win 1: Δd=0.1533mm, Δa=-0.3020deg, Δb=0.5872deg
    [RefractiveCalib][SIDE-BARRIER] min(sX)=4.3589mm, near(<20um)=0.0%, vio=0, cost/J=1.5e-97
    Final:   S_ray=0.00, S_len=0.00 (JF=0.0000)
      RMSE Ray: 0.0927 -> 0.0000
      RMSE Len: 0.2431 -> 0.0000
[after_joint_from_aligned_init] ray_rmse_mm=0.000020868, len_rmse_mm=0.000016067, N_ray=20000, N_len=2500

  [Joint End (Aligned Init)] Plane Diagnostics:
    Win 0: n=[-0.0403, 0.0071, 0.9992], pt=[3.35, -10.17, -25.19]
      -> Cam 0: Dist 167.75 mm
      -> Cam 3: Dist 165.40 mm
    Win 1: n=[0.9949, -0.0102, 0.1008], pt=[-14.22, 8.06, -1.30]
      -> Cam 1: Dist 193.94 mm
      -> Cam 2: Dist 198.66 mm
    Angle between Win 0 and Win 1: 86.53°

add location perturbation to plane and check calibration

In [1]:
# ============================================
# Realtime parallel test for plane shift impact
# ============================================

import os
import re
import csv
import glob
import copy
import time
import math
import threading
import traceback
import contextlib
import io

import numpy as np
import cv2
from concurrent.futures import ThreadPoolExecutor, as_completed
from IPython.display import display, Markdown

from modules.camera_calibration.wand_calibration.refraction_calibration_BA import (
    RefractiveBAConfig, RefractiveBAOptimizer
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import CppCameraFactory

# -----------------------------
# Inputs
# -----------------------------
init_cam_dir = r"J:\Fish\R2\camFile"
obs_csv      = r"J:\Fish\R2\wand_points_filtered.csv"

SHIFTS_MM   = [-5.0, -2.0, 0.0, 2.0, 5.0]
MAX_WORKERS = 1 #len(SHIFTS_MM)   # 每个shift一个worker
MAX_FRAMES  = 0                # 0 = all
WAND_LEN_MM = 10.0
IMG_SIZE    = (800, 1280)

# 若你发现5并发卡住（C++对象并发初始化问题），临时改成2或3：
# MAX_WORKERS = 2


# -----------------------------
# Parse / Load helpers
# -----------------------------
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and (not s.startswith("#")):
            return s, j
        j += 1
    return None, j

def _to_floats(s):
    toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
    return [float(t) for t in toks]

def parse_cam_file(path):
    d = {}
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            K = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)
            d["f"]  = float(K[0, 0])
            d["cx"] = float(K[0, 2])
            d["cy"] = float(K[1, 2])

        elif s.startswith("# Distortion Coefficients"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)
            d["k1"] = rr[0] if len(rr) > 0 else 0.0
            d["k2"] = rr[1] if len(rr) > 1 else 0.0

        elif s.startswith("# Rotation Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)

        elif s.startswith("# Translation Vector"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane reference point" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane normal" in s:
            row, _ = _next_data(lines, i)
            n = np.array(_to_floats(row), dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)  # obj,win,air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = _to_floats(row)[0]

        elif s.startswith("# WINDOW_ID="):
            d["wid_meta"] = int(s.split("=", 1)[1])

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()

    need = ["rvec", "tvec", "f", "cx", "cy", "plane_far", "plane_n", "n1", "n2", "n3", "thickness"]
    miss = [k for k in need if k not in d]
    if miss:
        raise ValueError(f"Missing keys in {path}: {miss}")
    return d

def load_cam_set(cam_dir, with_plane=True):
    cam_params, cam_to_window = {}, {}
    window_planes, window_media = {}, {}

    cam_files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
    if not cam_files:
        raise RuntimeError(f"No cam*.txt in {cam_dir}")

    for path in cam_files:
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array([
            d["rvec"][0], d["rvec"][1], d["rvec"][2],
            d["tvec"][0], d["tvec"][1], d["tvec"][2],
            d["f"], d["cx"], d["cy"], d.get("k1", 0.0), d.get("k2", 0.0)
        ], dtype=np.float64)

        wid = int(d["wid_meta"]) if "wid_meta" in d else (0 if cid <= 4 else 1)
        cam_to_window[cid] = wid

        if with_plane and (wid not in window_planes):
            # file stores farthest interface; optimizer uses closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            window_planes[wid] = {
                "plane_pt": np.array(p_close, dtype=np.float64),
                "plane_n": np.array(d["plane_n"], dtype=np.float64),
                "initialized": True
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"]
            }

    return cam_params, cam_to_window, window_planes, window_media

def load_obs_dataset(csv_path, max_frames=0):
    obsA, obsB, frames = {}, {}, set()
    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {
        "obsA": obsA,
        "obsB": obsB,
        "frames": frames,
        "cam_ids": None,
        "est_radius_small_mm": 1.5,
        "est_radius_large_mm": 2.0,
    }


# -----------------------------
# Optimization helpers
# -----------------------------
def eval_rmse(opt):
    lam = 2.0 * max(1, len(opt.cam_params))
    _, S_ray, S_len, N_ray, N_len = opt.evaluate_residuals(
        opt.window_planes, opt.cam_params, lam, window_media=opt.window_media
    )
    ray_rmse = math.sqrt(S_ray / max(1, N_ray))
    len_rmse = math.sqrt(S_len / max(1, N_len)) if N_len > 0 else float("nan")
    return ray_rmse, len_rmse, S_ray, S_len

def _set_status(status_map, lock, shift_mm, **kwargs):
    with lock:
        status_map[shift_mm].update(kwargs)

def build_optimizer(cam_params, cam_to_window, window_planes, window_media, dataset, progress_cb):
    class _Base: pass
    base = _Base()
    base.image_size = IMG_SIZE
    base.dist_coeff_num = 0

    cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
        base=base,
        cam_params=cam_params,
        window_media=window_media,
        cam_to_window=cam_to_window,
        window_planes=window_planes
    )

    cfg = RefractiveBAConfig(
        stage=0,
        verbosity=0,
        max_frames=(MAX_FRAMES if MAX_FRAMES > 0 else 0),
        diff_step_mode_joint="auto",
        diff_step_mode_final="auto",
    )

    opt = RefractiveBAOptimizer(
        dataset=dataset,
        cam_params={k: v.copy() for k, v in cam_params.items()},
        cams_cpp=cams_cpp,
        cam_to_window=cam_to_window,
        window_media=copy.deepcopy(window_media),
        window_planes=copy.deepcopy(window_planes),
        wand_length=WAND_LEN_MM,
        config=cfg,
        progress_callback=progress_cb
    )
    opt._compute_physical_sigmas()
    return opt

def run_one_shift(shift_mm, cam_init, cam_to_window, window_planes_init, window_media_init, dataset, status_map, lock):
    try:
        _set_status(status_map, lock, shift_mm, status="starting", nfev_est=0, ray_rmse=None, len_rmse=None, error="", t_last=time.time())

        cam_params = {k: v.copy() for k, v in cam_init.items()}
        window_planes = copy.deepcopy(window_planes_init)
        window_media = copy.deepcopy(window_media_init)

        _set_status(status_map, lock, shift_mm, status="perturbing", t_last=time.time())
        for wid, pl in window_planes.items():
            n = np.asarray(pl["plane_n"], dtype=float)
            n = n / (np.linalg.norm(n) + 1e-12)
            pt = np.asarray(pl["plane_pt"], dtype=float)
            pl["plane_n"] = n
            pl["plane_pt"] = pt + shift_mm * n

        nfev_counter = {"k": 0}
        def progress_cb(phase, ray_rmse, len_rmse, cost):
            nfev_counter["k"] += 1
            _set_status(
                status_map, lock, shift_mm,
                status="optimizing",
                nfev_est=nfev_counter["k"] * 10,
                ray_rmse=float(ray_rmse) if ray_rmse is not None else None,
                len_rmse=float(len_rmse) if len_rmse is not None else None,
                cost=float(cost) if cost is not None else None,
                t_last=time.time()
            )

        t0 = time.time()
        _set_status(status_map, lock, shift_mm, status="building_cpp", t_last=time.time())

        # 为了不刷屏，静默内部print
        with contextlib.redirect_stdout(io.StringIO()):
            opt = build_optimizer(cam_params, cam_to_window, window_planes, window_media, dataset, progress_cb)

        _set_status(status_map, lock, shift_mm, status="eval_before", t_last=time.time())
        with contextlib.redirect_stdout(io.StringIO()):
            ray0, len0, Sray0, Slen0 = eval_rmse(opt)

        _set_status(status_map, lock, shift_mm, status="optimizing", t_last=time.time())
        with contextlib.redirect_stdout(io.StringIO()):
            res, _ = opt._optimize_generic(
                mode="joint",
                description=f"Joint shift {shift_mm:+.1f}mm",
                enable_planes=True,
                enable_cam_t=True,
                enable_cam_r=True,
                limit_rot_rad=np.radians(20.0),
                limit_trans_mm=50.0,
                limit_plane_d_mm=50.0,
                limit_plane_angle_rad=np.radians(10.0),
                ftol=1e-6,
                xtol=1e-6,
                gtol=1e-6,
                loss=opt.config.loss_joint,
                max_nfev=20,
            )

        _set_status(status_map, lock, shift_mm, status="eval_after", t_last=time.time())
        with contextlib.redirect_stdout(io.StringIO()):
            ray1, len1, Sray1, Slen1 = eval_rmse(opt)

        elapsed = time.time() - t0
        nfev = getattr(res, "nfev", None)

        out = {
            "shift_mm": shift_mm,
            "status": "done",
            "elapsed_s": elapsed,
            "nfev": int(nfev) if nfev is not None else None,
            "ray_before": float(ray0),
            "len_before": float(len0),
            "ray_after": float(ray1),
            "len_after": float(len1),
            "Sray_before": float(Sray0),
            "Slen_before": float(Slen0),
            "Sray_after": float(Sray1),
            "Slen_after": float(Slen1),
            "t_last": time.time(),
        }
        _set_status(status_map, lock, shift_mm, **out)
        return out

    except Exception as e:
        _set_status(
            status_map, lock, shift_mm,
            status="failed",
            error=f"{type(e).__name__}: {e}",
            traceback=traceback.format_exc(),
            t_last=time.time(),
        )
        raise


# -----------------------------
# Main runner
# -----------------------------
cam_init, cam_to_window, window_planes_init, window_media_init = load_cam_set(init_cam_dir, with_plane=True)
dataset = load_obs_dataset(obs_csv, max_frames=MAX_FRAMES)
dataset["cam_ids"] = sorted(cam_init.keys())

status_map = {}
lock = threading.Lock()
for s in SHIFTS_MM:
    status_map[s] = {
        "status": "queued",
        "nfev_est": 0,
        "ray_rmse": None,
        "len_rmse": None,
        "cost": None,
        "error": "",
        "t_last": time.time(),
    }

futures = []
results = []
start_all = time.time()

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
    for s in SHIFTS_MM:
        futures.append(ex.submit(
            run_one_shift, s,
            cam_init, cam_to_window, window_planes_init, window_media_init, dataset,
            status_map, lock
        ))

    panel = display(Markdown("Starting workers..."), display_id=True)

    while True:
        done_cnt = sum(1 for f in futures if f.done())
        now = time.time()

        lines = []
        lines.append("### Plane Shift Joint Test (Realtime)")
        lines.append(f"- Done: **{done_cnt}/{len(futures)}**")
        lines.append(f"- Elapsed: **{now - start_all:.1f} s**")
        lines.append("")
        lines.append("| Shift (mm) | Status | nfev~ | Ray RMSE (mm) | Len RMSE (mm) | Last update (s ago) | Error |")
        lines.append("|---:|:---|---:|---:|---:|---:|:---|")

        with lock:
            for s in sorted(SHIFTS_MM):
                st = status_map[s]
                ray = st.get("ray_rmse")
                ln = st.get("len_rmse")
                err = st.get("error", "")
                if len(err) > 40:
                    err = err[:40] + "..."
                lag = now - st.get("t_last", now)

                ray_txt = "-" if ray is None else f"{ray:.6f}"
                len_txt = "-" if ln is None else f"{ln:.6f}"

                lines.append(
                    f"| {s:+.1f} | {st.get('status','?')} | {st.get('nfev_est',0)} | "
                    f"{ray_txt} | {len_txt} | {lag:.1f} | {err} |"
                )

        panel.update(Markdown("\n".join(lines)))

        if done_cnt == len(futures):
            break
        time.sleep(0.4)

    for f in as_completed(futures):
        try:
            results.append(f.result())
        except Exception:
            pass

# Final summary
ok = [r for r in results if r.get("status") == "done"]
fail = [s for s in SHIFTS_MM if status_map[s].get("status") == "failed"]

lines = []
lines.append("### Plane Shift Joint Test (Completed)")
if ok:
    ok = sorted(ok, key=lambda x: x["ray_after"])
    lines.append("")
    lines.append("| Shift | nfev | Time(s) | Ray before | Ray after | Len after |")
    lines.append("|---:|---:|---:|---:|---:|---:|")
    for r in ok:
        lines.append(
            f"| {r['shift_mm']:+.1f} | {r['nfev']} | {r['elapsed_s']:.1f} | "
            f"{r['ray_before']:.6f} | {r['ray_after']:.6f} | {r['len_after']:.6f} |"
        )

if fail:
    lines.append("")
    lines.append("**Failed shifts**")
    for s in fail:
        lines.append(f"- {s:+.1f}: {status_map[s].get('error')}")

display(Markdown("\n".join(lines)))

### Plane Shift Joint Test (Realtime)
- Done: **5/5**
- Elapsed: **8093.1 s**

| Shift (mm) | Status | nfev~ | Ray RMSE (mm) | Len RMSE (mm) | Last update (s ago) | Error |
|---:|:---|---:|---:|---:|---:|:---|
| -5.0 | failed | 740 | 1.671083 | 0.676840 | 7030.7 | TypeError: _set_status() got multiple va... |
| -2.0 | failed | 630 | 1.616039 | 0.799694 | 5658.3 | TypeError: _set_status() got multiple va... |
| +0.0 | failed | 660 | 1.642280 | 0.724591 | 4300.4 | TypeError: _set_status() got multiple va... |
| +2.0 | failed | 740 | 1.674160 | 0.668414 | 2160.9 | TypeError: _set_status() got multiple va... |
| +5.0 | failed | 740 | 1.693519 | 0.610845 | 0.1 | TypeError: _set_status() got multiple va... |

### Plane Shift Joint Test (Completed)

**Failed shifts**
- -5.0: TypeError: _set_status() got multiple values for argument 'shift_mm'
- -2.0: TypeError: _set_status() got multiple values for argument 'shift_mm'
- +0.0: TypeError: _set_status() got multiple values for argument 'shift_mm'
- +2.0: TypeError: _set_status() got multiple values for argument 'shift_mm'
- +5.0: TypeError: _set_status() got multiple values for argument 'shift_mm'

Optimize both camera and points, using SBA

In [7]:
import os
import re
import csv
import glob
import copy
import time
import numpy as np
import cv2
from scipy.optimize import least_squares
from scipy.sparse import lil_matrix

from modules.camera_calibration.wand_calibration.refractive_geometry import (
    build_pinplate_rays_cpp_batch, point_to_ray_dist, update_normal_tangent, camera_center
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import CppCameraFactory, CppSyncAdapter


# =========================
# Inputs
# =========================
init_cam_dir = r"H:\20260210\T0\Synthetic_test\camFile_joint"
obs_csv      = r"H:\20260210\T0\synthetic_wand_points.csv"

MAX_FRAMES   = 0           # 0=all
WAND_LEN_MM  = 10.0
IMG_SIZE     = (800, 1280)

# 优化参数
MAX_NFEV     = 100
LOSS         = "linear"
FTOL = 1e-7
XTOL = None
GTOL = 1e-7


# =========================
# Data loaders
# =========================
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and (not s.startswith("#")):
            return s, j
        j += 1
    return None, j

def _to_floats(s):
    toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
    return [float(t) for t in toks]

def parse_cam_file(path):
    d = {}
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            K = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)
            d["f"] = float(K[0,0]); d["cx"] = float(K[0,2]); d["cy"] = float(K[1,2])

        elif s.startswith("# Distortion Coefficients"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)
            d["k1"] = rr[0] if len(rr)>0 else 0.0
            d["k2"] = rr[1] if len(rr)>1 else 0.0

        elif s.startswith("# Rotation Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)

        elif s.startswith("# Translation Vector"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane reference point" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane normal" in s:
            row, _ = _next_data(lines, i)
            n = np.array(_to_floats(row), dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)  # obj,win,air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = _to_floats(row)[0]

        elif s.startswith("# WINDOW_ID="):
            d["wid_meta"] = int(s.split("=", 1)[1])

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()
    return d

def load_cam_set(cam_dir):
    cam_params, cam_to_window = {}, {}
    window_planes, window_media = {}, {}

    cam_files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
    if not cam_files:
        raise RuntimeError(f"No cam*.txt in {cam_dir}")

    for path in cam_files:
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array([
            d["rvec"][0], d["rvec"][1], d["rvec"][2],
            d["tvec"][0], d["tvec"][1], d["tvec"][2],
            d["f"], d["cx"], d["cy"], d.get("k1",0.0), d.get("k2",0.0)
        ], dtype=np.float64)

        wid = int(d["wid_meta"]) if "wid_meta" in d else (0 if cid <= 4 else 1)
        cam_to_window[cid] = wid

        if wid not in window_planes:
            # file stores farthest interface; optimizer uses closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            window_planes[wid] = {
                "plane_pt": np.array(p_close, dtype=np.float64),
                "plane_n": np.array(d["plane_n"], dtype=np.float64),
                "initialized": True
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"]
            }
    return cam_params, cam_to_window, window_planes, window_media

def load_obs_dataset(csv_path, max_frames=0):
    obsA, obsB, frames = {}, {}, set()
    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st  = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {
        "obsA": obsA, "obsB": obsB, "frames": frames
    }


# =========================
# Build initial state
# =========================
cam_init, cam_to_window, window_planes_init, window_media = load_cam_set(init_cam_dir)
dataset = load_obs_dataset(obs_csv, MAX_FRAMES)

cam_ids = sorted(cam_init.keys())
win_ids = sorted(window_planes_init.keys())
fids = [fid for fid in dataset["frames"] if (fid in dataset["obsA"] and fid in dataset["obsB"])]
print(f"cams={len(cam_ids)}, windows={len(win_ids)}, frames={len(fids)}")

class _Base: pass
base = _Base()
base.image_size = IMG_SIZE
base.dist_coeff_num = 0

cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_init,
    window_media=window_media,
    cam_to_window=cam_to_window,
    window_planes=window_planes_init
)

# 固定一个参考相机，去除全局 gauge
ref_cam = cam_ids[0]
opt_cam_ids = [c for c in cam_ids if c != ref_cam]
print("reference cam fixed:", ref_cam, "optimized cams:", opt_cam_ids)

# 预构建观测列表
obs_rows = []
for fid in fids:
    for cid, uv in dataset["obsA"].get(fid, {}).items():
        if cid in cam_ids:
            obs_rows.append((fid, cid, 0, uv))  # endpoint A=0
    for cid, uv in dataset["obsB"].get(fid, {}).items():
        if cid in cam_ids:
            obs_rows.append((fid, cid, 1, uv))  # endpoint B=1

# 点索引（每帧 A/B）
fid_to_idx = {fid:i for i,fid in enumerate(fids)}
nF = len(fids)


# =========================
# Initial 3D points by triangulation (one-time init)
# =========================
def triangulate_init_points():
    XA = np.zeros((nF,3), dtype=float)
    XB = np.zeros((nF,3), dtype=float)
    validA = np.zeros(nF, dtype=bool)
    validB = np.zeros(nF, dtype=bool)

    def tri_endpoint(obs_key, endpoint_flag, Xout, valid):
        per_cam = {}
        for i, fid in enumerate(fids):
            obs_f = dataset[obs_key].get(fid, {})
            for cid, uv in obs_f.items():
                if cid in cams_cpp:
                    per_cam.setdefault(cid, []).append((i, fid, uv))

        rays_by_frame = {i: [] for i in range(nF)}
        for cid, items in per_cam.items():
            wid = cam_to_window[cid]
            uv_list = [uv for (_,_,uv) in items]
            meta = [{"cam_id":cid,"window_id":wid,"frame_id":fid,"endpoint":"A" if endpoint_flag==0 else "B"} for (_,fid,_) in items]
            rays = build_pinplate_rays_cpp_batch(cams_cpp[cid], uv_list, meta_list=meta)
            for (i,_,_), r in zip(items, rays):
                if r.valid:
                    rays_by_frame[i].append(r)

        for i in range(nF):
            rays = rays_by_frame[i]
            if len(rays) >= 2:
                # simple line-line LS triangulation
                # minimize sum ||(I-dd^T)(X-o)||^2
                A = np.zeros((3,3)); b = np.zeros(3)
                for r in rays:
                    d = r.d / (np.linalg.norm(r.d) + 1e-12)
                    o = r.o
                    P = np.eye(3) - np.outer(d,d)
                    A += P
                    b += P @ o
                try:
                    X = np.linalg.solve(A + 1e-9*np.eye(3), b)
                    Xout[i,:] = X
                    valid[i] = True
                except np.linalg.LinAlgError:
                    pass

    tri_endpoint("obsA", 0, XA, validA)
    tri_endpoint("obsB", 1, XB, validB)

    # fallback: invalid点用零或A/B互补
    for i in range(nF):
        if not validA[i] and validB[i]:
            XA[i] = XB[i] + np.array([0,0,-WAND_LEN_MM])
            validA[i] = True
        if not validB[i] and validA[i]:
            XB[i] = XA[i] + np.array([0,0, WAND_LEN_MM])
            validB[i] = True
        if not validA[i] and not validB[i]:
            XA[i] = np.array([0,0,0.0])
            XB[i] = np.array([0,0,WAND_LEN_MM])
            validA[i] = validB[i] = True

    return XA, XB

XA0, XB0 = triangulate_init_points()


# =========================
# Parameter packing
# =========================
cam_dim = 6 * len(opt_cam_ids)
# 每window: plane_pt(3) + tangent-normal delta (a,b)=2
win_dim = 5 * len(win_ids)
pts_dim = 6 * nF
n_params = cam_dim + win_dim + pts_dim

cam_off = 0
win_off = cam_off + cam_dim
pts_off = win_off + win_dim

# 保存固定相机内参
cam_fixed_intr = {cid: cam_init[cid][6:11].copy() for cid in cam_ids}
cam_r0 = {cid: cam_init[cid][0:3].copy() for cid in cam_ids}
cam_t0 = {cid: cam_init[cid][3:6].copy() for cid in cam_ids}

# 平面初值
pl_pt0 = {wid: window_planes_init[wid]["plane_pt"].copy() for wid in win_ids}
pl_n0  = {wid: window_planes_init[wid]["plane_n"].copy()  for wid in win_ids}

# 每窗口 anchor（用于 d-shift 更稳定）
pl_anchor = {}
for wid in win_ids:
    centers = []
    for cid, w in cam_to_window.items():
        if w == wid:
            p = cam_init[cid]
            R,_ = cv2.Rodrigues(p[:3]); C = camera_center(R, p[3:6])
            centers.append(C)
    if centers:
        pl_anchor[wid] = np.mean(np.asarray(centers), axis=0)
    else:
        pl_anchor[wid] = pl_pt0[wid].copy()

def pack_x0():
    x = np.zeros(n_params, dtype=float)

    # cams (excluding reference)
    k = cam_off
    for cid in opt_cam_ids:
        x[k:k+3] = cam_r0[cid]
        x[k+3:k+6] = cam_t0[cid]
        k += 6

    # planes
    k = win_off
    for wid in win_ids:
        # optimize plane_pt directly + (a,b)=0 init
        x[k:k+3] = pl_pt0[wid]
        x[k+3] = 0.0
        x[k+4] = 0.0
        k += 5

    # points
    k = pts_off
    for i in range(nF):
        x[k:k+3] = XA0[i]
        x[k+3:k+6] = XB0[i]
        k += 6

    return x

def unpack_params(x):
    # cams
    cam_params = {}
    for cid in cam_ids:
        p = cam_init[cid].copy()
        if cid == ref_cam:
            # reference cam fixed
            p[:3] = cam_r0[cid]
            p[3:6] = cam_t0[cid]
        else:
            j = opt_cam_ids.index(cid)
            base = cam_off + 6*j
            p[:3] = x[base:base+3]
            p[3:6] = x[base+3:base+6]
        p[6:11] = cam_fixed_intr[cid]
        cam_params[cid] = p

    # planes
    planes = {}
    for j, wid in enumerate(win_ids):
        base = win_off + 5*j
        pt = x[base:base+3]
        a = x[base+3]
        b = x[base+4]
        n = update_normal_tangent(pl_n0[wid], a, b)
        planes[wid] = {
            "plane_pt": pt,
            "plane_n": n,
            "initialized": True
        }

    # points
    XA = np.zeros((nF,3), dtype=float)
    XB = np.zeros((nF,3), dtype=float)
    for i in range(nF):
        base = pts_off + 6*i
        XA[i,:] = x[base:base+3]
        XB[i,:] = x[base+3:base+6]

    return cam_params, planes, XA, XB


# =========================
# Jacobian sparsity (SBA style)
# =========================
# residuals: one per observation + one per frame wand length
n_obs = len(obs_rows)
m = n_obs + nF
n = n_params

Jsp = lil_matrix((m, n), dtype=np.int8)

# obs residual: depends on camera(6, if not reference) + window plane(5) + point(3)
for r_idx, (fid, cid, endpoint, uv) in enumerate(obs_rows):
    # camera vars
    if cid != ref_cam:
        j = opt_cam_ids.index(cid)
        cbase = cam_off + 6*j
        Jsp[r_idx, cbase:cbase+6] = 1

    # window vars
    wid = cam_to_window[cid]
    wj = win_ids.index(wid)
    wbase = win_off + 5*wj
    Jsp[r_idx, wbase:wbase+5] = 1

    # point vars
    i = fid_to_idx[fid]
    pbase = pts_off + 6*i
    if endpoint == 0:
        Jsp[r_idx, pbase:pbase+3] = 1
    else:
        Jsp[r_idx, pbase+3:pbase+6] = 1

# wand residual: depends on XA/XB of this frame
for i, fid in enumerate(fids):
    r_idx = n_obs + i
    pbase = pts_off + 6*i
    Jsp[r_idx, pbase:pbase+6] = 1

Jsp = Jsp.tocsr()
print("jac_sparsity shape:", Jsp.shape, "nnz:", Jsp.nnz)


# =========================
# Residual function
# =========================
# 归一化
# 你当前配置改为1px；这里按几何估计sigma_ray
avg_f = np.mean([cam_init[c][6] for c in cam_ids])
# 用初始相机中心到原点的大致距离估计尺度
z_scale = []
for c in cam_ids:
    p = cam_init[c]
    R,_ = cv2.Rodrigues(p[:3]); C = camera_center(R, p[3:6])
    z_scale.append(abs(C[2]) + 1e-6)
avg_z = np.mean(z_scale)
sigma_ray = 1.0 * (avg_z / avg_f)  # 1px -> mm
sigma_wand = 0.02 * WAND_LEN_MM
print(f"sigma_ray={sigma_ray:.6f} mm, sigma_wand={sigma_wand:.6f} mm")

call_counter = {"k": 0, "t0": time.time()}

def residual_fun(x):
    cam_params, planes, XA, XB = unpack_params(x)

    # sync C++ camera objects with current cam+plane
    for cid in cam_ids:
        kw = CppSyncAdapter.build_update_kwargs(
            cam_params=cam_params,
            window_planes=planes,
            window_media=window_media,
            cam_to_window=cam_to_window,
            cam_id=cid
        )
        CppSyncAdapter.apply(cams_cpp, cid, kw)

    # batch build rays per camera for A/B
    per_cam_A = {}
    per_cam_B = {}
    for (fid, cid, endpoint, uv) in obs_rows:
        if endpoint == 0:
            per_cam_A.setdefault(cid, []).append((fid, uv))
        else:
            per_cam_B.setdefault(cid, []).append((fid, uv))

    ray_lookup_A = {}
    for cid, items in per_cam_A.items():
        wid = cam_to_window[cid]
        uv_list = [uv for (_,uv) in items]
        meta = [{"cam_id":cid, "window_id":wid, "frame_id":fid, "endpoint":"A"} for (fid,_) in items]
        rays = build_pinplate_rays_cpp_batch(cams_cpp[cid], uv_list, meta_list=meta)
        for (fid,_), r in zip(items, rays):
            ray_lookup_A[(fid,cid)] = r

    ray_lookup_B = {}
    for cid, items in per_cam_B.items():
        wid = cam_to_window[cid]
        uv_list = [uv for (_,uv) in items]
        meta = [{"cam_id":cid, "window_id":wid, "frame_id":fid, "endpoint":"B"} for (fid,_) in items]
        rays = build_pinplate_rays_cpp_batch(cams_cpp[cid], uv_list, meta_list=meta)
        for (fid,_), r in zip(items, rays):
            ray_lookup_B[(fid,cid)] = r

    res = np.zeros(m, dtype=float)

    S_ray = 0.0
    N_ray = 0

    # observation residuals
    for ridx, (fid, cid, endpoint, uv) in enumerate(obs_rows):
        i = fid_to_idx[fid]
        X = XA[i] if endpoint == 0 else XB[i]
        r = ray_lookup_A.get((fid,cid)) if endpoint == 0 else ray_lookup_B.get((fid,cid))
        if (r is not None) and r.valid:
            d = point_to_ray_dist(X, r.o, r.d)
            res[ridx] = d / sigma_ray
            S_ray += d*d
            N_ray += 1
        else:
            # invalid ray penalty
            res[ridx] = 100.0 / sigma_ray

    # wand length residuals
    S_len = 0.0
    for i, fid in enumerate(fids):
        L = np.linalg.norm(XB[i] - XA[i])
        dl = L - WAND_LEN_MM
        res[n_obs + i] = dl / sigma_wand
        S_len += dl*dl

    call_counter["k"] += 1
    if call_counter["k"] % 10 == 0:
        ray_rmse = np.sqrt(S_ray / max(1, N_ray))
        len_rmse = np.sqrt(S_len / max(1, nF))
        elapsed = time.time() - call_counter["t0"]
        print(f"[fve~{call_counter['k']:4d}] ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | elapsed={elapsed:.1f}s")

    return res


# =========================
# Run SBA
# =========================
x0 = pack_x0()

print("Start SBA...")
t_start = time.time()
res = least_squares(
    residual_fun,
    x0,
    method="trf",
    jac_sparsity=Jsp,
    loss=LOSS,
    ftol=FTOL,
    xtol=XTOL,
    gtol=GTOL,
    max_nfev=MAX_NFEV,
    verbose=0,
)
t_used = time.time() - t_start

print("\n=== SBA Done ===")
print("status:", res.status)
print("message:", res.message)
print("nfev:", res.nfev)
print("time(s):", round(t_used, 2))

cam_opt, plane_opt, XA_opt, XB_opt = unpack_params(res.x)

# quick post metrics
r_final = residual_fun(res.x)
cost = 0.5 * np.sum(r_final**2)
print("final cost:", cost)

# 你如果想看最终ray/len，可从 residual_fun 中再提一次，或者在这里复算一版统计

cams=4, windows=2, frames=2500

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
reference cam fixed: 0 optimized cams: [1, 2, 3]
jac_sparsity shape: (22500, 15028) nnz: 265000
sigma_ray=0.010261 mm, sigma_wand=0.200000 mm
Start SBA...
[fve~  10] ray=0.092705 mm | len=0.243132 mm | elapsed=5.0s
[fve~  20] ray=0.077318 mm | len=0.266043 mm | elapsed=10.0s
[fve~  30] ray=0.077318 mm | len=0.266043 mm | elapsed=15.0s
[fve~  40] ray=0.057624 mm | len=0.272857 mm | elapsed=20.0s
[fve~  50] ray=0.057624 mm | len=0.272857 mm | elapsed=25.0s
[fve~  60] ray=0.053122 mm | len=0.316978 mm | elapsed=30.0s
[fve~  70] ray=0.053121 mm | len=0.316978 mm | elapsed=34.9s
[fve~  80] ray=0.034577 mm | len=0.313114 mm | elapsed=39.9s
[fve~  90] ray=0.034577 mm | len=0.313114 mm | elapsed=44.9s
[fve~ 100] ray=0.029376 mm | len=0.314735 mm | elapsed=49.8s
[fve~ 110] ray=0.025007 mm | len=0.308888 mm | elapsed=54.8s
[fve~ 120] ray=0.025007 mm | len=0.308888 mm | elapsed=59.6s
[fve~ 130] ray=0.022576 mm | len=0.308448 mm | elapsed=64.6s
[fve~ 140] ray=0.022576 mm | len=0.308448 mm | elapsed=69.4s
[fve~ 150] ray=0.018048 mm | len=0.307601 mm | elapsed=74.3s
[fve~ 160] ray=0.018048 mm | len=0.307601 mm | elapsed=79.3s
[fve~ 170] ray=0.016200 mm | len=0.307008 mm | elapsed=84.2s
[fve~ 180] ray=0.016201 mm | len=0.307008 mm | elapsed=89.1s
[fve~ 190] ray=0.015727 mm | len=0.306432 mm | elapsed=94.1s
[fve~ 200] ray=0.015798 mm | len=0.306407 mm | elapsed=99.0s
[fve~ 210] ray=0.014548 mm | len=0.306426 mm | elapsed=104.0s
[fve~ 220] ray=0.014206 mm | len=0.306426 mm | elapsed=108.9s
[fve~ 230] ray=0.014206 mm | len=0.306426 mm | elapsed=113.9s
[fve~ 240] ray=0.014085 mm | len=0.306426 mm | elapsed=118.8s
[fve~ 250] ray=0.014085 mm | len=0.306426 mm | elapsed=123.8s
[fve~ 260] ray=0.014071 mm | len=0.306426 mm | elapsed=128.7s
[fve~ 270] ray=0.014071 mm | len=0.306426 mm | elapsed=133.6s
[fve~ 280] ray=0.013905 mm | len=0.306426 mm | elapsed=138.6s
[fve~ 290] ray=0.013905 mm | len=0.306426 mm | elapsed=143.5s
[fve~ 300] ray=0.013899 mm | len=0.306426 mm | elapsed=148.5s
[fve~ 310] ray=0.013863 mm | len=0.306426 mm | elapsed=153.5s
[fve~ 320] ray=0.013863 mm | len=0.306426 mm | elapsed=158.5s
[fve~ 330] ray=0.013854 mm | len=0.306426 mm | elapsed=163.6s
[fve~ 340] ray=0.013854 mm | len=0.306426 mm | elapsed=168.6s
[fve~ 350] ray=0.013853 mm | len=0.306426 mm | elapsed=173.7s
[fve~ 360] ray=0.013853 mm | len=0.306426 mm | elapsed=178.7s
[fve~ 370] ray=0.013851 mm | len=0.306426 mm | elapsed=183.7s
[fve~ 380] ray=0.013851 mm | len=0.306426 mm | elapsed=188.5s
[fve~ 390] ray=0.013851 mm | len=0.306426 mm | elapsed=193.5s
[fve~ 400] ray=0.013851 mm | len=0.306426 mm | elapsed=198.5s
[fve~ 410] ray=0.013850 mm | len=0.306426 mm | elapsed=203.6s
[fve~ 420] ray=0.013850 mm | len=0.306426 mm | elapsed=208.8s
[fve~ 430] ray=0.013850 mm | len=0.306426 mm | elapsed=214.0s
[fve~ 440] ray=0.013850 mm | len=0.306426 mm | elapsed=219.2s
[fve~ 450] ray=0.013850 mm | len=0.306426 mm | elapsed=224.4s
[fve~ 460] ray=0.013849 mm | len=0.306426 mm | elapsed=229.5s
[fve~ 470] ray=0.013849 mm | len=0.306426 mm | elapsed=234.6s
[fve~ 480] ray=0.013849 mm | len=0.306426 mm | elapsed=239.7s
[fve~ 490] ray=0.013849 mm | len=0.306426 mm | elapsed=244.7s
[fve~ 500] ray=0.013849 mm | len=0.306426 mm | elapsed=249.7s
[fve~ 510] ray=0.013848 mm | len=0.306426 mm | elapsed=254.8s
[fve~ 520] ray=0.013848 mm | len=0.306426 mm | elapsed=260.0s
[fve~ 530] ray=0.013847 mm | len=0.306426 mm | elapsed=265.2s
[fve~ 540] ray=0.013847 mm | len=0.306426 mm | elapsed=270.4s
[fve~ 550] ray=0.013846 mm | len=0.306426 mm | elapsed=275.4s
[fve~ 560] ray=0.013846 mm | len=0.306426 mm | elapsed=280.4s
[fve~ 570] ray=0.013845 mm | len=0.306426 mm | elapsed=285.5s
[fve~ 580] ray=0.013845 mm | len=0.306426 mm | elapsed=290.5s
[fve~ 590] ray=0.013845 mm | len=0.306425 mm | elapsed=295.5s
[fve~ 600] ray=0.013844 mm | len=0.306425 mm | elapsed=300.6s
[fve~ 610] ray=0.013844 mm | len=0.306425 mm | elapsed=305.6s
[fve~ 620] ray=0.013842 mm | len=0.306424 mm | elapsed=310.6s
[fve~ 630] ray=0.013842 mm | len=0.306424 mm | elapsed=315.6s
[fve~ 640] ray=0.013839 mm | len=0.306423 mm | elapsed=320.6s
[fve~ 650] ray=0.013839 mm | len=0.306423 mm | elapsed=325.6s
[fve~ 660] ray=0.013832 mm | len=0.306420 mm | elapsed=330.7s
[fve~ 670] ray=0.013832 mm | len=0.306420 mm | elapsed=335.8s
[fve~ 680] ray=0.013819 mm | len=0.306414 mm | elapsed=340.9s
[fve~ 690] ray=0.013796 mm | len=0.306401 mm | elapsed=346.2s
[fve~ 700] ray=0.013796 mm | len=0.306401 mm | elapsed=351.3s

KeyboardInterrupt:

In [8]:
import os
import re
import csv
import glob
import time
import numpy as np
import cv2

from scipy.optimize import least_squares
from scipy.sparse import lil_matrix

from modules.camera_calibration.wand_calibration.refractive_geometry import (
    build_pinplate_rays_cpp_batch,
    point_to_ray_dist,
    update_normal_tangent,
    camera_center,
    align_world_y_to_plane_intersection,
)
from modules.camera_calibration.wand_calibration.refraction_wand_calibrator import (
    CppCameraFactory, CppSyncAdapter
)

# =========================
# Inputs
# =========================
init_cam_dir = r"H:\20260210\T0\Synthetic_test\camFile_joint"
obs_csv      = r"H:\20260210\T0\synthetic_wand_points.csv"

MAX_FRAMES  = 0          # 0=all
WAND_LEN_MM = 10.0
IMG_SIZE    = (800, 1280)

MAX_NFEV = 150
FTOL = 1e-7
XTOL = None     # 你要求避免 xtol 早退
GTOL = 1e-6
LOSS = "linear"


# =========================
# Loaders
# =========================
def _next_data(lines, i):
    j = i + 1
    while j < len(lines):
        s = lines[j].strip()
        if s and (not s.startswith("#")):
            return s, j
        j += 1
    return None, j

def _to_floats(s):
    toks = [t for t in re.split(r"[\s,]+", s.strip()) if t]
    return [float(t) for t in toks]

def parse_cam_file(path):
    d = {}
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        s = line.strip()

        if s.startswith("# Camera Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            K = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)
            d["f"] = float(K[0, 0]); d["cx"] = float(K[0, 2]); d["cy"] = float(K[1, 2])

        elif s.startswith("# Distortion Coefficients"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)
            d["k1"] = rr[0] if len(rr) > 0 else 0.0
            d["k2"] = rr[1] if len(rr) > 1 else 0.0

        elif s.startswith("# Rotation Matrix"):
            r1, _ = _next_data(lines, i + 0)
            r2, _ = _next_data(lines, i + 1)
            r3, _ = _next_data(lines, i + 2)
            d["R"] = np.array([_to_floats(r1), _to_floats(r2), _to_floats(r3)], dtype=float)

        elif s.startswith("# Translation Vector"):
            row, _ = _next_data(lines, i)
            d["tvec"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane reference point" in s:
            row, _ = _next_data(lines, i)
            d["plane_far"] = np.array(_to_floats(row), dtype=float)

        elif "Refractive plane normal" in s:
            row, _ = _next_data(lines, i)
            n = np.array(_to_floats(row), dtype=float)
            d["plane_n"] = n / (np.linalg.norm(n) + 1e-12)

        elif s.startswith("# n_plate"):
            row, _ = _next_data(lines, i)
            rr = _to_floats(row)  # object, glass, air
            d["n3"], d["n2"], d["n1"] = rr[0], rr[1], rr[2]

        elif s.startswith("# w_array"):
            row, _ = _next_data(lines, i)
            d["thickness"] = _to_floats(row)[0]

        elif s.startswith("# WINDOW_ID="):
            d["wid_meta"] = int(s.split("=", 1)[1])

    rvec, _ = cv2.Rodrigues(d["R"])
    d["rvec"] = rvec.flatten()
    return d

def load_cam_set(cam_dir):
    cam_params, cam_to_window = {}, {}
    window_planes, window_media = {}, {}

    cam_files = sorted(glob.glob(os.path.join(cam_dir, "cam*.txt")))
    if not cam_files:
        raise RuntimeError(f"No cam*.txt found in {cam_dir}")

    for path in cam_files:
        cid = int(re.findall(r"cam(\d+)", os.path.basename(path))[0])
        d = parse_cam_file(path)

        cam_params[cid] = np.array([
            d["rvec"][0], d["rvec"][1], d["rvec"][2],
            d["tvec"][0], d["tvec"][1], d["tvec"][2],
            d["f"], d["cx"], d["cy"], d.get("k1", 0.0), d.get("k2", 0.0)
        ], dtype=np.float64)

        wid = int(d["wid_meta"]) if "wid_meta" in d else (0 if cid <= 4 else 1)
        cam_to_window[cid] = wid

        if wid not in window_planes:
            # file stores farthest; optimizer uses closest
            p_close = d["plane_far"] - d["plane_n"] * d["thickness"]
            window_planes[wid] = {
                "plane_pt": np.array(p_close, dtype=np.float64),
                "plane_n": np.array(d["plane_n"], dtype=np.float64),
                "initialized": True
            }
            window_media[wid] = {
                "n1": d["n1"], "n2": d["n2"], "n3": d["n3"],
                "thickness": d["thickness"]
            }

    return cam_params, cam_to_window, window_planes, window_media

def load_obs_dataset(csv_path, max_frames=0):
    obsA, obsB, frames = {}, {}, set()
    with open(csv_path, "r", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        for r in rd:
            fid = int(r["Frame"])
            cid = int(r["Camera"])
            st = r["Status"]
            pidx = int(r["PointIdx"])
            uv = np.array([float(r["X"]), float(r["Y"])], dtype=float)

            frames.add(fid)
            if ("Small" in st) or (pidx == 0):
                obsA.setdefault(fid, {})[cid] = uv
            elif ("Large" in st) or (pidx == 1):
                obsB.setdefault(fid, {})[cid] = uv

    frames = sorted(frames)
    if max_frames and max_frames > 0:
        frames = frames[:max_frames]

    return {"obsA": obsA, "obsB": obsB, "frames": frames}


# =========================
# Initial build
# =========================
cam_init, cam_to_window, window_planes_init, window_media = load_cam_set(init_cam_dir)
dataset = load_obs_dataset(obs_csv, MAX_FRAMES)

cam_ids = sorted(cam_init.keys())
win_ids = sorted(window_planes_init.keys())
fids = [fid for fid in dataset["frames"] if fid in dataset["obsA"] and fid in dataset["obsB"]]
fid_to_idx = {fid:i for i, fid in enumerate(fids)}
nF = len(fids)

print(f"cams={len(cam_ids)}, windows={len(win_ids)}, frames={nF}")

class _Base: pass
base = _Base()
base.image_size = IMG_SIZE
base.dist_coeff_num = 0

cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_init,
    window_media=window_media,
    cam_to_window=cam_to_window,
    window_planes=window_planes_init
)

# gauge fix: keep one reference cam fixed
ref_cam = cam_ids[0]
opt_cam_ids = [c for c in cam_ids if c != ref_cam]
print("reference cam fixed:", ref_cam)

# flatten observations
obs_rows = []
for fid in fids:
    for cid, uv in dataset["obsA"].get(fid, {}).items():
        if cid in cam_ids:
            obs_rows.append((fid, cid, 0, uv))
    for cid, uv in dataset["obsB"].get(fid, {}).items():
        if cid in cam_ids:
            obs_rows.append((fid, cid, 1, uv))
n_obs = len(obs_rows)
print("observations:", n_obs)

# =========================
# One-time triangulation init
# =========================
def triangulate_init(cams_cpp_local, cam_params_local, planes_local):
    XA = np.zeros((nF, 3), dtype=float)
    XB = np.zeros((nF, 3), dtype=float)

    def tri_endpoint(obs_key, endpoint_flag, Xout):
        per_cam = {}
        for i, fid in enumerate(fids):
            obs_f = dataset[obs_key].get(fid, {})
            for cid, uv in obs_f.items():
                if cid in cams_cpp_local:
                    per_cam.setdefault(cid, []).append((i, fid, uv))

        rays_by_i = {i: [] for i in range(nF)}
        for cid, items in per_cam.items():
            wid = cam_to_window[cid]
            uv_list = [uv for _, _, uv in items]
            meta = [{"cam_id":cid, "window_id":wid, "frame_id":fid, "endpoint":"A" if endpoint_flag==0 else "B"} for _, fid, _ in items]
            rays = build_pinplate_rays_cpp_batch(cams_cpp_local[cid], uv_list, meta_list=meta)
            for (i, _, _), r in zip(items, rays):
                if r.valid:
                    rays_by_i[i].append(r)

        for i in range(nF):
            rays = rays_by_i[i]
            if len(rays) < 2:
                continue
            A = np.zeros((3,3)); b = np.zeros(3)
            for r in rays:
                d = r.d / (np.linalg.norm(r.d) + 1e-12)
                o = r.o
                P = np.eye(3) - np.outer(d, d)
                A += P
                b += P @ o
            Xout[i] = np.linalg.solve(A + 1e-9*np.eye(3), b)

    tri_endpoint("obsA", 0, XA)
    tri_endpoint("obsB", 1, XB)

    for i in range(nF):
        if not np.all(np.isfinite(XA[i])):
            XA[i] = np.array([0,0,0], dtype=float)
        if not np.all(np.isfinite(XB[i])):
            XB[i] = XA[i] + np.array([0,0,WAND_LEN_MM], dtype=float)

    return XA, XB

XA0, XB0 = triangulate_init(cams_cpp, cam_init, window_planes_init)

# =========================
# B case: rotate-align BEFORE optimization
# =========================
pts_for_align = np.vstack([XA0, XB0])  # (2*nF, 3)
cam_aligned, planes_aligned, pts_aligned, R_align, t_shift = align_world_y_to_plane_intersection(
    window_planes_init,
    cam_init,
    points_3d=pts_for_align
)

# normalize plane array types
planes_aligned = {
    int(w): {
        **pl,
        "plane_pt": np.asarray(pl["plane_pt"], dtype=np.float64),
        "plane_n": np.asarray(pl["plane_n"], dtype=np.float64),
        "initialized": True
    }
    for w, pl in planes_aligned.items()
}
cam_aligned = {int(c): np.asarray(p, dtype=np.float64) for c, p in cam_aligned.items()}

# reuse aligned points as point init if available
if (pts_aligned is not None) and (len(pts_aligned) == 2*nF):
    pts_aligned = np.asarray(pts_aligned, dtype=float)
    XA0 = pts_aligned[:nF].copy()
    XB0 = pts_aligned[nF:].copy()

# rebuild C++ cams with aligned params
cams_cpp = CppCameraFactory.init_cams_cpp_in_memory(
    base=base,
    cam_params=cam_aligned,
    window_media=window_media,
    cam_to_window=cam_to_window,
    window_planes=planes_aligned
)

print("[B] alignment applied before SBA")
print("R_align=\n", R_align)
print("t_shift=", t_shift)

# =========================
# Parameter layout
# =========================
# optimize cam extrinsics + planes + points
# keep intrinsics fixed
cam_intr_fixed = {cid: cam_aligned[cid][6:11].copy() for cid in cam_ids}
cam_r0 = {cid: cam_aligned[cid][:3].copy() for cid in cam_ids}
cam_t0 = {cid: cam_aligned[cid][3:6].copy() for cid in cam_ids}
pl_n0  = {wid: planes_aligned[wid]["plane_n"].copy() for wid in win_ids}
pl_pt0 = {wid: planes_aligned[wid]["plane_pt"].copy() for wid in win_ids}

cam_dim = 6 * len(opt_cam_ids)
win_dim = 5 * len(win_ids)    # plane_pt(3) + a,b(2)
pts_dim = 6 * nF              # XA(3)+XB(3)

off_cam = 0
off_win = off_cam + cam_dim
off_pts = off_win + win_dim
n_params = off_pts + pts_dim

# residuals: obs + wand length (NO X prior)
off_obs = 0
off_len = off_obs + n_obs
m_res = off_len + nF

print("n_params:", n_params, "n_residuals:", m_res)

def pack_x0():
    x = np.zeros(n_params, dtype=float)
    k = off_cam
    for cid in opt_cam_ids:
        x[k:k+3] = cam_r0[cid]
        x[k+3:k+6] = cam_t0[cid]
        k += 6

    k = off_win
    for wid in win_ids:
        x[k:k+3] = pl_pt0[wid]
        x[k+3] = 0.0
        x[k+4] = 0.0
        k += 5

    k = off_pts
    for i in range(nF):
        x[k:k+3] = XA0[i]
        x[k+3:k+6] = XB0[i]
        k += 6

    return x

def unpack_x(x):
    # cameras
    cams = {}
    for cid in cam_ids:
        p = cam_aligned[cid].copy()
        if cid == ref_cam:
            p[:3] = cam_r0[cid]
            p[3:6] = cam_t0[cid]
        else:
            j = opt_cam_ids.index(cid)
            b = off_cam + 6*j
            p[:3] = x[b:b+3]
            p[3:6] = x[b+3:b+6]
        p[6:11] = cam_intr_fixed[cid]
        cams[cid] = p

    # planes
    planes = {}
    for j, wid in enumerate(win_ids):
        b = off_win + 5*j
        pt = x[b:b+3]
        a = x[b+3]
        c = x[b+4]
        n = update_normal_tangent(pl_n0[wid], a, c)
        planes[wid] = {
            "plane_pt": pt,
            "plane_n": n,
            "initialized": True
        }

    # points
    XA = np.zeros((nF,3), dtype=float)
    XB = np.zeros((nF,3), dtype=float)
    for i in range(nF):
        b = off_pts + 6*i
        XA[i] = x[b:b+3]
        XB[i] = x[b+3:b+6]

    return cams, planes, XA, XB

# =========================
# Jacobian sparsity
# =========================
Jsp = lil_matrix((m_res, n_params), dtype=np.int8)

# obs rows: depend on cam + plane + point
for ridx, (fid, cid, endpoint, uv) in enumerate(obs_rows):
    if cid != ref_cam:
        j = opt_cam_ids.index(cid)
        cb = off_cam + 6*j
        Jsp[ridx, cb:cb+6] = 1

    wid = cam_to_window[cid]
    jw = win_ids.index(wid)
    wb = off_win + 5*jw
    Jsp[ridx, wb:wb+5] = 1

    i = fid_to_idx[fid]
    pb = off_pts + 6*i
    if endpoint == 0:
        Jsp[ridx, pb:pb+3] = 1
    else:
        Jsp[ridx, pb+3:pb+6] = 1

# length rows: depend on XA/XB of frame
for i in range(nF):
    ridx = off_len + i
    pb = off_pts + 6*i
    Jsp[ridx, pb:pb+6] = 1

Jsp = Jsp.tocsr()
print("jac_sparsity:", Jsp.shape, "nnz:", Jsp.nnz)

# =========================
# Scales
# =========================
avg_f = np.mean([cam_aligned[c][6] for c in cam_ids])
z_guess = []
for cid in cam_ids:
    p = cam_aligned[cid]
    R, _ = cv2.Rodrigues(p[:3])
    C = camera_center(R, p[3:6])
    z_guess.append(abs(C[2]) + 1e-6)
avg_z = np.mean(z_guess)

sigma_ray = 1.0 * (avg_z / avg_f)     # 1 px -> mm
sigma_wand = 0.02 * WAND_LEN_MM
print(f"sigma_ray={sigma_ray:.6f} mm, sigma_wand={sigma_wand:.6f} mm")

# =========================
# Residual function + progress every 10 fve
# =========================
state = {"fve": 0, "t0": time.time()}

def residual_fun(x):
    cams, planes, XA, XB = unpack_x(x)

    # sync C++ cameras
    for cid in cam_ids:
        kw = CppSyncAdapter.build_update_kwargs(
            cam_params=cams,
            window_planes=planes,
            window_media=window_media,
            cam_to_window=cam_to_window,
            cam_id=cid
        )
        CppSyncAdapter.apply(cams_cpp, cid, kw)

    # batch rays
    perA, perB = {}, {}
    for fid, cid, endpoint, uv in obs_rows:
        if endpoint == 0:
            perA.setdefault(cid, []).append((fid, uv))
        else:
            perB.setdefault(cid, []).append((fid, uv))

    lookupA, lookupB = {}, {}
    for cid, items in perA.items():
        wid = cam_to_window[cid]
        uv_list = [uv for _, uv in items]
        meta = [{"cam_id":cid, "window_id":wid, "frame_id":fid, "endpoint":"A"} for fid, _ in items]
        rays = build_pinplate_rays_cpp_batch(cams_cpp[cid], uv_list, meta_list=meta)
        for (fid, _), r in zip(items, rays):
            lookupA[(fid, cid)] = r

    for cid, items in perB.items():
        wid = cam_to_window[cid]
        uv_list = [uv for _, uv in items]
        meta = [{"cam_id":cid, "window_id":wid, "frame_id":fid, "endpoint":"B"} for fid, _ in items]
        rays = build_pinplate_rays_cpp_batch(cams_cpp[cid], uv_list, meta_list=meta)
        for (fid, _), r in zip(items, rays):
            lookupB[(fid, cid)] = r

    res = np.zeros(m_res, dtype=float)

    S_ray = 0.0
    N_ray = 0
    for ridx, (fid, cid, endpoint, uv) in enumerate(obs_rows):
        i = fid_to_idx[fid]
        X = XA[i] if endpoint == 0 else XB[i]
        r = lookupA.get((fid, cid)) if endpoint == 0 else lookupB.get((fid, cid))
        if (r is not None) and r.valid:
            d = point_to_ray_dist(X, r.o, r.d)
            res[off_obs + ridx] = d / sigma_ray
            S_ray += d*d
            N_ray += 1
        else:
            res[off_obs + ridx] = 100.0 / sigma_ray

    S_len = 0.0
    for i in range(nF):
        dl = np.linalg.norm(XB[i] - XA[i]) - WAND_LEN_MM
        res[off_len + i] = dl / sigma_wand
        S_len += dl*dl

    state["fve"] += 1
    if state["fve"] % 10 == 0:
        ray_rmse = np.sqrt(S_ray / max(1, N_ray))
        len_rmse = np.sqrt(S_len / max(1, nF))
        dt = time.time() - state["t0"]
        print(f"[fve~{state['fve']:4d}] ray={ray_rmse:.6f} mm | len={len_rmse:.6f} mm | elapsed={dt:.1f}s")

    return res


# =========================
# Run SBA (B only)
# =========================
x0 = pack_x0()
print("\nStart SBA (B: pre-rot-align + no X regularization)...")

t0 = time.time()
res = least_squares(
    residual_fun,
    x0,
    method="trf",
    jac_sparsity=Jsp,
    loss=LOSS,
    ftol=FTOL,
    xtol=XTOL,
    gtol=GTOL,
    max_nfev=MAX_NFEV,
    verbose=0
)
dt = time.time() - t0

print("\n=== SBA B Done ===")
print("status :", res.status)
print("message:", res.message)
print("nfev   :", res.nfev)
print("time(s):", round(dt, 2))
print("fve calls:", state["fve"])

cams=4, windows=2, frames=2500

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
reference cam fixed: 0
observations: 20000
[Coordinate Alignment] Intersection line direction: [-0.2016, 0.9761, -0.0815]
[Coordinate Alignment] Intersection line direction: [-0.2016, 0.9761, -0.0815]
[ALIGN CHECK] Y-Axis (Intersection): [-4.27069348e-18  1.00000000e+00  1.89668606e-17]
[ALIGN CHECK] Z-Axis (Plane 0 Normal): [-2.01129160e-17  1.89668606e-17  1.00000000e+00]
[Coordinate Alignment] Centering World at Cloud Centroid: [  4.18181678  -0.68259398 184.97554366]
[Coordinate Alignment] Applied rotation and translation to align coordinates.

Initializing C++ Camera objects in-memory...
  Initialized 4 C++ Camera objects.
[B] alignment applied before SBA
R_align=
 [[ 0.97721405  0.19478644 -0.08432645]
 [-0.20159031  0.97607522 -0.08147701]
 [ 0.06643834  0.09661988  0.99310148]]
t_shift= [  -4.18181678    0.68259398 -184.97554366]
n_params: 15028 n_residuals: 22500
jac_sparsity: (22500, 15028) nnz: 265000
sigma_ray=0.011657 mm, sigma_wand=0.200000 mm

Start SBA (B: pre-rot-align + no X regularization)...
[fve~  10] ray=0.092705 mm | len=0.243132 mm | elapsed=4.9s
[fve~  20] ray=0.070099 mm | len=0.193757 mm | elapsed=10.4s
[fve~  30] ray=0.070099 mm | len=0.193757 mm | elapsed=15.3s
[fve~  40] ray=0.044640 mm | len=0.231419 mm | elapsed=20.4s
[fve~  50] ray=0.044640 mm | len=0.231419 mm | elapsed=25.4s
[fve~  60] ray=0.017669 mm | len=0.206142 mm | elapsed=30.5s
[fve~  70] ray=0.017669 mm | len=0.206142 mm | elapsed=35.5s
[fve~  80] ray=0.014577 mm | len=0.198104 mm | elapsed=40.7s
[fve~  90] ray=0.014577 mm | len=0.198104 mm | elapsed=45.6s
[fve~ 100] ray=0.011141 mm | len=0.206172 mm | elapsed=50.5s
[fve~ 110] ray=0.011141 mm | len=0.206172 mm | elapsed=55.4s
[fve~ 120] ray=0.010661 mm | len=0.205685 mm | elapsed=60.4s
[fve~ 130] ray=0.009860 mm | len=0.205715 mm | elapsed=65.3s
[fve~ 140] ray=0.009860 mm | len=0.205715 mm | elapsed=70.1s
[fve~ 150] ray=0.009767 mm | len=0.205715 mm | elapsed=75.0s
[fve~ 160] ray=0.009767 mm | len=0.205715 mm | elapsed=80.0s
[fve~ 170] ray=0.009150 mm | len=0.205715 mm | elapsed=84.8s
[fve~ 180] ray=0.009150 mm | len=0.205715 mm | elapsed=89.7s
[fve~ 190] ray=0.009057 mm | len=0.205715 mm | elapsed=94.7s
[fve~ 200] ray=0.009057 mm | len=0.205715 mm | elapsed=99.6s
[fve~ 210] ray=0.008934 mm | len=0.205715 mm | elapsed=104.6s
[fve~ 220] ray=0.008934 mm | len=0.205715 mm | elapsed=109.4s
[fve~ 230] ray=0.008912 mm | len=0.205715 mm | elapsed=114.3s
[fve~ 240] ray=0.008912 mm | len=0.205715 mm | elapsed=119.2s
[fve~ 250] ray=0.008907 mm | len=0.205715 mm | elapsed=124.1s
[fve~ 260] ray=0.008904 mm | len=0.205715 mm | elapsed=129.1s
[fve~ 270] ray=0.008904 mm | len=0.205715 mm | elapsed=134.0s
[fve~ 280] ray=0.008897 mm | len=0.205715 mm | elapsed=139.0s
[fve~ 290] ray=0.008897 mm | len=0.205715 mm | elapsed=143.9s
[fve~ 300] ray=0.008886 mm | len=0.205715 mm | elapsed=148.9s
[fve~ 310] ray=0.008886 mm | len=0.205715 mm | elapsed=153.8s
[fve~ 320] ray=0.008867 mm | len=0.205716 mm | elapsed=158.8s
[fve~ 330] ray=0.008867 mm | len=0.205716 mm | elapsed=163.8s
[fve~ 340] ray=0.008841 mm | len=0.205719 mm | elapsed=168.7s
[fve~ 350] ray=0.008816 mm | len=0.205726 mm | elapsed=173.8s
[fve~ 360] ray=0.008816 mm | len=0.205726 mm | elapsed=178.6s
[fve~ 370] ray=0.008780 mm | len=0.205742 mm | elapsed=183.6s
[fve~ 380] ray=0.008780 mm | len=0.205742 mm | elapsed=188.5s
[fve~ 390] ray=0.008718 mm | len=0.205775 mm | elapsed=193.4s
[fve~ 400] ray=0.008718 mm | len=0.205775 mm | elapsed=198.3s
[fve~ 410] ray=0.008596 mm | len=0.205844 mm | elapsed=203.3s
[fve~ 420] ray=0.008596 mm | len=0.205844 mm | elapsed=208.2s
[fve~ 430] ray=0.008383 mm | len=0.205975 mm | elapsed=213.3s
[fve~ 440] ray=0.008020 mm | len=0.206231 mm | elapsed=218.2s
[fve~ 450] ray=0.008020 mm | len=0.206231 mm | elapsed=223.2s
[fve~ 460] ray=0.007702 mm | len=0.206568 mm | elapsed=228.3s
[fve~ 470] ray=0.007702 mm | len=0.206568 mm | elapsed=233.3s
[fve~ 480] ray=0.007663 mm | len=0.206981 mm | elapsed=238.2s
[fve~ 490] ray=0.007663 mm | len=0.206981 mm | elapsed=243.2s
[fve~ 500] ray=0.007369 mm | len=0.206981 mm | elapsed=252.9s
[fve~ 510] ray=0.007369 mm | len=0.206981 mm | elapsed=259.2s
[fve~ 520] ray=0.007357 mm | len=0.206981 mm | elapsed=264.2s
[fve~ 530] ray=0.007357 mm | len=0.206981 mm | elapsed=269.2s
[fve~ 540] ray=0.007354 mm | len=0.206981 mm | elapsed=274.2s
[fve~ 550] ray=0.007354 mm | len=0.206981 mm | elapsed=279.2s
[fve~ 560] ray=0.007353 mm | len=0.206981 mm | elapsed=284.1s
[fve~ 570] ray=0.007353 mm | len=0.206982 mm | elapsed=289.1s
[fve~ 580] ray=0.007353 mm | len=0.206982 mm | elapsed=294.0s
[fve~ 590] ray=0.007351 mm | len=0.206983 mm | elapsed=299.1s
[fve~ 600] ray=0.007351 mm | len=0.206983 mm | elapsed=304.1s
[fve~ 610] ray=0.007350 mm | len=0.206985 mm | elapsed=309.0s
[fve~ 620] ray=0.007350 mm | len=0.206985 mm | elapsed=314.0s
[fve~ 630] ray=0.007346 mm | len=0.206988 mm | elapsed=319.0s
[fve~ 640] ray=0.007346 mm | len=0.206988 mm | elapsed=324.0s
[fve~ 650] ray=0.007341 mm | len=0.206994 mm | elapsed=328.9s
[fve~ 660] ray=0.007329 mm | len=0.207004 mm | elapsed=333.9s
[fve~ 670] ray=0.007329 mm | len=0.207004 mm | elapsed=338.8s
[fve~ 680] ray=0.007316 mm | len=0.206979 mm | elapsed=343.8s
[fve~ 690] ray=0.007316 mm | len=0.206979 mm | elapsed=348.8s
[fve~ 700] ray=0.007285 mm | len=0.206969 mm | elapsed=353.8s
[fve~ 710] ray=0.007285 mm | len=0.206969 mm | elapsed=358.7s
[fve~ 720] ray=0.007246 mm | len=0.206811 mm | elapsed=363.8s
[fve~ 730] ray=0.007246 mm | len=0.206811 mm | elapsed=368.7s
[fve~ 740] ray=0.007185 mm | len=0.206433 mm | elapsed=373.9s
[fve~ 750] ray=0.007099 mm | len=0.205364 mm | elapsed=379.1s
[fve~ 760] ray=0.007099 mm | len=0.205364 mm | elapsed=384.1s
[fve~ 770] ray=0.006955 mm | len=0.202905 mm | elapsed=389.3s
[fve~ 780] ray=0.006955 mm | len=0.202905 mm | elapsed=394.3s
[fve~ 790] ray=0.006686 mm | len=0.197891 mm | elapsed=399.5s
[fve~ 800] ray=0.006686 mm | len=0.197891 mm | elapsed=404.4s
[fve~ 810] ray=0.006207 mm | len=0.187485 mm | elapsed=409.9s
[fve~ 820] ray=0.006207 mm | len=0.187485 mm | elapsed=414.8s
[fve~ 830] ray=0.005900 mm | len=0.169029 mm | elapsed=420.1s
[fve~ 840] ray=0.006148 mm | len=0.164674 mm | elapsed=425.4s
[fve~ 850] ray=0.005658 mm | len=0.167929 mm | elapsed=430.5s
[fve~ 860] ray=0.005640 mm | len=0.167984 mm | elapsed=435.6s
[fve~ 870] ray=0.005640 mm | len=0.167984 mm | elapsed=440.8s
[fve~ 880] ray=0.005546 mm | len=0.167984 mm | elapsed=446.1s
[fve~ 890] ray=0.005546 mm | len=0.167984 mm | elapsed=451.3s
[fve~ 900] ray=0.005220 mm | len=0.167984 mm | elapsed=458.4s
[fve~ 910] ray=0.005220 mm | len=0.167984 mm | elapsed=466.5s
[fve~ 920] ray=0.005202 mm | len=0.167984 mm | elapsed=471.8s
[fve~ 930] ray=0.005202 mm | len=0.167984 mm | elapsed=476.9s
[fve~ 940] ray=0.005188 mm | len=0.167984 mm | elapsed=482.1s
[fve~ 950] ray=0.005184 mm | len=0.167984 mm | elapsed=487.3s
[fve~ 960] ray=0.005184 mm | len=0.167984 mm | elapsed=492.4s
[fve~ 970] ray=0.005181 mm | len=0.167984 mm | elapsed=497.6s
[fve~ 980] ray=0.005181 mm | len=0.167984 mm | elapsed=502.7s
[fve~ 990] ray=0.005179 mm | len=0.167984 mm | elapsed=507.9s
[fve~1000] ray=0.005179 mm | len=0.167984 mm | elapsed=513.1s
[fve~1010] ray=0.005177 mm | len=0.167984 mm | elapsed=518.4s
[fve~1020] ray=0.005177 mm | len=0.167984 mm | elapsed=523.6s
[fve~1030] ray=0.005172 mm | len=0.167985 mm | elapsed=528.7s
[fve~1040] ray=0.005165 mm | len=0.167985 mm | elapsed=533.9s
[fve~1050] ray=0.005165 mm | len=0.167985 mm | elapsed=539.0s
[fve~1060] ray=0.005156 mm | len=0.167987 mm | elapsed=544.0s
[fve~1070] ray=0.005156 mm | len=0.167987 mm | elapsed=548.9s
[fve~1080] ray=0.005145 mm | len=0.167992 mm | elapsed=553.8s
[fve~1090] ray=0.005145 mm | len=0.167992 mm | elapsed=558.7s
[fve~1100] ray=0.005129 mm | len=0.168001 mm | elapsed=563.7s
[fve~1110] ray=0.005129 mm | len=0.168001 mm | elapsed=568.6s
[fve~1120] ray=0.005100 mm | len=0.168018 mm | elapsed=573.7s
[fve~1130] ray=0.005051 mm | len=0.168043 mm | elapsed=578.6s
[fve~1140] ray=0.005051 mm | len=0.168043 mm | elapsed=583.6s
[fve~1150] ray=0.004993 mm | len=0.167995 mm | elapsed=588.6s
[fve~1160] ray=0.004993 mm | len=0.167995 mm | elapsed=593.6s
[fve~1170] ray=0.004899 mm | len=0.167913 mm | elapsed=598.6s
[fve~1180] ray=0.004899 mm | len=0.167913 mm | elapsed=603.5s
[fve~1190] ray=0.004820 mm | len=0.167308 mm | elapsed=608.7s
[fve~1200] ray=0.004820 mm | len=0.167308 mm | elapsed=613.6s
[fve~1210] ray=0.004720 mm | len=0.166178 mm | elapsed=618.7s
[fve~1220] ray=0.004942 mm | len=0.165179 mm | elapsed=623.7s
[fve~1230] ray=0.004686 mm | len=0.165925 mm | elapsed=628.6s
[fve~1240] ray=0.004680 mm | len=0.165934 mm | elapsed=633.6s
[fve~1250] ray=0.004680 mm | len=0.165934 mm | elapsed=638.5s
[fve~1260] ray=0.004638 mm | len=0.165934 mm | elapsed=643.5s
[fve~1270] ray=0.004638 mm | len=0.165934 mm | elapsed=648.4s
[fve~1280] ray=0.004628 mm | len=0.165934 mm | elapsed=653.3s
[fve~1290] ray=0.004628 mm | len=0.165934 mm | elapsed=658.2s
[fve~1300] ray=0.004626 mm | len=0.165934 mm | elapsed=663.1s
[fve~1310] ray=0.004626 mm | len=0.165934 mm | elapsed=668.0s
[fve~1320] ray=0.004626 mm | len=0.165934 mm | elapsed=673.0s
[fve~1330] ray=0.004626 mm | len=0.165934 mm | elapsed=677.9s
[fve~1340] ray=0.004626 mm | len=0.165934 mm | elapsed=682.8s
[fve~1350] ray=0.004626 mm | len=0.165934 mm | elapsed=687.7s
[fve~1360] ray=0.004625 mm | len=0.165934 mm | elapsed=692.6s
[fve~1370] ray=0.004625 mm | len=0.165934 mm | elapsed=697.5s
[fve~1380] ray=0.004625 mm | len=0.165934 mm | elapsed=702.4s
[fve~1390] ray=0.004625 mm | len=0.165934 mm | elapsed=707.2s
[fve~1400] ray=0.004625 mm | len=0.165934 mm | elapsed=712.2s
[fve~1410] ray=0.004625 mm | len=0.165934 mm | elapsed=717.1s
[fve~1420] ray=0.004625 mm | len=0.165934 mm | elapsed=722.0s
[fve~1430] ray=0.004625 mm | len=0.165934 mm | elapsed=727.1s
[fve~1440] ray=0.004625 mm | len=0.165934 mm | elapsed=732.0s
[fve~1450] ray=0.004625 mm | len=0.165934 mm | elapsed=737.0s
[fve~1460] ray=0.004625 mm | len=0.165934 mm | elapsed=742.0s
[fve~1470] ray=0.004625 mm | len=0.165934 mm | elapsed=747.0s
[fve~1480] ray=0.004625 mm | len=0.165935 mm | elapsed=752.0s
[fve~1490] ray=0.004625 mm | len=0.165935 mm | elapsed=757.0s
[fve~1500] ray=0.004624 mm | len=0.165936 mm | elapsed=762.0s
[fve~1510] ray=0.004624 mm | len=0.165936 mm | elapsed=767.0s
[fve~1520] ray=0.004622 mm | len=0.165938 mm | elapsed=772.1s
[fve~1530] ray=0.004622 mm | len=0.165938 mm | elapsed=777.0s
[fve~1540] ray=0.004619 mm | len=0.165940 mm | elapsed=782.0s
[fve~1550] ray=0.004615 mm | len=0.165942 mm | elapsed=787.1s
[fve~1560] ray=0.004615 mm | len=0.165942 mm | elapsed=791.9s
[fve~1570] ray=0.004609 mm | len=0.165934 mm | elapsed=796.9s
[fve~1580] ray=0.004609 mm | len=0.165934 mm | elapsed=801.9s
[fve~1590] ray=0.004600 mm | len=0.165897 mm | elapsed=807.0s
[fve~1600] ray=0.004600 mm | len=0.165897 mm | elapsed=812.0s
[fve~1610] ray=0.004587 mm | len=0.165792 mm | elapsed=817.2s
[fve~1620] ray=0.004587 mm | len=0.165792 mm | elapsed=822.3s
[fve~1630] ray=0.004566 mm | len=0.165537 mm | elapsed=827.5s
[fve~1640] ray=0.004534 mm | len=0.164909 mm | elapsed=832.9s
[fve~1650] ray=0.004534 mm | len=0.164909 mm | elapsed=837.8s
[fve~1660] ray=0.004470 mm | len=0.163683 mm | elapsed=843.2s
[fve~1670] ray=0.004470 mm | len=0.163683 mm | elapsed=848.2s
[fve~1680] ray=0.004392 mm | len=0.161180 mm | elapsed=853.7s
[fve~1690] ray=0.004392 mm | len=0.161180 mm | elapsed=858.7s
[fve~1700] ray=0.004202 mm | len=0.156304 mm | elapsed=864.3s
[fve~1710] ray=0.004202 mm | len=0.156304 mm | elapsed=869.4s
[fve~1720] ray=0.003965 mm | len=0.146957 mm | elapsed=874.8s
[fve~1730] ray=0.003777 mm | len=0.145986 mm | elapsed=880.1s
[fve~1740] ray=0.003777 mm | len=0.145986 mm | elapsed=885.1s
[fve~1750] ray=0.003789 mm | len=0.145999 mm | elapsed=890.2s
[fve~1760] ray=0.003751 mm | len=0.145986 mm | elapsed=895.2s
[fve~1770] ray=0.003751 mm | len=0.145986 mm | elapsed=900.2s
[fve~1780] ray=0.003712 mm | len=0.145986 mm | elapsed=905.1s
[fve~1790] ray=0.003704 mm | len=0.145986 mm | elapsed=910.0s
[fve~1800] ray=0.003704 mm | len=0.145986 mm | elapsed=914.9s
[fve~1810] ray=0.003703 mm | len=0.145986 mm | elapsed=920.0s
[fve~1820] ray=0.003703 mm | len=0.145986 mm | elapsed=925.0s
[fve~1830] ray=0.003703 mm | len=0.145987 mm | elapsed=930.2s
[fve~1840] ray=0.003703 mm | len=0.145987 mm | elapsed=940.3s
[fve~1850] ray=0.003702 mm | len=0.145987 mm | elapsed=945.5s
[fve~1860] ray=0.003702 mm | len=0.145987 mm | elapsed=950.7s
[fve~1870] ray=0.003702 mm | len=0.145987 mm | elapsed=955.8s
[fve~1880] ray=0.003702 mm | len=0.145987 mm | elapsed=960.9s
[fve~1890] ray=0.003702 mm | len=0.145987 mm | elapsed=965.9s
[fve~1900] ray=0.003702 mm | len=0.145987 mm | elapsed=970.9s
[fve~1910] ray=0.003702 mm | len=0.145987 mm | elapsed=975.8s
[fve~1920] ray=0.003702 mm | len=0.145987 mm | elapsed=980.7s
[fve~1930] ray=0.003702 mm | len=0.145987 mm | elapsed=985.7s
[fve~1940] ray=0.003702 mm | len=0.145987 mm | elapsed=990.7s
[fve~1950] ray=0.003702 mm | len=0.145987 mm | elapsed=995.8s
[fve~1960] ray=0.003702 mm | len=0.145987 mm | elapsed=1000.8s
[fve~1970] ray=0.003702 mm | len=0.145987 mm | elapsed=1005.9s
[fve~1980] ray=0.003701 mm | len=0.145988 mm | elapsed=1011.1s
[fve~1990] ray=0.003700 mm | len=0.145989 mm | elapsed=1016.3s
[fve~2000] ray=0.003700 mm | len=0.145989 mm | elapsed=1021.4s
[fve~2010] ray=0.003698 mm | len=0.145991 mm | elapsed=1026.5s
[fve~2020] ray=0.003698 mm | len=0.145991 mm | elapsed=1031.6s
[fve~2030] ray=0.003695 mm | len=0.145997 mm | elapsed=1036.7s
[fve~2040] ray=0.003695 mm | len=0.145997 mm | elapsed=1041.6s
[fve~2050] ray=0.003688 mm | len=0.146006 mm | elapsed=1046.6s
[fve~2060] ray=0.003688 mm | len=0.146006 mm | elapsed=1051.5s
[fve~2070] ray=0.003677 mm | len=0.146023 mm | elapsed=1056.4s
[fve~2080] ray=0.003661 mm | len=0.146041 mm | elapsed=1061.4s
[fve~2090] ray=0.003661 mm | len=0.146041 mm | elapsed=1066.4s
[fve~2100] ray=0.003636 mm | len=0.146065 mm | elapsed=1071.6s
[fve~2110] ray=0.003636 mm | len=0.146065 mm | elapsed=1076.7s
[fve~2120] ray=0.003606 mm | len=0.146004 mm | elapsed=1082.0s
[fve~2130] ray=0.003606 mm | len=0.146004 mm | elapsed=1087.2s
[fve~2140] ray=0.003553 mm | len=0.145854 mm | elapsed=1092.7s
[fve~2150] ray=0.003553 mm | len=0.145854 mm | elapsed=1097.8s
[fve~2160] ray=0.003482 mm | len=0.145166 mm | elapsed=1103.2s
[fve~2170] ray=0.003330 mm | len=0.143913 mm | elapsed=1108.9s
[fve~2180] ray=0.003330 mm | len=0.143913 mm | elapsed=1114.0s
[fve~2190] ray=0.003225 mm | len=0.140286 mm | elapsed=1119.6s
[fve~2200] ray=0.003225 mm | len=0.140286 mm | elapsed=1124.7s
[fve~2210] ray=0.002845 mm | len=0.135136 mm | elapsed=1130.3s
[fve~2220] ray=0.002845 mm | len=0.135136 mm | elapsed=1135.5s
[fve~2230] ray=0.002641 mm | len=0.130762 mm | elapsed=1141.0s
[fve~2240] ray=0.002641 mm | len=0.130762 mm | elapsed=1146.4s

=== SBA B Done ===
status : 0
message: The maximum number of function evaluations is exceeded.
nfev   : 150
time(s): 1147.21
fve calls: 2241

Synthetic test

In [2]:
import os, csv, json, math
from pathlib import Path
import numpy as np
import cv2
import matplotlib.pyplot as plt

import pyopenlpt as lpt

# =========================================================
# Global settings
# =========================================================
OUT_ROOT = Path(r"J:\Refraction_test")
OUT_ROOT.mkdir(parents=True, exist_ok=True)

IMG_W, IMG_H = 1280, 800
FOCAL = 9000.0
CX, CY = IMG_W / 2.0, IMG_H / 2.0

WAND_LEN_MM = 10.0
R_SMALL_MM = 1.5
R_LARGE_MM = 2.0
METRIC_CONST = 1.0

N_OBJ, N_WIN, N_AIR = 1.333, 1.49, 1.0
THICK_MM = 10.0
REFRACT_ARRAY = [N_OBJ, N_WIN, N_AIR]   # farthest->nearest
W_ARRAY = [THICK_MM]

SEED_BASE = 20260223
N_FRAMES_TARGET = 2000
MAX_FRAME_TRIES = 1_200_000
HALFSPACE_MARGIN_MM = 2.0
D_PLANE_MM = 120.0

DIST_MAP = {
    "Near": 550.0,
    "Mid": 800.0,
    "Far": 1100.0,
}

# ---------------------------------------------------------
# 30-case matrix
# G is adjacent face inner angle
# A uses 15/30/45 now
# ---------------------------------------------------------
CASES = [
    {"id": 1,  "P": 1, "C": [2],       "G": None, "A": "U15", "D": "Near"},
    {"id": 2,  "P": 1, "C": [2],       "G": None, "A": "U45", "D": "Far"},
    {"id": 3,  "P": 1, "C": [3],       "G": None, "A": "U30", "D": "Mid"},
    {"id": 4,  "P": 1, "C": [3],       "G": None, "A": "M3",  "D": "Near"},
    {"id": 5,  "P": 1, "C": [4],       "G": None, "A": "U15", "D": "Far"},
    {"id": 6,  "P": 1, "C": [4],       "G": None, "A": "M2",  "D": "Mid"},

    {"id": 7,  "P": 2, "C": [2,2],     "G": 60,   "A": "U30", "D": "Near"},
    {"id": 8,  "P": 2, "C": [2,2],     "G": 120,  "A": "M2",  "D": "Far"},
    {"id": 9,  "P": 2, "C": [3,3],     "G": 90,   "A": "U30", "D": "Mid"},
    {"id": 10, "P": 2, "C": [3,3],     "G": 60,   "A": "M3",  "D": "Far"},
    {"id": 11, "P": 2, "C": [2,3],     "G": 90,   "A": "U15", "D": "Near"},
    {"id": 12, "P": 2, "C": [2,3],     "G": 120,  "A": "M2",  "D": "Mid"},
    {"id": 13, "P": 2, "C": [2,4],     "G": 60,   "A": "U45", "D": "Far"},
    {"id": 14, "P": 2, "C": [2,4],     "G": 90,   "A": "M3",  "D": "Near"},
    {"id": 15, "P": 2, "C": [3,4],     "G": 120,  "A": "U30", "D": "Mid"},
    {"id": 16, "P": 2, "C": [3,4],     "G": 60,   "A": "M2",  "D": "Far"},
    {"id": 17, "P": 2, "C": [4,4],     "G": 90,   "A": "U15", "D": "Mid"},
    {"id": 18, "P": 2, "C": [4,4],     "G": 120,  "A": "M3",  "D": "Near"},

    {"id": 19, "P": 3, "C": [2,2,2],   "G": 60,   "A": "U30", "D": "Near"},
    {"id": 20, "P": 3, "C": [2,2,2],   "G": 120,  "A": "M3",  "D": "Far"},
    {"id": 21, "P": 3, "C": [3,3,3],   "G": 90,   "A": "U30", "D": "Mid"},
    {"id": 22, "P": 3, "C": [3,3,3],   "G": 60,   "A": "M2",  "D": "Far"},
    {"id": 23, "P": 3, "C": [2,3,4],   "G": 90,   "A": "M3",  "D": "Near"},
    {"id": 24, "P": 3, "C": [2,3,4],   "G": 120,  "A": "U15", "D": "Mid"},
    {"id": 25, "P": 3, "C": [2,4,4],   "G": 60,   "A": "U45", "D": "Far"},
    {"id": 26, "P": 3, "C": [2,4,4],   "G": 90,   "A": "M2",  "D": "Near"},
    {"id": 27, "P": 3, "C": [3,2,4],   "G": 120,  "A": "M3",  "D": "Mid"},
    {"id": 28, "P": 3, "C": [3,2,4],   "G": 60,   "A": "U15", "D": "Far"},
    {"id": 29, "P": 3, "C": [4,3,2],   "G": 90,   "A": "M2",  "D": "Mid"},
    {"id": 30, "P": 3, "C": [4,3,2],   "G": 120,  "A": "U45", "D": "Near"},
]

# =========================================================
# Math helpers
# =========================================================
def nrm(v):
    n = np.linalg.norm(v)
    return v if n < 1e-12 else v / n

def basis_from_n(n):
    n = nrm(n)
    ref = np.array([0.0, 0.0, 1.0])
    if abs(np.dot(n, ref)) > 0.95:
        ref = np.array([0.0, 1.0, 0.0])
    u = nrm(np.cross(n, ref))
    v = nrm(np.cross(n, u))
    return u, v

def look_at_origin(C):
    z = nrm(-C)  # optical axis camera->origin
    up = np.array([0.0, 0.0, 1.0])
    if abs(np.dot(z, up)) > 0.98:
        up = np.array([0.0, 1.0, 0.0])
    x = nrm(np.cross(up, z))
    y = nrm(np.cross(z, x))
    R = np.vstack([x, y, z])  # world->cam
    t = -R @ C
    return R, t

def rodrigues_rvec(R):
    rv, _ = cv2.Rodrigues(R)
    return rv.ravel()

def angle_profile(name, n):
    base = {
        "U15": [15.0],
        "U30": [30.0],
        "U45": [45.0],
        "M2":  [15.0, 45.0],
        "M3":  [15.0, 30.0, 45.0],
    }[name]
    return [base[i % len(base)] for i in range(n)]

# =========================================================
# Geometry generation
# =========================================================
def build_planes(P, G_inner_deg, d_plane=D_PLANE_MM):
    """
    G_inner_deg = adjacent face inner angle.
    Adjacent normal angle = 180 - G_inner_deg.
    """
    if P == 1:
        phis = [0.0]
    else:
        dphi = np.deg2rad(180.0 - G_inner_deg)
        phis = [i * dphi for i in range(P)]

    planes = []
    for i, ph in enumerate(phis):
        n = nrm(np.array([np.cos(ph), np.sin(ph), 0.0], dtype=float))
        p = -d_plane * n
        planes.append({"id": i, "n": n, "pt_far": p, "d_plane": d_plane})
    return planes

def enforce_plane_normal_direction(planes):
    # origin should be object-side: n·(O-p)>0
    O = np.zeros(3)
    for pl in planes:
        if np.dot(pl["n"], O - pl["pt_far"]) < 0:
            pl["n"] = -pl["n"]

def build_cameras(case, planes, phi_plane):
    """
    phi_plane: per-plane azimuth phase offsets (len=P)
    """
    cams = []
    cam_id = 0
    Rcam = DIST_MAP[case["D"]]

    for pid, cnum in enumerate(case["C"]):
        n = planes[pid]["n"]
        u, v = basis_from_n(n)
        betas = angle_profile(case["A"], cnum)  # angle(optical_axis, normal)
        ph0 = phi_plane[pid]

        for j in range(cnum):
            phi = ph0 + 2*np.pi*j/max(cnum, 1)
            t_hat = nrm(np.cos(phi)*u + np.sin(phi)*v)

            beta = np.deg2rad(betas[j])
            d = nrm(np.cos(beta)*n + np.sin(beta)*t_hat)  # camera->origin axis

            C = -Rcam * d
            R, t = look_at_origin(C)
            beta_chk = np.degrees(np.arccos(np.clip(np.dot(d, n), -1.0, 1.0)))

            cams.append({
                "cam_id": cam_id,
                "plane_id": pid,
                "C": C,
                "R": R,
                "t": t,
                "beta_deg": float(beta_chk),
            })
            cam_id += 1

    return cams

# =========================================================
# Cam file writer
# =========================================================
def write_camfile(path, cam, plane):
    R, t, C = cam["R"], cam["t"], cam["C"]
    n, p = plane["n"], plane["pt_far"]
    rv = rodrigues_rvec(R)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Camera Model: (PINHOLE/POLYNOMIAL/PINPLATE)\nPINPLATE\n")
        f.write("# Camera Calibration Error:\n0,0\n")
        f.write("# Pose Calibration Error:\n0,0\n")
        f.write(f"# Image Size: (n_row,n_col)\n{IMG_H},{IMG_W}\n")
        f.write("# Camera Matrix:\n")
        f.write(f"{FOCAL:.8g} 0 {CX:.8g}\n")
        f.write(f"0 {FOCAL:.8g} {CY:.8g}\n")
        f.write("0 0 1\n")
        f.write("# Distortion Coefficients:\n0,0,0,0,0\n")
        f.write(f"# Rotation Vector:\n{rv[0]:.8g},{rv[1]:.8g},{rv[2]:.8g}\n")
        f.write("# Rotation Matrix:\n")
        for row in R:
            f.write(f"{row[0]:.8g} {row[1]:.8g} {row[2]:.8g}\n")
        f.write("# Inverse of Rotation Matrix:\n")
        for row in R.T:
            f.write(f"{row[0]:.8g} {row[1]:.8g} {row[2]:.8g}\n")
        f.write(f"# Translation Vector:\n{t[0]:.8g} {t[1]:.8g} {t[2]:.8g}\n")
        f.write(f"# Inverse of Translation Vector:\n{C[0]:.8g} {C[1]:.8g} {C[2]:.8g}\n")
        f.write("# Refractive plane reference point plane.pt (Farthest Interface)\n")
        f.write(f"{p[0]:.8g} {p[1]:.8g} {p[2]:.8g}\n")
        f.write("# Refractive plane normal plane.norm_vector (camera->object direction)\n")
        f.write(f"{n[0]:.8g} {n[1]:.8g} {n[2]:.8g}\n")
        f.write("# refract_array (ONE token, comma-separated, farthest->nearest: obj->win->air)\n")
        f.write(",".join(f"{x:.4f}" for x in REFRACT_ARRAY) + "\n")
        f.write("# w_array (ONE token, comma-separated, plate thicknesses in mm)\n")
        f.write(",".join(f"{x:.4f}" for x in W_ARRAY) + "\n")
        f.write("# proj_tol\n1e-6\n# proj_nmax\n50\n# lr (learning rate)\n0.1\n")
        f.write("# --- BEGIN_REFRACTION_META ---\n")
        f.write("# VERSION=2\n")
        f.write(f"# CAM_ID={cam['cam_id']}\n")
        f.write(f"# WINDOW_ID={cam['plane_id']}\n")
        f.write("# --- END_REFRACTION_META ---\n")

# =========================================================
# Visibility / FOV
# =========================================================
def project_batch(cam_obj, pts):
    pts_lpt = [lpt.Pt3D(float(p[0]), float(p[1]), float(p[2])) for p in pts]
    try:
        st = cam_obj.projectBatchStatus(pts_lpt, False)
    except TypeError:
        st = cam_obj.projectBatchStatus(pts_lpt)

    uv = np.full((len(pts), 2), np.nan, dtype=float)
    ok = np.zeros(len(pts), dtype=bool)
    for i, s in enumerate(st):
        if s and s[0]:
            u, v = float(s[1][0]), float(s[1][1])
            uv[i] = [u, v]
            ok[i] = (0 <= u < IMG_W) and (0 <= v < IMG_H)
    return uv, ok

def project_one(cam_obj, X):
    p = lpt.Pt3D(float(X[0]), float(X[1]), float(X[2]))
    try:
        st = cam_obj.projectStatus(p, False)
    except TypeError:
        st = cam_obj.projectStatus(p)
    if not st or not st[0]:
        return None, False
    u, v = float(st[1][0]), float(st[1][1])
    ok = (0 <= u < IMG_W) and (0 <= v < IMG_H)
    return np.array([u, v]), ok

def in_object_side_all_planes(X, planes, margin_mm):
    for pl in planes:
        if np.dot(pl["n"], X - pl["pt_far"]) <= margin_mm:
            return False
    return True

def collect_valid_voxels(cams_obj, planes, bmin, bmax, step, margin_mm):
    xs = np.arange(bmin[0], bmax[0] + 1e-9, step)
    ys = np.arange(bmin[1], bmax[1] + 1e-9, step)
    zs = np.arange(bmin[2], bmax[2] + 1e-9, step)
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing="xy")
    pts = np.stack([X.ravel(), Y.ravel(), Z.ravel()], axis=1)

    hs_ok = np.array([in_object_side_all_planes(p, planes, margin_mm) for p in pts], dtype=bool)
    if not np.any(hs_ok):
        return np.empty((0, 3)), {"n_vox": int(len(pts)), "n_halfspace": 0, "n_valid": 0, "step": float(step)}

    vis = hs_ok.copy()
    for cam in cams_obj:
        _, ok = project_batch(cam, pts)
        vis &= ok
        if not np.any(vis):
            break

    valid = pts[vis]
    stat = {
        "n_vox": int(len(pts)),
        "n_halfspace": int(np.sum(hs_ok)),
        "n_valid": int(len(valid)),
        "step": float(step),
    }
    return valid, stat

# =========================================================
# Point generation
# =========================================================
def radius_px(R, t, Xw, r_mm):
    Xc = R @ Xw + t
    z = float(Xc[2])
    if z <= 1e-9:
        return np.nan
    return FOCAL * r_mm / z

def sample_wand_points(cams, cams_obj, planes, valid_pts, rng, n_target, margin_mm, voxel_step):
    if len(valid_pts) == 0:
        return None, None, None, {"tries": 0, "accepted": 0, "reject_side": 0, "reject_vis": 0}

    A_list, B_list, rows = [], [], []
    tries, reject_side, reject_vis = 0, 0, 0

    while len(A_list) < n_target and tries < MAX_FRAME_TRIES:
        tries += 1
        c = valid_pts[rng.integers(0, len(valid_pts))] + rng.uniform(-0.35*voxel_step, 0.35*voxel_step, size=3)
        u = nrm(rng.normal(size=3))
        A = c - 0.5 * WAND_LEN_MM * u
        B = c + 0.5 * WAND_LEN_MM * u

        if (not in_object_side_all_planes(A, planes, margin_mm)) or (not in_object_side_all_planes(B, planes, margin_mm)):
            reject_side += 1
            continue

        ok_all = True
        uvA_by, uvB_by = {}, {}
        for cm, co in zip(cams, cams_obj):
            uvA, okA = project_one(co, A)
            uvB, okB = project_one(co, B)
            if not (okA and okB):
                ok_all = False
                break
            uvA_by[cm["cam_id"]] = uvA
            uvB_by[cm["cam_id"]] = uvB

        if not ok_all:
            reject_vis += 1
            continue

        fid = len(A_list)
        A_list.append(A); B_list.append(B)

        for cm in cams:
            cid = cm["cam_id"]
            uA, vA = uvA_by[cid]
            uB, vB = uvB_by[cid]
            rA = radius_px(cm["R"], cm["t"], A, R_SMALL_MM)
            rB = radius_px(cm["R"], cm["t"], B, R_LARGE_MM)
            rows.append([fid, cid, "Filtered_Small", 0, f"{uA:.6f}", f"{vA:.6f}", f"{rA:.6f}", f"{METRIC_CONST:.6f}"])
            rows.append([fid, cid, "Filtered_Large", 1, f"{uB:.6f}", f"{vB:.6f}", f"{rB:.6f}", f"{METRIC_CONST:.6f}"])

    if len(A_list) < n_target:
        return None, None, None, {
            "tries": int(tries),
            "accepted": int(len(A_list)),
            "reject_side": int(reject_side),
            "reject_vis": int(reject_vis),
        }

    return np.array(A_list), np.array(B_list), rows, {
        "tries": int(tries),
        "accepted": int(len(A_list)),
        "reject_side": int(reject_side),
        "reject_vis": int(reject_vis),
    }

# =========================================================
# Plot
# =========================================================
def save_scene_plot(path_png, planes, cams, A_pts, B_pts):
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")

    s = 120.0
    for pl in planes:
        n, p0 = pl["n"], pl["pt_far"]
        u, v = basis_from_n(n)
        q = np.array([p0+s*u+s*v, p0+s*u-s*v, p0-s*u-s*v, p0-s*u+s*v])
        ax.plot(np.r_[q[:,0], q[0,0]], np.r_[q[:,1], q[0,1]], np.r_[q[:,2], q[0,2]], "-", lw=1.2)

    C = np.array([c["C"] for c in cams])
    D = np.array([nrm(-c["C"]) for c in cams])
    ax.scatter(C[:,0], C[:,1], C[:,2], c="r", s=24, label="Cameras")
    ax.quiver(C[:,0], C[:,1], C[:,2], D[:,0], D[:,1], D[:,2], length=80, normalize=True, color="r")

    ax.scatter(A_pts[:,0], A_pts[:,1], A_pts[:,2], c="b", s=5, label="A")
    ax.scatter(B_pts[:,0], B_pts[:,1], B_pts[:,2], c="g", s=5, label="B")
    ax.scatter([0], [0], [0], c="k", marker="x", s=40, label="Origin")

    ax.set_xlabel("X(mm)"); ax.set_ylabel("Y(mm)"); ax.set_zlabel("Z(mm)")
    ax.set_title("Synthetic Scene")
    ax.legend(loc="upper right")
    ax.set_box_aspect([1,1,1])
    plt.tight_layout()
    plt.savefig(path_png, dpi=170)
    plt.close(fig)

# =========================================================
# Layout search
# =========================================================
def search_best_layout(case, retries, rng_base):
    """
    Search phi_plane per plane to maximize valid voxel count.
    """
    P = case["P"]
    best = None

    # coarse region for quick score
    coarse_bmin = np.array([-280.0, -280.0, -280.0])
    coarse_bmax = np.array([ 280.0,  280.0,  280.0])

    for k in range(retries):
        rng = np.random.default_rng(rng_base + k)

        planes = build_planes(case["P"], case["G"] if case["G"] is not None else 90, d_plane=D_PLANE_MM)
        enforce_plane_normal_direction(planes)

        # per-plane phase offsets
        phi_plane = rng.uniform(0, 2*np.pi, size=P)

        cams = build_cameras(case, planes, phi_plane)

        # temporary write/load cameras in memory from formula is enough for score:
        # use pinhole projection score first (fast proxy)
        # Here still using pyopenlpt scoring for fidelity:
        tmp_dir = OUT_ROOT / "_tmp_layout_eval"
        tmp_dir.mkdir(parents=True, exist_ok=True)
        for c in cams:
            write_camfile(tmp_dir / f"cam{c['cam_id']}.txt", c, planes[c["plane_id"]])
        cams_obj = [lpt.Camera(str(tmp_dir / f"cam{c['cam_id']}.txt")) for c in cams]

        valid, stat = collect_valid_voxels(
            cams_obj, planes,
            bmin=coarse_bmin, bmax=coarse_bmax,
            step=16.0, margin_mm=HALFSPACE_MARGIN_MM
        )
        score = stat["n_valid"]

        if (best is None) or (score > best["score"]):
            best = {
                "score": score,
                "planes": planes,
                "cams": cams,
                "phi_plane": phi_plane.tolist(),
                "coarse_stat": stat
            }

    return best

# =========================================================
# Main run
# =========================================================
summary_rows = []
failed_rows = []

for case in CASES[25:]:
    case_id = case["id"]
    case_dir = OUT_ROOT / f"case_{case_id:03d}"
    cam_dir = case_dir / "Synthetic_camFile"
    case_dir.mkdir(parents=True, exist_ok=True)
    cam_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n=== Case {case_id:03d} ===")

    best_layout = search_best_layout(case, retries=240, rng_base=SEED_BASE + 10000*case_id)
    if best_layout is None:
        reason = "layout search failed"
        failed_rows.append([case_id, reason])
        with open(case_dir / "case_meta.json", "w", encoding="utf-8") as f:
            json.dump({"case": case, "status": "failed", "reason": reason}, f, indent=2)
        print(f"[FAIL] {reason}")
        continue

    planes = best_layout["planes"]
    cams = best_layout["cams"]

    # write final cam files
    for c in cams:
        write_camfile(cam_dir / f"cam{c['cam_id']}.txt", c, planes[c["plane_id"]])

    cams_obj = [lpt.Camera(str(cam_dir / f"cam{c['cam_id']}.txt")) for c in cams]

    # refined valid voxels
    refined_bmin = np.array([-320.0, -320.0, -320.0])
    refined_bmax = np.array([ 320.0,  320.0,  320.0])
    valid_pts, fov_stat = collect_valid_voxels(
        cams_obj, planes,
        bmin=refined_bmin, bmax=refined_bmax,
        step=8.0, margin_mm=HALFSPACE_MARGIN_MM
    )

    if len(valid_pts) == 0:
        reason = f"empty common FOV (best coarse score={best_layout['score']})"
        failed_rows.append([case_id, reason])
        with open(case_dir / "case_meta.json", "w", encoding="utf-8") as f:
            json.dump({
                "case": case,
                "status": "failed",
                "reason": reason,
                "layout_search": {
                    "best_phi_plane": best_layout["phi_plane"],
                    "best_coarse_stat": best_layout["coarse_stat"]
                }
            }, f, indent=2)
        print(f"[FAIL] {reason}")
        continue

    rng = np.random.default_rng(SEED_BASE + 20000*case_id)
    A_pts, B_pts, rows, gen_stat = sample_wand_points(
        cams, cams_obj, planes, valid_pts, rng,
        n_target=N_FRAMES_TARGET, margin_mm=HALFSPACE_MARGIN_MM, voxel_step=fov_stat["step"]
    )

    if A_pts is None:
        reason = f"insufficient frames: {gen_stat}"
        failed_rows.append([case_id, reason])
        with open(case_dir / "case_meta.json", "w", encoding="utf-8") as f:
            json.dump({
                "case": case,
                "status": "failed",
                "reason": reason,
                "layout_search": {
                    "best_phi_plane": best_layout["phi_plane"],
                    "best_coarse_stat": best_layout["coarse_stat"]
                },
                "fov": {
                    **fov_stat,
                    "bbox_min": valid_pts.min(axis=0).tolist(),
                    "bbox_max": valid_pts.max(axis=0).tolist()
                }
            }, f, indent=2)
        print(f"[FAIL] {reason}")
        continue

    # save csv
    csv_path = case_dir / "synthetic_wand_points.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["Frame", "Camera", "Status", "PointIdx", "X", "Y", "Radius", "Metric"])
        w.writerows(rows)

    # save plot
    plot_path = case_dir / "scene_overview.png"
    save_scene_plot(plot_path, planes, cams, A_pts, B_pts)

    # save meta
    meta = {
        "case": case,
        "status": "ok",
        "focal_px": FOCAL,
        "image_size": [IMG_H, IMG_W],
        "wand": {
            "length_mm": WAND_LEN_MM,
            "radius_small_mm": R_SMALL_MM,
            "radius_large_mm": R_LARGE_MM,
            "metric": METRIC_CONST,
            "n_frames": int(len(A_pts)),
        },
        "constraints": {
            "all_camera_visible": True,
            "halfspace_margin_mm": HALFSPACE_MARGIN_MM,
            "angle_definition": "camera optical axis vs plane normal",
            "adjacent_plane_angle_definition": "inner angle G"
        },
        "layout_search": {
            "best_phi_plane": best_layout["phi_plane"],
            "best_coarse_stat": best_layout["coarse_stat"],
            "best_coarse_score_n_valid": best_layout["score"]
        },
        "fov": {
            **fov_stat,
            "bbox_min": valid_pts.min(axis=0).tolist(),
            "bbox_max": valid_pts.max(axis=0).tolist()
        },
        "generation": gen_stat,
        "planes": [
            {"id": p["id"], "n": p["n"].tolist(), "pt_far": p["pt_far"].tolist(), "d_from_origin_mm": p["d_plane"]}
            for p in planes
        ],
        "cameras": [
            {"cam_id": c["cam_id"], "plane_id": c["plane_id"], "C_world": c["C"].tolist(), "beta_deg": c["beta_deg"]}
            for c in cams
        ],
        "outputs": {
            "cam_dir": str(cam_dir),
            "csv": str(csv_path),
            "plot": str(plot_path),
        }
    }
    with open(case_dir / "case_meta.json", "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    summary_rows.append([case_id, len(cams), len(A_pts), str(csv_path)])
    print(f"[OK] case_{case_id:03d} cams={len(cams)} frames={len(A_pts)} valid_vox={fov_stat['n_valid']}")

# summary files
manifest_ok = OUT_ROOT / "cases_manifest.csv"
with open(manifest_ok, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["case_id", "n_cams", "n_frames", "csv"])
    w.writerows(summary_rows)

manifest_fail = OUT_ROOT / "cases_failed.csv"
with open(manifest_fail, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["case_id", "reason"])
    w.writerows(failed_rows)

print("\nDone.")
print("  OK manifest   :", manifest_ok)
print("  Failed manifest:", manifest_fail)

=== Case 026 ===
[OK] case_026 cams=10 frames=2000 valid_vox=2

=== Case 027 ===
[OK] case_027 cams=9 frames=2000 valid_vox=408

=== Case 028 ===
[OK] case_028 cams=9 frames=2000 valid_vox=2476

=== Case 029 ===
[OK] case_029 cams=9 frames=2000 valid_vox=275

=== Case 030 ===
[FAIL] empty common FOV (best coarse score=0)

Done.
  OK manifest   : J:\Refraction_test\cases_manifest.csv
  Failed manifest: J:\Refraction_test\cases_failed.csv

Verify the synthetic data

In [1]:
"""
Synthetic数据几何残差验证（无GT版本）
- 直接遍历 case_* 目录
- 直接用 lpt.Camera(file_path) 读取 cam*.txt
- 用 lineOfSightBatchStatus + 多光线最小二乘重构3D
- 几何残差定义：重构点到各相机光线的距离（mm），取该点的 max residual
- 额外检查：每帧 wand length 误差 | ||XB-XA|| - WAND_LEN_MM |
- 判定：
  1) 每个点 max residual < 0.001 mm
  2) 每帧 wand length 绝对误差 < 0.001 mm
  3) case 内所有点和所有帧均通过才算 case 通过
"""

from __future__ import annotations

import csv
import math
import re
from pathlib import Path
from collections import defaultdict
from typing import Dict, Tuple, List, Any

import numpy as np
import pyopenlpt as lpt


ROOT = Path(r"J:\Refraction_test")
THRESH_MM = 1e-3          # point-to-ray max residual threshold (mm)
WAND_LEN_MM = 10.0        # target wand length (mm)
WAND_THRESH_MM = 1e-3     # wand length abs error threshold (mm)


def make_pt2d(uv: Tuple[float, float]):
    return lpt.Pt2D(float(uv[0]), float(uv[1]))


def status_valid(v: str) -> bool:
    s = str(v).strip().lower()
    if s in {"1", "true", "ok", "valid", "yes"}:
        return True
    if s in {"0", "false", "invalid", "no", ""}:
        return False
    return True


def parse_cam_id(path: Path) -> int:
    m = re.match(r"cam(\d+)\.txt$", path.name, flags=re.IGNORECASE)
    if not m:
        raise ValueError(f"Invalid camera filename: {path.name}")
    return int(m.group(1))


def load_cameras(cam_dir: Path) -> Dict[int, Any]:
    cams: Dict[int, Any] = {}
    cam_files = sorted(cam_dir.glob("cam*.txt"), key=lambda p: parse_cam_id(p))
    for f in cam_files:
        cid = parse_cam_id(f)
        cams[cid] = lpt.Camera(str(f))  # 直接读取cam*.txt
    return cams


def load_obs(csv_path: Path) -> Dict[Tuple[int, int], Dict[int, Tuple[float, float]]]:
    # key = (frame, point_idx), value = {cam_id: (u,v)}
    obs = defaultdict(dict)
    with csv_path.open("r", newline="", encoding="utf-8") as f:
        rd = csv.DictReader(f)
        required = {"Frame", "Camera", "Status", "PointIdx", "X", "Y"}
        if not required.issubset(set(rd.fieldnames or [])):
            raise RuntimeError(f"{csv_path} missing required columns: {required}")
        for row in rd:
            if not status_valid(row["Status"]):
                continue
            frame = int(row["Frame"])
            cam = int(row["Camera"])
            pidx = int(row["PointIdx"])
            u = float(row["X"])
            v = float(row["Y"])
            obs[(frame, pidx)][cam] = (u, v)
    return obs


def triangulate_from_rays(rays: List[Tuple[np.ndarray, np.ndarray]]):
    # rays: [(o,d), ...], d assumed normalized
    if len(rays) < 2:
        return np.zeros(3), np.inf, False, "insufficient_valid_rays"

    A = np.zeros((3, 3), dtype=np.float64)
    b = np.zeros(3, dtype=np.float64)
    I = np.eye(3, dtype=np.float64)

    for o, d in rays:
        d = d.reshape(3, 1)
        P = I - d @ d.T
        A += P
        b += P @ o

    try:
        cond = np.linalg.cond(A)
        if cond < 1e12:
            X = np.linalg.solve(A, b)
            return X, cond, True, ""
        X, _, rank, _ = np.linalg.lstsq(A, b, rcond=None)
        return X, cond, False, f"ill_conditioned(rank={rank}, cond={cond:.2e})"
    except Exception as e:
        return np.zeros(3), np.inf, False, f"linalg_error: {e}"


def point_to_ray_dist_halfline(X: np.ndarray, o: np.ndarray, d: np.ndarray) -> float:
    d = d / (np.linalg.norm(d) + 1e-12)
    v = X - o
    t = float(np.dot(v, d))
    if t >= 0.0:
        return float(np.linalg.norm(v - t * d))
    return float(np.linalg.norm(v))


def verify_case(case_dir: Path, thresh_mm: float):
    cam_dir = case_dir / "Synthetic_camFile"
    csv_file = case_dir / "synthetic_wand_points.csv"

    if not cam_dir.exists() or not csv_file.exists():
        return [], [], {
            "case": case_dir.name,
            "status": "SKIP",
            "reason": "missing Synthetic_camFile or synthetic_wand_points.csv",
            "total_points": 0,
            "failed_points": 0,
            "max_err_mm": "",
            "wand_failed_frames": 0,
            "wand_max_abs_err_mm": "",
            "pass": False,
        }

    cams = load_cameras(cam_dir)
    if len(cams) < 2:
        return [], [], {
            "case": case_dir.name,
            "status": "SKIP",
            "reason": f"not_enough_cameras({len(cams)})",
            "total_points": 0,
            "failed_points": 0,
            "max_err_mm": "",
            "wand_failed_frames": 0,
            "wand_max_abs_err_mm": "",
            "pass": False,
        }

    obs = load_obs(csv_file)

    point_rows = []
    failed = 0
    max_err = -np.inf

    # frame -> endpoint -> reconstructed point
    recon_by_frame = defaultdict(dict)

    for (frame, pidx), cam_uv in sorted(obs.items()):
        rays = []
        invalid_los = 0

        for cid, uv in cam_uv.items():
            cam = cams.get(cid, None)
            if cam is None:
                continue

            try:
                st = cam.lineOfSightBatchStatus([make_pt2d(uv)])
            except Exception:
                invalid_los += 1
                continue

            if not st:
                invalid_los += 1
                continue

            ok, line, _ = st[0]
            if not ok:
                invalid_los += 1
                continue

            o = np.array([line.pt[0], line.pt[1], line.pt[2]], dtype=np.float64)
            d = np.array([line.unit_vector[0], line.unit_vector[1], line.unit_vector[2]], dtype=np.float64)
            if not np.all(np.isfinite(o)) or not np.all(np.isfinite(d)):
                invalid_los += 1
                continue

            dn = np.linalg.norm(d)
            if dn < 1e-12:
                invalid_los += 1
                continue

            d = d / dn
            rays.append((o, d))

        if len(rays) < 2:
            err = math.inf
            ok = False
            reason = "insufficient_valid_rays"
        else:
            X, cond, tri_ok, tri_reason = triangulate_from_rays(rays)
            if not np.all(np.isfinite(X)):
                err = math.inf
                ok = False
                reason = "triangulate_nonfinite"
            else:
                dists = [point_to_ray_dist_halfline(X, o, d) for (o, d) in rays]
                err = float(np.max(dists)) if dists else math.inf
                ok = bool(tri_ok) and (err < thresh_mm)
                reason = "" if ok else (tri_reason if tri_reason else "residual_over_threshold")
                # save reconstructed endpoint for wand check
                recon_by_frame[frame][pidx] = X.copy()

        if np.isfinite(err):
            max_err = max(max_err, err)

        if not ok:
            failed += 1

        point_rows.append({
            "case": case_dir.name,
            "frame": frame,
            "point_idx": pidx,
            "num_obs": len(cam_uv),
            "num_valid_rays": len(rays),
            "invalid_los": invalid_los,
            "max_residual_mm": err,
            "pass": ok,
            "reason": reason,
        })

    # --- Wand length verification per frame ---
    wand_rows = []
    wand_failed = 0
    wand_max_err = -np.inf

    for frame in sorted(recon_by_frame.keys()):
        pts = recon_by_frame[frame]
        if 0 not in pts or 1 not in pts:
            wand_err = math.inf
            wand_ok = False
            wand_reason = "missing_endpoint"
        else:
            L = float(np.linalg.norm(pts[1] - pts[0]))
            wand_err = abs(L - WAND_LEN_MM)
            wand_ok = (wand_err < WAND_THRESH_MM)
            wand_reason = "" if wand_ok else "wand_length_over_threshold"

        if np.isfinite(wand_err):
            wand_max_err = max(wand_max_err, wand_err)
        if not wand_ok:
            wand_failed += 1

        wand_rows.append({
            "case": case_dir.name,
            "frame": frame,
            "wand_abs_err_mm": wand_err,
            "pass": wand_ok,
            "reason": wand_reason,
        })

    total = len(point_rows)
    case_pass = (total > 0 and failed == 0 and wand_failed == 0)

    case_row = {
        "case": case_dir.name,
        "status": "OK",
        "reason": "",
        "total_points": total,
        "failed_points": failed,
        "max_err_mm": (max_err if np.isfinite(max_err) else ""),
        "wand_failed_frames": wand_failed,
        "wand_max_abs_err_mm": (wand_max_err if np.isfinite(wand_max_err) else ""),
        "pass": case_pass,
    }
    return point_rows, wand_rows, case_row


def main():
    if not ROOT.exists():
        raise RuntimeError(f"Root not found: {ROOT}")

    cases = sorted([p for p in ROOT.glob("case_*") if p.is_dir()], key=lambda p: p.name)

    out_points = ROOT / "verification_geometry_points.csv"
    out_wand = ROOT / "verification_wand_length.csv"
    out_cases = ROOT / "verification_geometry_cases.csv"
    out_summary = ROOT / "verification_geometry_summary.txt"

    all_points = []
    all_wand = []
    all_cases = []

    for case_dir in cases:
        point_rows, wand_rows, case_row = verify_case(case_dir, THRESH_MM)
        all_points.extend(point_rows)
        all_wand.extend(wand_rows)
        all_cases.append(case_row)
        print(
            f"[{case_row['case']}] {case_row['status']} "
            f"total={case_row['total_points']} failed={case_row['failed_points']} "
            f"wand_failed={case_row['wand_failed_frames']} pass={case_row['pass']}"
        )

    with out_points.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "case", "frame", "point_idx", "num_obs", "num_valid_rays", "invalid_los",
                "max_residual_mm", "pass", "reason"
            ],
        )
        w.writeheader()
        for r in all_points:
            w.writerow(r)

    with out_wand.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["case", "frame", "wand_abs_err_mm", "pass", "reason"],
        )
        w.writeheader()
        for r in all_wand:
            w.writerow(r)

    with out_cases.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "case", "status", "reason", "total_points", "failed_points", "max_err_mm",
                "wand_failed_frames", "wand_max_abs_err_mm", "pass"
            ],
        )
        w.writeheader()
        for r in all_cases:
            w.writerow(r)

    n_total = len(all_cases)
    n_ok = sum(1 for r in all_cases if r["status"] == "OK")
    n_skip = sum(1 for r in all_cases if r["status"] != "OK")
    n_pass = sum(1 for r in all_cases if r["status"] == "OK" and r["pass"])
    pts_total = sum(int(r["total_points"]) for r in all_cases if r["status"] == "OK")
    pts_fail = sum(int(r["failed_points"]) for r in all_cases if r["status"] == "OK")

    wand_total = len(all_wand)
    wand_failed = sum(1 for r in all_wand if not bool(r["pass"]))

    lines = [
        f"root: {ROOT}",
        f"threshold_mm: {THRESH_MM}",
        f"wand_len_mm: {WAND_LEN_MM}",
        f"wand_threshold_mm: {WAND_THRESH_MM}",
        f"cases_total: {n_total}",
        f"cases_ok: {n_ok}",
        f"cases_skip: {n_skip}",
        f"cases_pass_all_points: {n_pass}",
        f"points_total: {pts_total}",
        f"points_failed: {pts_fail}",
        f"wand_total_frames: {wand_total}",
        f"wand_failed_frames: {wand_failed}",
        f"overall_pass: {pts_fail == 0 and wand_failed == 0 and n_ok > 0}",
        "",
        f"points_csv: {out_points}",
        f"wand_csv: {out_wand}",
        f"cases_csv: {out_cases}",
    ]
    out_summary.write_text("\n".join(lines), encoding="utf-8")

    print("\n==== DONE ====")
    print(f"Summary: {out_summary}")
    print(f"Points : {out_points}")
    print(f"Wand   : {out_wand}")
    print(f"Cases  : {out_cases}")


if __name__ == "__main__":
    main()

[case_001] OK total=4000 failed=0 wand_failed=0 pass=True
[case_002] OK total=4000 failed=0 wand_failed=0 pass=True
[case_003] OK total=4000 failed=0 wand_failed=0 pass=True
[case_004] OK total=4000 failed=0 wand_failed=0 pass=True
[case_005] OK total=4000 failed=0 wand_failed=0 pass=True
[case_006] OK total=4000 failed=0 wand_failed=0 pass=True
[case_007] OK total=4000 failed=0 wand_failed=0 pass=True
[case_008] OK total=4000 failed=0 wand_failed=0 pass=True
[case_009] OK total=4000 failed=0 wand_failed=0 pass=True
[case_010] OK total=4000 failed=0 wand_failed=0 pass=True
[case_011] OK total=4000 failed=0 wand_failed=0 pass=True
[case_012] OK total=4000 failed=0 wand_failed=0 pass=True
[case_013] OK total=4000 failed=0 wand_failed=0 pass=True
[case_014] OK total=4000 failed=0 wand_failed=0 pass=True
[case_015] OK total=4000 failed=0 wand_failed=0 pass=True
[case_016] OK total=4000 failed=0 wand_failed=0 pass=True
[case_017] OK total=4000 failed=0 wand_failed=0 pass=True
[case_018] OK total=4000 failed=0 wand_failed=0 pass=True
[case_019] OK total=4000 failed=0 wand_failed=0 pass=True
[case_020] OK total=4000 failed=0 wand_failed=0 pass=True
[case_021] OK total=4000 failed=0 wand_failed=0 pass=True
[case_022] OK total=4000 failed=0 wand_failed=0 pass=True
[case_023] OK total=4000 failed=0 wand_failed=0 pass=True
[case_024] OK total=4000 failed=0 wand_failed=0 pass=True
[case_025] OK total=4000 failed=0 wand_failed=0 pass=True
[case_026] OK total=4000 failed=0 wand_failed=0 pass=True
[case_027] OK total=4000 failed=0 wand_failed=0 pass=True
[case_028] OK total=4000 failed=0 wand_failed=0 pass=True
[case_029] OK total=4000 failed=0 wand_failed=0 pass=True
[case_030] SKIP total=0 failed=0 wand_failed=0 pass=False

==== DONE ====
Summary: J:\Refraction_test\verification_geometry_summary.txt
Points : J:\Refraction_test\verification_geometry_points.csv
Wand   : J:\Refraction_test\verification_wand_length.csv
Cases  : J:\Refraction_test\verification_geometry_cases.csv